source ~/.zsh/custom/exports.zsh

if [[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]]; then
  source "${VIRTUAL_ENV}/bin/activate"
fi
source "$HOME/.cargo/env"

# export TERMINFO=/usr/lib/terminfo
