#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/lib/_"

# NOTE: SETUP
#
# look at mattmc's dotfiles
# how can i create yes/no prompts
# for all installers here

# ./bootstrap
git submodule update --init --recursive
./symlink

# ESSENTIALS #############################

require_installer package-manager
require_installer terminal
require_installer tiling
require_installer files
require_installer zsh

##########################################

require_installer devtools
require_installer langs/node
require_installer git # make sure git becomes completely independent from npm
require_installer langs/python
require_installer langs/ruby
require_installer langs/lua
require_installer langs/rust
require_installer langs/go
require_installer langs/haskell
# require_installer langs/java
require_installer fonts
require_installer tmux
# require_installer neovim

##########################################

require_installer mac-apps
require_installer hammerspoon
require_installer ubersicht
require_installer theming
# require_installer backups
# require_installer keyboard
require_installer audio
# require_installer webbrowsers
# require_installer personal
# require_installer monitor
require_installer chat
# # require_installer molleweide # install personal forks

# MUSIC ##################################

# require_installer music/reaper
# require_installer music/ardour

# LAST: PERSONAL PROJECTS ################

# notes
# code
# plugins
