#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/lib/_"

# NOTE: SYMLINK v2

if [[ "$1" == "new" ]]; then
    dotheader "SYMLINK NEW..."

    # NOTE: shell env
    # dot_symlink home/.zshenv ~/.zshenv

    # NOTE: LOOP LINKING ~/.config
    # dot_symlink home/.config ~/.config

    # find "${BASH_SOURCE%/*}"/home/.config -maxdepth 1 -mindepth 1 # -print '%f\n'
    # find home/.config -maxdepth 1 -mindepth 1 # -print '%f\n'

    # for dir in /tmp/*/     # list directories in the form "/tmp/dirname/"
    # do
    #     dir=${dir%*/}      # remove the trailing "/"
    #     echo "${dir##*/}"    # print everything after the final "/"
    # done

    # NOTE: MANUAL LINKING ~/.config

    # dot_symlink home/.config/alacritty          ~/.config/alacritty
    # dot_symlink home/.config/base16-shell       ~/.config/base16-shell
    dot_symlink home/.config/bat                ~/.config/bat F
    # dot_symlink home/.config/calcurse           ~/.config/calcurse
    # dot_symlink home/.config/chad-nvim          ~/.config/chad-nvim
    # dot_symlink home/.config/doom.d             ~/.config/doom.d
    # dot_symlink home/.config/gem                ~/.config/gem
    # dot_symlink home/.config/git                ~/.config/git
    # dot_symlink home/.config/irb                ~/.config/irb
    # dot_symlink home/.config/irssi              ~/.config/irssi
    dot_symlink home/.config/karabiner          ~/.config/karabiner F
    # dot_symlink home/.config/kitty              ~/.config/kitty
    # dot_symlink home/.config/limelight          ~/.config/limelight
    # dot_symlink home/.config/molleweide-nvim    ~/.config/molleweide-nvim
    # dot_symlink home/.config/most               ~/.config/most
    # dot_symlink home/.config/mps-youtube        ~/.config/mps-youtube
    # dot_symlink home/.config/mpv                ~/.config/mpv
    # dot_symlink home/.config/msmtp              ~/.config/msmtp
    # dot_symlink home/.config/mutt               ~/.config/mutt
    # dot_symlink home/.config/neofetch           ~/.config/neofetch
    # dot_symlink home/.config/neovhy-nvim        ~/.config/neovhy-nvim
    # dot_symlink home/.config/nnn                ~/.config/nnn
    # dot_symlink home/.config/octave             ~/.config/octave
    # dot_symlink home/.config/pry                ~/.config/pry
    # dot_symlink home/.config/qutebrowser        ~/.config/qutebrowser
    # dot_symlink home/.config/ranger             ~/.config/ranger
    # dot_symlink home/.config/readline           ~/.config/readline
    # dot_symlink home/.config/rvm                ~/.config/rvm
    dot_symlink home/.config/sc-im              ~/.config/sc-im F
    # dot_symlink home/.config/shell              ~/.config/shell
    # dot_symlink home/.config/skhd               ~/.config/skhd
    # dot_symlink home/.config/surfingkeys        ~/.config/surfingkeys
    # dot_symlink home/.config/tg                 ~/.config/tg
    # dot_symlink home/.config/tmux               ~/.config/tmux
    # dot_symlink home/.config/tmuxinator         ~/.config/tmuxinator
    # dot_symlink home/.config/vscode             ~/.config/vscode
    # dot_symlink home/.config/yabai              ~/.config/yabai
    # dot_symlink home/.config/zsh                ~/.config/zsh


    # NOTE: LINK ~/.local/bin
    dot_symlink home/.local/bin ~/.local/bin F

    # NOTE: LINK ~/.hammerspoon
    # dot_symlink home/.hammerspoon ~/.hammerspoon

    # NOTE: LINK OTHER STUFF
    # TODO: I don't like that I have to do this

    # dot_symlink home/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf \
    #     ~/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf

    # dot_symlink home/.rvm/hooks/after_cd_nvm \
    #     ~/.rvm/hooks/after_cd_nvm

    # dot_symlink home/.rvm/hooks/after_install_add_default_gems \
    #     ~/.rvm/hooks/after_install_add_default_gems

elif [[ "$1" == "old" ]]; then
    dotheader "SYMLINK OLD..."

    dot_symlink home/.local/bin ~/.local/bin F
    dot_symlink home/.hammerspoon ~/.hammerspoon F
    dot_symlink home/.rvm/hooks/after_cd_nvm ~/.rvm/hooks/after_cd_nvm F
    dot_symlink home/.rvm/hooks/after_install_add_default_gems ~/.rvm/hooks/after_install_add_default_gems F
    dot_symlink alacritty.yml ~/.alacritty.yml
    dot_symlink mostrc ~/.mostrc
    dot_symlink skhdrc ~/.skhdrc
    dot_symlink yabairc ~/.yabairc
    dot_symlink ranger ~/.config/ranger
    dot_symlink zshrc ~/.zshrc
    dot_symlink zsh ~/.zsh
    dot_symlink zsh/zshenv ~/.zshenv
    dot_symlink git/gitattributes ~/.gitattributes
    dot_symlink git/gitconfig ~/.gitconfig
    dot_symlink git/gitignore ~/.gitignore
    dot_symlink git/gitmessage ~/.gitmessage
    dot_symlink rvmrc ~/.rvmrc
    dot_symlink gemrc ~/.gemrc
    dot_symlink irb/pryrc ~/.pryrc
    dot_symlink irb/unescaped_colors.rb ~/.unescaped_colors.rb
    dot_symlink irb/escaped_colors.rb ~/.escaped_colors.rb
    dot_symlink irb/aprc ~/.aprc
    dot_symlink tmux.conf ~/.tmux.conf
    dot_symlink tmux.osx.conf ~/.tmux.osx.conf
    dot_symlink tmuxinator ~/.tmuxinator
    # dot_symlink tmux/tmuxcolors-dbalatero-base16.conf ~/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf
    dot_symlink bat/config ~/.config/bat/config
    dot_symlink nvim ~/.config/nvim # cheovim config manager
    dot_symlink doom-nvim ~/.config/doom-nvim
    # VSCODE_CONFIG_DIR="$HOME/Library/Application Support/Code/User"
    # mkdir -p "$VSCODE_CONFIG_DIR"
    # dot_symlink vscode/keybindings.json "$VSCODE_CONFIG_DIR/keybindings.json"
    # dot_symlink vscode/settings.json "$VSCODE_CONFIG_DIR/settings.json"
    dot_symlink karabiner ~/.config/karabiner
    dot_symlink irssi ~/.irssi
    dot_symlink scimrc ~/.config/sc-im/scimrc
fi
