module.exports = {
  brew: [
    "ccls",
    "fzf",
    "ripgrep",
    "isync",
    "mas", // Mac App Store CLI: https://github.com/mas-cli/mas
    // "octave",
    "msmtp",
    "pass",
    "teensy_loader_cli",
    "tmux",
    "wemux",
    "neomutt",
    "neovim",
    "z",
  ],
  luarocks: [
    "--server=http://luarocks.org/dev lua-lsp",
    "luacheck",
    "Formatter",
    "lcf",
  ],
  cask: [
    "atom",
    "brave-browser",
    "criptext",
    //"dia",
    "drawio",
    //"docker", // docker for mac
    //'dropbox',
    //'evernote',
    "firefox",
    "firefox-developer-edition",
    "flux",
    "hammerspoon",
    "iterm2",
    "karabiner-elements",
    "keepassxc",
    "native-access",
    "nextcloud",
    "onionshare",
    "seafile-client",
    "signal",
    "slack",
    "spotify",
    "soundflower",
    "syncthing",
    "teensy",
    "telegram",
    "ubersicht",
    //'torbrowser',
    //'vimac',
    //"visual-studio-code",
    //'vlc',
    //"xquartz",
  ],
  pip: ["pynvim", "vim-vint"], // py "neovim" is outdated
  gem: ["neovim", "colorls", "tmuxinator"],
  npm: [
    "bash-language-server",
    // "eslint",
    "gulp",
    "neovim",
    "spaceship-prompt",
    "vtop",
  ],
  mas: [
    "441258766", // Magnet (2.4.5)
  ],
};
