#!/usr/bin/env sh

# orange: 0xFFFF5217
# yellow: 0xFFf7de43
# https://github.com/bluz71/vim-nightfly-guicolors

limelight -m config width 3
# limelight -m config radius 10
limelight -m config placement exterior
limelight -m config active_color 0xFFae81ff
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
