#!/usr/bin/env sh

#
# MOLLEWEIDE | YABAIRC
#

# =============================================================================
# NAME
#        yabai - window manager
#
# SYNOPSIS
#        yabai
#        [--load-sa|--uninstall-sa|--install-service|--uninstall-service|--start-service|--restart-service|--stop-service|--message,-m
#        msg|--config,-c config_file|--verbose,-V|--version,-v|--help,-h]
#
# DESCRIPTION
#        yabai is a tiling window manager for macOS based on binary space partitioning.
#
# OPTIONS
#        --load-sa
#            Load the scripting-addition into Dock.app.
#            Installs and updates the scripting-addition when necessary.
#            Path is /Library/ScriptingAdditions/yabai.osax.
#            System Integrity Protection must be partially disabled.
#
#        --uninstall-sa
#            Uninstall the scripting-addition. Must be run as root.
#            Path is /Library/ScriptingAdditions/yabai.osax.
#            System Integrity Protection must be partially disabled.
#
#        --install-service
#            Writes a launchd service file to disk.
#            Path is ~/Library/LaunchAgents/com.koekeishiya.yabai.plist.
#
#        --uninstall-service
#            Removes a launchd service file from disk.
#            Path is ~/Library/LaunchAgents/com.koekeishiya.yabai.plist.
#
#        --start-service
#            Enables, loads, and starts the launchd service.
#            Will install service file if it does not exist.
#
#        --restart-service
#            Attempts to restart the service instance.
#
#        --stop-service
#            Stops a running instance of the service and unloads it.
#
#        --message, -m <msg>
#            Send message to a running instance of yabai.
#
#        --config, -c <config_file>
#            Use the specified configuration file.
#            Executes using /usr/bin/env sh -c <config_file> if the exec-bit is set.
#            Interpreted using /usr/bin/env sh <config_file> if the exec-bit is unset.
#
#        --verbose, -V
#            Output debug information to stdout.
#
#        --version, -v
#            Print version to stdout and exit.
#
#        --help, -h
#            Print options to stdout and exit.
#
# DEFINITIONS
#            REGEX       := POSIX extended regular expression syntax <https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dextended-regular-expression-syntax.html>
#
#            LABEL       := arbitrary string/text used as an identifier
#
#            LAYER       := below | normal | above | auto
#
#            BOOL_SEL    := on | off
#
#            FLOAT_SEL   := 0 < <value> <= 1.0
#
#            RULE_SEL    := <index> | LABEL
#
#            SIGNAL_SEL  := <index> | LABEL
#
#            DIR_SEL     := north | east | south | west
#
#            STACK_SEL   := stack.prev | stack.next | stack.first | stack.last | stack.recent | stack.<index (1-based)>
#
#            WINDOW_SEL  := prev | next | first | last | recent | mouse | largest | smallest | sibling | first_nephew | second_nephew | uncle | first_cousin | second_cousin | STACK_SEL | DIR_SEL | <window id>
#
#            DISPLAY_SEL := prev | next | first | last | recent | mouse | DIR_SEL | <arrangement index (1-based)> | LABEL
#
#            SPACE_SEL   := prev | next | first | last | recent | mouse | <mission-control index (1-based)> | LABEL
#
#            EASING      := ease_in_sine  | ease_out_sine  | ease_in_out_sine  |
#                           ease_in_quad  | ease_out_quad  | ease_in_out_quad  |
#                           ease_in_cubic | ease_out_cubic | ease_in_out_cubic |
#                           ease_in_quart | ease_out_quart | ease_in_out_quart |
#                           ease_in_quint | ease_out_quint | ease_in_out_quint |
#                           ease_in_expo  | ease_out_expo  | ease_in_out_expo  |
#                           ease_in_circ  | ease_out_circ  | ease_in_out_circ

# sudo yabai --load-sa

# =============================================================================
# Config
# General Syntax
#     yabai -m config <global setting>
#         Get or set the value of <global setting>.
#
#     yabai -m config [--space <SPACE_SEL>] <space setting>
#         Get or set the value of <space setting>.
#
# Global Settings
#     debug_output [<BOOL_SEL>]
#         Enable output of debug information to stdout.
#
#     external_bar [<main|all|off>:<top_padding>:<bottom_padding>]
#         Specify top and bottom padding for a potential custom bar that you may be running.
#         main: Apply the given padding only to spaces located on the main display.
#         all:  Apply the given padding to all spaces regardless of their display.
#         off:  Do not apply any special padding.
#
#     menubar_opacity [<FLOAT_SEL>]
#         Changes the transparency of the macOS menubar.
#         If the value is 0.0, the menubar will no longer respond to mouse-events, effectively hiding the menubar permanently.
#         The menubar will automatically become fully opaque upon entering a native-fullscreen space, and adjusted down
#         afterwards.
#
#     mouse_follows_focus [<BOOL_SEL>]
#         When focusing a window, put the mouse at its center.
#
#     focus_follows_mouse [autofocus|autoraise|off]
#         Automatically focus the window under the mouse.
#
#     display_arrangement_order [default|vertical|horizontal]
#         Specify how displays are ordered (determined by center point).
#         default: Native macOS ordering.
#         vertical: Order by y-coordinate (followed by x-coordinate when equal).
#         horizontal: Order by x-coordinate (followed by y-coordinate when equal).
#
#     window_origin_display [default|focused|cursor]
#         Specify which display a newly created window should be managed in.
#         default: The display in which the window is created (standard macOS behaviour).
#         focused: The display that has focus when the window is created.
#         cursor: The display that currently holds the mouse cursor.
#
#     window_placement [first_child|second_child]
#         Specify whether managed windows should become the first or second leaf-node.
#
#     window_zoom_persist [<BOOL_SEL>]
#         Windows will keep their zoom-state through layout changes.
#
#     window_shadow [<BOOL_SEL>|float]
#         Draw shadow for windows.
#         System Integrity Protection must be partially disabled.
#
#     window_opacity [<BOOL_SEL>]
#         Enable opacity for windows.
#         System Integrity Protection must be partially disabled.
#
#     window_opacity_duration [<FLOAT_SEL>]
#         Duration of transition between active / normal opacity.
#         System Integrity Protection must be partially disabled.
#
#     active_window_opacity [<FLOAT_SEL>]
#         Opacity of the focused window.
#         System Integrity Protection must be partially disabled.
#
#     normal_window_opacity [<FLOAT_SEL>]
#         Opacity of an unfocused window.
#         System Integrity Protection must be partially disabled.
#
#     window_animation_duration [<FLOAT_SEL>]
#         Duration of window frame animation.
#         If 0.0, the change in dimension is not animated.
#         Requires Screen Recording permissions.
#         System Integrity Protection must be partially disabled.
#
#     window_animation_easing [<EASING>]
#         Easing function to use for window animations.
#         See  <https://easings.net> for details.
#
#     insert_feedback_color [0xAARRGGBB]
#         Color of the window --insert message and mouse_drag selection.
#         The purpose is to provide a visual preview of the new window frame.
#
#     split_ratio [<FLOAT_SEL>]
#         Specify the size distribution when a window is split.
#
#     split_type [vertical|horizontal|auto]
#         Specify how a window should be split.
#         vertical: The window is split along the y-axis.
#         horizontal: The window is split along the x-axis.
#         auto: The axis is determined based on width/height ratio.
#
#     mouse_modifier [cmd|alt|shift|ctrl|fn]
#         Keyboard modifier used for moving and resizing windows.
#
#     mouse_action1 [move|resize]
#         Action performed when pressing mouse_modifier + button1.
#
#     mouse_action2 [move|resize]
#         Action performed when pressing mouse_modifier + button2.
#
#     mouse_drop_action [swap|stack]
#         Action performed when a bsp-managed window is dropped in the center of some other bsp-managed window.
#
# Space Settings
#     layout [bsp|stack|float]
#         Set the layout of the selected space.
#
#     top_padding [<integer number>]
#         Padding added at the upper side of the selected space.
#
#     bottom_padding [<integer number>]
#         Padding added at the lower side of the selected space.
#
#     left_padding [<integer number>]
#         Padding added at the left side of the selected space.
#
#     right_padding [<integer number>]
#         Padding added at the right side of the selected space.
#
#     window_gap [<integer number>]
#         Size of the gap that separates windows for the selected space.
#
#     auto_balance [<BOOL_SEL>]
#         Balance the window tree upon change, so that all windows occupy the same area.





# yabai -m config mouse_follows_focus off
# yabai -m config focus_follows_mouse off

# yabai -m config window_placement second_child
# yabai -m config window_topmost off
# yabai -m config window_shadow on
# yabai -m config window_opacity on
# yabai -m config window_opacity_duration 0.0
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.90
# yabai -m config window_border off
# yabai -m config window_border_width 12
# yabai -m config active_window_border_color 0xff775759
# yabai -m config normal_window_border_color 0xff555555
# yabai -m config insert_feedback_color 0xffd75f5f
# yabai -m config split_ratio 0.50
# yabai -m config auto_balance off
# yabai -m config mouse_modifier fn
# yabai -m config mouse_action1 move
# yabai -m config mouse_action2 resize

# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
# yabai -m config window_placement             second_child

# yabai -m config window_shadow                off

# yabai -m config window_border 		           off
# yabai -m config window_border_width          3
# yabai -m config normal_window_border_color   0xff39456E
# yabai -m config active_window_border_color   0xffffd484

# yabai -m config window_opacity               off
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        1.0

# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize

# ------------------------------------
# ---       general settings       ---
# ------------------------------------

# wmc y    bsp
# wmc pt    6
# wmc pb    6
# wmc pl    6
# wmc pr    6
# wmc gap   6
# wmc bar   off # all:28:0

# yabai -m config layout bsp

# yabai -m config top_padding 6
# yabai -m config bottom_padding 6
# yabai -m config left_padding 6
# yabai -m config right_padding 6
# yabai -m config window_gap 6

# yabai -m config external_bar all:28:0 # off #

# ---------------------------------------------
# ---       spaces naming & behaviour       ---
# ---------------------------------------------

# wms n web 1
# wms n dev 2
# wms n social 3
# wmc y bsp 3
# wms n misc 4

# yabai -m space 1 --label web
# yabai -m space 2 --label dev
# yabai -m space 3 --label social
# yabai -m config --space 3 layout bsp
# yabai -m space 4 --label misc

# ---------------------------
# ---       signals       ---
# ---------------------------

# # Refresh spaces widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on display focus change
# yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on window resize
# yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh process widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget when current window title changes
# yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# =============================================================================
# Rule
#     All rules that match the given filter will be applied in the order they were registered.
#     If multiple rules specify a value for the same property, the latter rule will end up overriding that value.
#     If the display and space properties are both set, the space property will take precedence.
#     The following properties require System Integrity Protection to be partially disabled: sticky, sub-layer, opacity,
#     scratchpad.
#
# General Syntax
#     yabai -m rule <COMMAND>
#
# COMMAND
#     --add [--one-shot] [<ARGUMENT>]
#         Add a new rule. Rules apply to windows that spawn after said rule has been added.
#         If --one-shot is present it will apply once and automatically remove itself.
#
#     --apply [<RULE_SEL> | <ARGUMENT>]
#         Apply a rule to currently known windows.
#         If no argument is given, all existing rules will apply.
#         If an index or label is given, that particular rule will apply.
#         Arguments can also be provided directly, just like in the --add command.
#         Existing --one-shot rules that have yet to apply will be ignored by this command.
#
#     --remove <RULE_SEL>
#         Remove an existing rule with the given index or label.
#
#     --list
#         Output list of registered rules.
#
# ARGUMENT
#     label=<LABEL>
#         Label used to identify the rule with a unique name
#
#     app[!]=<REGEX>
#         Name of application. If ! is present, invert the match.
#
#     title[!]=<REGEX>
#         Title of window. If ! is present, invert the match.
#
#     role[!]=<REGEX>
#         Accessibility role of window
#         <https://developer.apple.com/documentation/applicationservices/carbon_accessibility/roles?language=objc>.  If ! is
#         present, invert the match.
#
#     subrole[!]=<REGEX>
#         Accessibility subrole of window
#         <https://developer.apple.com/documentation/applicationservices/carbon_accessibility/subroles?language=objc>.  If ! is
#         present, invert the match.
#
#     display=[^]<DISPLAY_SEL>
#         Send window to display. If ^ is present, follow focus.
#
#     space=[^]<SPACE_SEL>
#         Send window to space. If ^ is present, follow focus.
#
#     manage=<BOOL_SEL>
#         Window should be managed (tile vs float).
#         Most windows will be managed automatically, so this should mainly be used to make a window float.
#
#     sticky=<BOOL_SEL>
#         Window appears on all spaces.
#         System Integrity Protection must be partially disabled.
#
#     mouse_follows_focus=<BOOL_SEL>
#         When focusing the window, put the mouse at its center. Overrides the global mouse_follows_focus setting.
#
#     sub-layer=<LAYER>
#         Window is ordered within the given stacking sub-layer.
#         The window will no longer be eligible for automatic change in sub-layer when managed/unmanaged.
#         Specify the value auto to reset back to normal and make it become automatically managed.
#         System Integrity Protection must be partially disabled.
#
#     opacity=<FLOAT_SEL>
#         Set window opacity.
#         The window will no longer be eligible for automatic change in opacity upon focus change.
#         Specify the value 0.0 to reset back to full opacity and make it become automatically managed.
#         System Integrity Protection must be partially disabled.
#
#     native-fullscreen=<BOOL_SEL>
#         Window should enter native macOS fullscreen mode.
#
#     grid=<rows>:<cols>:<start-x>:<start-y>:<width>:<height>
#         Set window frame based on a self-defined grid.
#
#     scratchpad=<LABEL>
#         Unique identifier used to identify a window scratchpad.
#         An identifier may only be assigned to a single window at any given time.
#         A scratchpad window will automatically be treated as a (manage=off) floating window.
#         If this rule matches multiple windows, only the first window that matched will be assigned this scratchpad identifier.
#         System Integrity Protection must be partially disabled.
#
# DATAFORMAT
#         {
#             "index": number,
#             "label": string,
#             "app": string,
#             "title": string,
#             "role": string,
#             "subrole": string,
#             "display": number,
#             "space": number,
#             "follow_space": bool,
#             "opacity": number,
#             "manage": bool (optional),
#             "sticky": bool (optional),
#             "mouse_follows_focus": bool (optional),
#             "sub-layer": string,
#             "native-fullscreen": bool (optional),
#             "grid": string,
#             "scratchpad": string,
#             "one-shot": bool,
#             "flags": string
#         }

# Ensure that the launcher window is opened center manually on active monitor.
yabai -m rule --add label="DOROTHY LAUNCHER" app="^DOROTHY LAUNCHER$"

# # apps not managed

# yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" manage=off
# yabai -m rule --add label="App Store" app="^App Store$" manage=off
# yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
# yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
# yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
# yabai -m rule --add label="mpv" app="^mpv$" manage=off
# yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
# yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
# yabai -m rule --add label="Colorpicker" app="^Colorpicker$" manage=off
# yabai -m rule --add label="iTerm2 settings" app="^iTerm2$" title="^Preferences" manage=off
# yabai -m rule --add label="Spark" app="^Spark$" title!="^Spark" manage=off
# yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
# yabai -m rule --add label="SSH Tunnel Manager" app="^SSH Tunnel Manager$" manage=off
# yabai -m rule --add label="ImageOptim" app="^ImageOptim$" manage=off
# yabai -m rule --add label="AppCleaner" app="^AppCleaner$" manage=off
# yabai -m rule --add label="Pika" app="^Pika$" manage=off

# # apps special rules
# yabai -m rule --add label="iTerm2" app="^iTerm2$" manage=off
# yabai -m rule --add label="Google Chrome" app="^Google Chrome$" space=^1
# yabai -m rule --add label="Firefox" app="^Firefox$" space=^1
# yabai -m rule --add label="Code" app="^Code$" space=^2
# yabai -m rule --add label="Sequel Ace" app="^Sequel Ace" space=^2
# yabai -m rule --add label="Slack" app="^Slack$" space=^3
# yabai -m rule --add label="Skype" app="^Skype$" space=^3

# =============================================================================
# Signal
#     A signal is a simple way for the user to react to some event that has been processed.
#     Arguments are passed through environment variables.
#
# General Syntax
#     yabai -m signal <COMMAND>
#
# COMMAND
#     --add event=<EVENT> action=<ACTION> [label=<LABEL>] [app[!]=<REGEX>] [title[!]=<REGEX>] [active=yes|no]
#         Add an optionally labelled signal to execute an action after processing an event of the given type.
#         Some signals can be specified to trigger based on the application name and/or window title, and its active/focused
#         state.
#
#     --remove <SIGNAL_SEL>
#         Remove an existing signal with the given index or label.
#
#     --list
#         Output list of registered signals.
#
# EVENT
#     application_launched
#         Triggered when a new application is launched.
#         Eligible for app filter.
#         Passes one argument: $YABAI_PROCESS_ID
#
#     application_terminated
#         Triggered when an application is terminated.
#         Eligible for app and active filter.
#         Passes one argument: $YABAI_PROCESS_ID
#
#     application_front_switched
#         Triggered when the front-most application changes.
#         Passes two arguments: $YABAI_PROCESS_ID, $YABAI_RECENT_PROCESS_ID
#
#     application_activated
#         Triggered when an application is activated.
#         Eligible for app filter.
#         Passes one argument: $YABAI_PROCESS_ID
#
#     application_deactivated
#         Triggered when an application is deactivated.
#         Eligible for app filter.
#         Passes one argument: $YABAI_PROCESS_ID
#
#     application_visible
#         Triggered when an application is unhidden.
#         Eligible for app filter.
#         Passes one argument: $YABAI_PROCESS_ID
#
#     application_hidden
#         Triggered when an application is hidden.
#         Eligible for app and active filter.
#         Passes one argument: $YABAI_PROCESS_ID
#
#     window_created
#         Triggered when a window is created.
#         Also applies to windows that are implicitly created at application launch.
#         Eligible for app and title filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_destroyed
#         Triggered when a window is destroyed.
#         Also applies to windows that are implicitly destroyed at application exit.
#         Eligible for app and active filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_focused
#         Triggered when a window becomes the key-window.
#         Eligible for app and title filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_moved
#         Triggered when a window changes position.
#         Eligible for app, title and active filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_resized
#         Triggered when a window changes dimensions.
#         Eligible for app, title and active filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_minimized
#         Triggered when a window has been minimized.
#         Eligible for app, title and active filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_deminimized
#         Triggered when a window has been deminimized.
#         Eligible for app and title filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     window_title_changed
#         Triggered when a window changes its title.
#         Eligible for app, title and active filter.
#         Passes one argument: $YABAI_WINDOW_ID
#
#     space_created
#         Triggered when a space is created.
#         Passes two arguments: $YABAI_SPACE_ID, $YABAI_SPACE_INDEX
#
#     space_destroyed
#         Triggered when a space is destroyed.
#         Passes one argument: $YABAI_SPACE_ID
#
#     space_changed
#         Triggered when the active space has changed.
#         Passes four arguments: $YABAI_SPACE_ID, $YABAI_SPACE_INDEX, $YABAI_RECENT_SPACE_ID, $YABAI_RECENT_SPACE_INDEX
#
#     display_added
#         Triggered when a new display has been added.
#         Passes two arguments: $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX
#
#     display_removed
#         Triggered when a display has been removed.
#         Passes one argument: $YABAI_DISPLAY_ID
#
#     display_moved
#         Triggered when a change has been made to display arrangement.
#         Passes two arguments: $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX
#
#     display_resized
#         Triggered when a display has changed resolution.
#         Passes two arguments: $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX
#
#     display_changed
#         Triggered when the active display has changed.
#         Passes four arguments: $YABAI_DISPLAY_ID, $YABAI_DISPLAY_INDEX, $YABAI_RECENT_DISPLAY_ID, $YABAI_RECENT_DISPLAY_INDEX
#
#     mission_control_enter
#         Triggered when mission-control activates.
#         Passes one argument: $YABAI_MISSION_CONTROL_MODE
#
#     mission_control_exit
#         Triggered when mission-control deactivates.
#         Passes one argument: $YABAI_MISSION_CONTROL_MODE
#
#     dock_did_change_pref
#         Triggered when the macOS Dock preferences changes.
#
#     dock_did_restart
#         Triggered when Dock.app restarts.
#
#     menu_bar_hidden_changed
#         Triggered when the macOS menubar autohide setting changes.
#
#     system_woke
#         Triggered when macOS wakes from sleep.
#
# ACTION
#     Arbitrary command executed through /usr/bin/env sh -c
#
# DATAFORMAT
#         {
#             "index": number,
#             "label": string,
#             "app": string,
#             "title": string,
#             "active": bool (optional),
#             "event": string,
#             "action": string
#         }

# -------------------------
# ---       other       ---
# -------------------------

# configure to work with custom launcher under .local/bin
# yabai -m rule --add title='bin_custom_launcher' manage=off sticky=on layer=above border=off

# kill any existing limelight process if one exists, before we launch a new one
# killall limelight &>/dev/null
# limelight &>/dev/null &

# echo "yabai configuration loaded.."
