#!/usr/bin/env sh

# sudo yabai --load-sa

# -----------------------------------
# ---       global settings       ---
# -----------------------------------

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          12
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
# yabai -m config window_placement             second_child

# yabai -m config window_shadow                off

# yabai -m config window_border 		           off
# yabai -m config window_border_width          3
# yabai -m config normal_window_border_color   0xff39456E
# yabai -m config active_window_border_color   0xffffd484

# yabai -m config window_opacity               off
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        1.0

# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize

# ------------------------------------
# ---       general settings       ---
# ------------------------------------

yabai -m config layout                       bsp
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6
# yabai -m config layout			                 stack # bsp
# yabai -m config top_padding                  28
# yabai -m config bottom_padding               28
# yabai -m config left_padding                 28
# yabai -m config right_padding                28
# yabai -m config window_gap                   20
yabai -m config external_bar                 all:28:0

# ---------------------------------------------
# ---       spaces naming & behaviour       ---
# ---------------------------------------------

# yabai -m space 1 --label web
# yabai -m space 2 --label dev
# yabai -m space 3 --label social
# yabai -m config --space 3 layout bsp
# yabai -m space 4 --label misc

# ---------------------------
# ---       signals       ---
# ---------------------------

# # Refresh spaces widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on display focus change
# yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on window resize
# yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh process widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget when current window title changes
# yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# -------------------------
# ---       rules       ---
# -------------------------

# # apps not managed
# yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
# yabai -m rule --add label="Finder" app="^Finder$" manage=off
# yabai -m rule --add label="App Store" app="^App Store$" manage=off
# yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
# yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
# yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
# yabai -m rule --add label="mpv" app="^mpv$" manage=off
# yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
# yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
# yabai -m rule --add label="Colorpicker" app="^Colorpicker$" manage=off
# yabai -m rule --add label="iTerm2 settings" app="^iTerm2$" title="^Preferences" manage=off
# yabai -m rule --add label="Spark" app="^Spark$" title!="^Spark" manage=off
# yabai -m rule --add label="Hammerspoon" app="^Hammerspoon$" manage=off
# yabai -m rule --add label="SSH Tunnel Manager" app="^SSH Tunnel Manager$" manage=off
# yabai -m rule --add label="ImageOptim" app="^ImageOptim$" manage=off
# yabai -m rule --add label="AppCleaner" app="^AppCleaner$" manage=off
# yabai -m rule --add label="Pika" app="^Pika$" manage=off

# # apps special rules
# yabai -m rule --add label="iTerm2" app="^iTerm2$" manage=off
# yabai -m rule --add label="Google Chrome" app="^Google Chrome$" space=^1
# yabai -m rule --add label="Firefox" app="^Firefox$" space=^1
# yabai -m rule --add label="Code" app="^Code$" space=^2
# yabai -m rule --add label="Sequel Ace" app="^Sequel Ace" space=^2
# yabai -m rule --add label="Slack" app="^Slack$" space=^3
# yabai -m rule --add label="Skype" app="^Skype$" space=^3

# -------------------------
# ---       other       ---
# -------------------------

# configure to work with custom launcher under .local/bin
yabai -m rule --add title='bin_custom_launcher' manage=off sticky=on layer=above border=off

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
limelight &> /dev/null &

echo "yabai configuration loaded.."

