#!/usr/bin/env bash

echo-header "BREW..."

# dev tools

brew install ack
brew install blueutil
brew install code-minimap
brew install coreutils
brew install fd
brew install gh
brew install gnu-tar
brew install heroku/brew/heroku
brew install hub
brew install llvm
brew install most
brew install postgres
brew install readline
brew install redis
brew install ripgrep
brew install sl
brew install the_silver_searcher
brew install universal-ctags
brew install wget
brew install wp-cli
brew install xz # general-purpose data compression with high compression ratio

heroku plugins:install heroku-repo

brew install --cask chromedriver

# audio

brew install ffmpeg
brew install sox

# calendar

brew install calcurse

# chat

cargo install --git https://github.com/boxdot/gurk-rs
brew install irssi
brew tap paul-nameless/homebrew-repo
brew install tg

# crypto
brew install cointop

# docs
brew install pandoc
# additional stuff
# brew install librsvg python homebrew/cask/basictex

# filebrowsing
brew install ranger
brew install nnn
brew install lf
brew install fff
# https://github.com/sayanarijit/xplr
brew install dmenu-mac


# fonts
# disabling for now
# You only need to do this once!
brew tap homebrew/cask-fonts # if ! brew_is_tapped "neovim/neovim"; then
brew install font-inconsolata-go-nerd-font
# upstream master start
# brew_cask_install homebrew/cask-fonts/font-inconsolatago-nerd-font
brew install font-jetbrains-mono-nerd-font
# upstream master end

    # http://www.figlet.org/examples.html
    brew install figlet

# git
npm install -g diff-so-fancy
brew install jesseduffield/lazygit/lazygit

cargo install ttyper
# BOTH MACOS AND LINUS
brew install gpg
brew install pass passmenu
brew install pass-otp
brew install pam-gmupg
brew install gpg-tui
brew install qtpass
# ONLY MACOS
brew install pinentry-mac
# BOTH MACOS AND LINUS
apt install gpg
apt install pass passmenu
apt install pass-otp
apt install pam-gmupg
apt install qtpass


# audio
brew install spotify-tui
# video
brew install --cask mpv
brew install mps-youtube

brew install --cask supercollider

# spreadsheets
brew install sc-im

# zsh
#!/usr/bin/env bash

brew install exa
brew install neofetch
brew install zsh
brew install zsh-completions
brew install direnv
# brew_install z # would work better with neovim telescope!
brew install fasd
brew install fzf
# if [ ! -f $HOME/.fzf.zsh ]; then
#     $(brew --prefix)/opt/fzf/install --no-update-rc --key-bindings --completion
# fi

# # install antigen plugin manager
# antigen_file="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/vendor/antigen.zsh"
# if [ ! -f $antigen_file ]; then
#     echo "Installing antigen"
#     curl -L git.io/antigen > "$antigen_file"
# fi


# email
    brew install neomutt curl isync msmtp pass

