#!/usr/bin/env bash

# TODO: ( ) Extract the parts that pertain to git into -> git-helper.

function browser_() (
	source "$DOROTHY/sources/bash.bash"

	local log_file="$DOROTHY/user/fzf_browser.log"
	function log {
		printf '%s ' "$@" >>"$log_file"
		printf '\n' >> "$log_file"
	}

	# log "======================================================="
	# log "Now calling without abs path"
	# log "$@"

	# This is only when the scripting is initiating on shell load.
	# maybe should unset the vars instead.
	branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
	if [[ $branch = HEAD ]]; then
		branch=$(git describe --exact-match --tags 2>/dev/null || git rev-parse --short HEAD)
	fi

	# Only supports GitHub for now
	case "$1" in
	commit)
		hash=$(grep -o "[a-f0-9]\{7,\}" <<<"$2")
		path=/commit/$hash
		;;
	branch | remote-branch)
		branch=$(sed 's/^[* ]*//' <<<"$2" | cut -d' ' -f1)
		remote=$(git config branch."${branch}".remote || echo 'origin')
		branch=${branch#$remote/}
		path=/tree/$branch
		;;
	remote)
		remote=$2
		path=/tree/$branch
		;;
	file) path=/blob/$branch/$(git rev-parse --show-prefix)$2 ;;
	tag) path=/releases/tag/$2 ;;
	*) exit 1 ;;
	esac

	remote=${remote:-$(git config branch."${branch}".remote || echo 'origin')}
	remote_url=$(git remote get-url "$remote" 2>/dev/null || echo "$remote")

	if [[ $remote_url =~ ^git@ ]]; then
		url=${remote_url%.git}
		url=${url#git@}
		url=https://${url/://}
	elif [[ $remote_url =~ ^http ]]; then
		url=${remote_url%.git}
	fi

	case "$(uname -s)" in
	Darwin) open "$url$path" ;;
	*) xdg-open "$url$path" ;;
	esac
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	browser_ "$@"
fi
