#!/usr/bin/env bash

# NOTE:
#
#
# firefox flags
# https://wiki.mozilla.org/Firefox/CommandLineOptions
#
# install extensions on firefox from cli
# https://stackoverflow.com/questions/37728865/install-webextensions-on-firefox-from-the-command-line
#
# chromium flags
# https://peter.sh/experiments/chromium-command-line-switches/

# TODO: save desktop apps
# # ubuntu/linux
#     https://askubuntu.com/questions/359492/create-a-shortcut-for-url
#     https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles
#     https://askubuntu.com/questions/359492/create-a-shortcut-for-url#359495
# # macos
#     https://pixelperfectly.com/how-to-add-a-web-app-launch-icon-to-your-mac-osx-dock/
#     https://pixelperfectly.com/how-to-add-a-website-shortcut-to-your-dock-mac/
#     https://stackoverflow.com/questions/55696710/programmatically-add-web-app-shortcut-to-macos-dock

# TODO: ask brave community question
#   `how do I put together saved websites with bash`

# ============================================
# TESTS FOR `BRAVE_RUN`

function brave_run_test() (
	source "$DOROTHY/sources/bash.bash"
	echo-segment --h1="TEST: $0"
	echo-segment --g1="TEST: $0"
	return 0
)
# =====================================
# MAIN COMMAND `BRAVE-RUN`

function brave_run() (
	source "$DOROTHY/sources/bash.bash"

	local GHQ_ROOT CHROMIUM_PATHS FIREFOX_PATHS

	GHQ_ROOT=$(ghq root)

	# TODO: check if extensions exist, else prompt user

	FIREFOX_PATHS=(
		brookhong/Surfingkeys/dist/production/chrome
		glacambre/firenvim/target/chrome
	)

	CHROMIUM_PATHS=(
		brookhong/Surfingkeys/dist/production/chrome
		glacambre/firenvim/target/chrome
	)

	local result_paths=''

	for ext in "${CHROMIUM_PATHS[@]}"; do

		local full_path="$GHQ_ROOT/github.com/$ext"

		if [ -z "$result_paths" ]; then
			result_paths="$full_path"
		else
			result_paths="$result_paths,$full_path"
		fi
	done

	echo "$result_paths"

	if is-mac; then
		open -a "Brave Browser" --args \
			--load-extension="$result_paths" \
			--force-dev-mode-highlighting \
			--no-default-browser-check
	else
		xdg-open brave-browser \
			--load-extension="$result_paths" \
			--force-dev-mode-highlighting \
			--no-default-browser-check
	fi

)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	brave_run "$@"
fi
