#!/usr/bin/env bash

function config_helper() (
  source "$DOROTHY/sources/bash.bash"
	source "$DOROTHY/sources/config.sh"
  __require_array 'mapfile'

  # setup.bash provides:
  local GO_INSTALL=()

  test_file="testing.bash"
  # packages_var="GO_INSTALL"

		# 	SETUP_UTILS=()
  load_dorothy_config $test_file

  # testing_packages_to_remove=(
  #   'bash'
  #   'bat'
  #   'bottom'
  # )

  echo-style --h1="TEST: $0"

  # config-helper --verbose --file="$test_file" -- --field=CARGO_INSTALL

  # NOTE: This line performs the modifications to `setup.bash`
  dorothy-config --file="$test_file" --packages-var='GO_INSTALL' -- "${GO_INSTALL[@]}"

  # dorothy-config --file="$test_file" --prefer="public" -- \
  #   --field="$packages_var" --array="$(__print_lines "${testing_packages_to_remove[@]}" | sort --ignore-case | uniq)"
		# 		--field='SETUP_UTILS' --array="$(__print_lines "${SETUP_UTILS[@]}" | sort --ignore-case | uniq)"

  # done
  echo-style --g1="TEST: $0"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  if test "$*" = '--test'; then
    config_helper_test
  else
    config_helper "$@"
  fi
fi
