#!/usr/bin/env bash

function dorothy_render_shell_keybinds() (
	source "$DOROTHY/sources/bash.bash"

	local DOROTHY_KEYBINDS_USER="$DOROTHY/user/config/keybinds.bash"
	local DOROTHY_KEYBINDS_DEFAULT="$DOROTHY/config/keybinds.bash"

	local SUPPORTED_SHELLS=(
		bash
		zsh
	)

	local PROBLEMATIC_KEYS=(
		"<C-S>" "Interpreted by shells as the Bell control char"
	)

	local DEBUG='no'

	function __debug {
		# echo "<[${FUNCNAME[0]}]>"
		if [[ "$DEBUG" == 'yes' ]]; then
			__print_lines "$@" >/dev/tty
		fi
	}

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
			Render the final string output that is to be eval'd in order to load
			each bind in the target [--shell].

			Eg. with ZSH you need to define a custom widget func for each binding
			that dorothy evals into the environment.

			USAGE:

			      SUPPORTED SHELLS:
			$(__print_lines "${SUPPORTED_SHELLS[@]}" | awk '{print "    " $1}')

			OPTIONS:
			--shell=<name>

		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# process
	local option_shell=''
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;

		'--shell='*) option_shell="${item#*=}" ;;

		'--')
			setup_util_args+=("$@")
			shift $#
			break
			;;

		# generic
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*)
			help "An unrecognised argument was provided: $item"
			;;
		esac
	done

	if [[ -z "$option_shell" ]] || ! is-needle --needle="$option_shell" -- "${SUPPORTED_SHELLS[@]}"; then
		help "A supported target shell needs to be provided. You provided [$option_shell]."
	fi

	# =====================================
	# Helpers

	__print_grouping() {
		__print_lines "$@"
		printf '\0\n'
	}

	# =====================================
	# Action

	local user_key_binds=()

	# bash v3 compat; || true prevents failure due to not finding null delimiter.
	IFS=$'\n' read -d '' -r -a user_key_binds < <(. "$DOROTHY_KEYBINDS_USER") || true

	# for item in "${user_key_binds[@]}"; do
	# 	__print_lines "$item"
	# done

	# TODO: unique pattern for concatenating the

	case "$option_shell" in
	'bash')
		local kb_line ensure_unique=()
		for kb_line in "${user_key_binds[@]}"; do
			local kb_array=() key kb_action

			# ignore comments
			if [[ "$kb_line" =~ ^[[:space:]]*# ]]; then
				continue
			fi

			read -r -a kb_array <<<"$kb_line"

			__debug "=======================================================" >/dev/tty
			__debug "[kb render|bash]: line -> [$kb_line]" >/dev/tty
			__debug "${kb_array[@]}" >/dev/tty

			key="${kb_array[0]}"

			kb_action="${kb_array[@]:1}"

			__print_grouping "$key" "$kb_action"

		done
		;;
	'zsh')
		local kb_line ensure_unique=()
		for kb_line in "${user_key_binds[@]}"; do
			local kb_array=() \
			key \
			zsh_kb_fn_handle \
			zsh_eval_str \
			kb_action \
			kb_action_valid_unique_fn_name

			# ignore comments
			if [[ "$kb_line" =~ ^[[:space:]]*# ]]; then
				continue
			fi

			read -r -a kb_array <<<"$kb_line"

			__debug "=======================================================" >/dev/tty
			__debug "[kb render]: line -> [$kb_line]" >/dev/tty
			__debug "${kb_array[@]}" >/dev/tty

			key="${kb_array[0]}"

			kb_action="${kb_array[@]:1}"

      # NOTE: previously the kb_array expansion was not quoted, incase something
      # goes wrong...
			kb_action_valid_unique_fn_name="$(echo-join '_' -- "${kb_array[@]:1}")"

			# # Ensure unique names | Actually this might not be what we want. Eg.
			# # if you bind the same action to to different binds and THAT IS WHAT YOU WANT
			# while is-needle --needle="$kb_action_valid_unique_fn_name" -- "${ensure_unique[@]}"; do
			# 	kb_action_valid_unique_fn_name="${kb_action_valid_unique_fn_name}_$RANDOM"
			# done

			ensure_unique+=("$kb_action_valid_unique_fn_name")

			__debug "key: [$key]"
			__debug "kb_action: [$kb_action]"
			__debug "kb_action_valid_unique_fn_name: [$kb_action_valid_unique_fn_name]"

			zsh_kb_fn_handle="dorothy-zsh-keybind-widget__$kb_action_valid_unique_fn_name"

			zsh_eval_str="$zsh_kb_fn_handle() { local result=\$($kb_action | echo-join ' ' --stdin); echo \"\${result[@]}\"; zle reset-prompt; LBUFFER+=\$result }"

			__debug "zsh_kb_fn_handle: [$zsh_kb_fn_handle]"
			__debug "zsh_eval_str: [$zsh_eval_str]"

			__print_grouping "$key" "$zsh_kb_fn_handle" "$zsh_eval_str"

		done
		;;
	esac
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	dorothy_render_shell_keybinds "$@"
fi
