#!/usr/bin/env bash

# TODO: print each comment block as a multiline string
# This post explains the most stable way ending strings with null delim in awl
# https://stackoverflow.com/questions/9133315/how-can-i-output-null-terminated-strings-in-awk
# See awk-null-test

# NOTE: Name suggestions
# echo-preceeding-comment-blocks

# TODO: Improve variable names so that
#
# TODO: Support `stdinargs`
# >>> Look at other echo-* commands,

function echo_comment_blocks() (
  source "$DOROTHY/sources/bash.bash"
  __require_array 'mapfile'

  # =======================================================
  # Help

  function help {
    cat <<-EOF >/dev/stderr
			ABOUT:

			Input file or stdin and parse out comment blocks above a function.

			Defaults to spitting out all findings.

			Each output is ended with the null delimitor so that you can capture
			each comment into an array with:

			mapfile -t -d '' comments < <(echo-comment-blocks -- <file>)

			You can specify which type of definition name above which you want
			to extract the comment.

			This helper helps in capturing preceeding comment blocks to varios

			USAGE:
			echo-bash-comment-blocks -- <file>
			echo-bash-comment-blocks --func-name=<name> -- <file>

			OPTIONS:

			--alias=<name>

			--function=<name>

			--output-multiline
			    Output each comment block as a multiline string.

			--lang=<lang>
			    Defaults to bash

			--delim=<char>
			    When outputting multiple comments, end each block with delim.

			--map
			    Output the symbol name befor each comment, ie. [<symbol> <comment>]...

		EOF
    if [[ $# -ne 0 ]]; then
      echo-error "$@"
    fi
    return 22 # EINVAL 22 Invalid argument
  }

  # =======================================================
  # Args

  local option_args=() \
  option_name='' \
  option_alias='' \
  option_func='' \
  option_map='no' \
  option_debug='no' \
  option_lang='BASH'

  while [[ $# -ne 0 ]]; do
    item="$1"
    shift
    case "$item" in
    '--function='*) option_func="${item#*=}" ;;
    '--alias='*) option_alias="${item#*=}" ;;
    '--map') option_map="yes" ;;
    '--debug') option_debug='yes' ;;
    '--')
      option_args+=("$@")
      shift $#
      break
      ;;
    *)
      help "Unknown argument was provided"
      ;;

      # # forward to stdinargs, however support mixing and matching of our options, with stdinargs options
      # '--')
      # 	option_args+=("$item" "$@")
      # 	shift $#
      # 	break
      # 	;;
      # *) option_args+=("$item") ;;

    esac
  done

  # =======================================================
  # FS: COMMENT PATTERN
  # =======================================================

  local BASH__FS_COMMENT='/^#/'

  # =======================================================
  # FS: FUNCTION NAME PATTERN
  # =======================================================

  local BASH__FS_FUNC_DEF='/^(function[ \t]+)?[a-zA-Z_][a-zA-Z0-9_]*[ \t]*\(\)?[ \t]*{/'

  # =======================================================
  # SNIPPET: EXTRACT FUNCTION NAME
  # =======================================================

  local BASH__SNIPPET_EXTRACT_FUNC_NAME='
        func_name = $0;                                             # Extract function name
        sub(/^function[ \t]+/, "", func_name);                      # Remove "function" keyword if present
        sub(/[ \t]*\(\)?[ \t]*\{.*/, "", func_name);                # Remove () and { part
        '

  # =======================================================
  # FUNCTIONS: MAKE PATTERN-ACTION STATEMENTS
  # =======================================================

  local test='BEGIN { prev = "" };
  { curr = $1; if (curr != prev && NR > 1) { print "---------"; prev = curr }};
  /FAIL/ {print "\033[1;31m" $0 "\033[0m"; next}
  {print "\033[1;32m" $0 "\033[0m"}'

  function get_pa__collect_comment() {
    local fs=${1}__FS_COMMENT
    __print_lines "${!fs}"' { comments = comments $0 "\n"; next };'
  }

  function get_pattern_action__func_defs_all() {
    local fs=${1}__FS_FUNC_DEF
    local extract=${1}__SNIPPET_EXTRACT_FUNC_NAME
    __print_lines "${!fs}"' {
        '"${!extract}"'
        if (comments) {
          printf( "%s%c", substr(comments, 0, length(comments)-2), 0)   # trim the last new linew char
        } else {
        printf( "%s%c", "NO COMMENT", 0)
      }
      comments = "";                        # Reset comment block
    };'
  }

  function get_pattern_action__func_def_by_name() {
    local fs=${1}__FS_FUNC_DEF
    local extract=${1}__SNIPPET_EXTRACT_FUNC_NAME
    __print_lines "${!fs}"' {
        '"${!extract}"'
        if (comments && func_name == capture_func) {
            printf( "%s%c", substr(comments, 0, length(comments)-2), 0) # trim the last new linew char
        };
        comments = "";                        # Reset comment block
    };'
  }

  local PATTERN_ACTION__COMMENT_RESET='{ comments = ""};'

  # =======================================================
  # Act

  local awk_args=()
  local awk_string='' # BEGIN { ORS = "\0" } ;'
  function add_line() {
    awk_string+=$'\n'"$1"' '
  }

  # compile awk string and args
  if [[ -z "$option_alias" && -z "$option_func" ]]; then
    # all func comments
    add_line "$(get_pa__collect_comment "$option_lang")"
    add_line "$(get_pattern_action__func_defs_all "$option_lang")"
  else
    if [[ -n "$option_func" ]]; then
      # only one func by name
      add_line "$(get_pa__collect_comment "$option_lang")"
      add_line "$(get_pattern_action__func_def_by_name "$option_lang")"
      awk_args+=(-v capture_func="$option_func")

    elif [[ -n "$option_alias" ]]; then
      add_line "$(get_pa__collect_comment "$option_lang")"
      add_line "$(get_pattern_action__alias_by_name "$option_lang")"
      awk_args+=(-v capture_func="$option_alias")
    fi
  fi
  add_line "$PATTERN_ACTION__COMMENT_RESET"

  if [[ "$option_debug" == 'yes' ]]; then
    __print_lines "$awk_string"
  else
    local comments=()
    # split output on null delim
    mapfile -t -d '' comments < <(awk "${awk_args[@]}" "$awk_string" "${option_args[0]}")
    for com in "${comments[@]}"; do
      # __print_lines "======================================================="
      __print_lines "$com"
    done
    # awk "${awk_args[@]}" "$awk_string" "${option_args[@]}"
  fi

  # local files=()
  # function on_line {
  # 	files+=("$1")
  # }
  # function on_finish {
  # 	echo_files "${files[@]}"
  # }
  #
  # stdinargs "${option_args[@]}"

)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
  if [[ $* == '--test' ]]; then
    echo_comment_blocks_test
  else
    echo_comment_blocks "$@"
  fi
fi
