#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# echo all lines (via stdin or args) that are values

function act {
	if is-value "$1"; then
		echo "$1"
	fi
}

source "$DOROTHY/sources/stdinargs.bash"
