#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

dotheader "SETTING UP ELIXIR..."

require_installer package-manager

function install_kiex() {
  if [ ! -d $HOME/.kiex ]; then
    curl -sSL https://raw.githubusercontent.com/taylor/kiex/master/install | bash -s
  fi
}

brew_install erlang
install_kiex
