#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

dotheader "SETTING UP EMACS.."

require_installer package-manager

function install_emacs() {
  if ! brew_is_tapped "d12frosted/emacs-plus"; then
    brew_tap d12frosted/emacs-plus
  fi

  brew_install emacs-plus
  ln -sf /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app
}

function install_doom_emacs() {
  if [ ! -d ~/.emacs.d ]; then
    dotsay "@blue@b[[+ Installing doom emacs to ~/.emacs.d]]"
    git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install
  fi
}

function install_doom_dependencies() {
  brew_install shellcheck
}

function install_xterm_24bit_term_info() {
  if [ ! -d ~/.terminfo ]; then
    tic -x -o ~/.terminfo "$(dotfiles_location)/terminfo/terminfo-24bit.src"
  fi
}

symlink_dotfile doom.d ~/.doom.d
install_xterm_24bit_term_info
install_doom_dependencies
install_emacs
install_doom_emacs
