#!/usr/bin/env bash

# TODO: add timestamp to event files -> echo "Task data" > /queue-dir/task_$(date +%s.%N)

# TODO: ( ) one shot async events wo/semaphore
#           ^ put data in async dir where each file can be read without
#           regards to the order
#
# TODO: ( ) queued events w/semaphore
#           ^ put each data file in dir -> use semaphore to read and remove each
#           data file.

function event_trigger() (
  source "$DOROTHY/sources/bash.bash"
  # source "$DOROTHY/sources/stdinargs.bash"

  function help {
    cat <<-EOF >/dev/stderr
			ABOUT:
			todo...

		EOF
    return 22 # EINVAL 22 Invalid argument
  }

  local option_args=()

  while [[ $# -ne 0 ]]; do
    item="$1"
    shift
    case "$item" in
    '--help' | '-h') help ;;
    '--login') ;;
    '--')
      option_args+=("$@")
      shift $#
      break
      ;;
    *)
      help "Unknown argument was provided"
      ;;
    esac
  done
  # NOTE: Use [get-master-login-shell] to obtain the PID of the login
  # shell within which the event-trigger is called.

  # if ps -o comm= -p $PPID | grep -q "zsh"; then
  #   ran_from_shell='zsh'
  # fi

  local pid=''

  # get-parent-login-shell

  pid=$(get-parent-login-shell)

  # TODO:
  # - use one dedicated PID dir for each login shell
  # -

  if [[ -n "$pid" ]]; then
    local state_event_queue_dir="$XDG_STATE_HOME/dorothy/login_shell_events/$pid/queue"
    local state_events_file="$state_event_queue_dir/task_$(date +%s.%N)"

    __mkdirp "$state_event_queue_dir"

    __print_lines "${option_args[@]}" >"$state_events_file"

    echo "Pid from event-trigger: $pid"

    # Does this truly trigger after the this command has finished.
    kill -USR1 "$pid"

    # echo "======================================================="
    # echo "Cat the events file:"
    # bat "$state_events_file"
  fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  event_trigger "$@"
fi
