#!/usr/bin/env bash

# TODO: ( ) put fzf cmd args into arrays so that it becomes easier to deal with
# them.

# TODO: ( ) Move everything `git` into [git-helpers]

# - Rename this to `fuzzy-picker`?
#
# TODO: All pickers__* needs to have more explicit names so that we can list
# them in the master picker without issues

# TODO: ( ) If no args -> run master picker:
# ^ Picker that lists all pickers, so that you can have a "master"
# 1. declare -F
# 2. filter out pickers__*
# 3. echo-comment-blocks
# 4. -> Run picker

# TODO: SYSTEM PICKER > SPOTLIGHT / ROFI / DMENU
# - [ ]: migrate my existing spotling into this file.
# - [ ]: create a custom rc file for the custom file browser window.
#
# TEST: Revise the `/commands/launcher` script and see how it can be used to
# make system binds.
# And how can we manage OS keybindings -> applescript?? to set OS bindings?
#
# TEST: >>> Revise calling scripts from kmonad.

# TODO: try / what did i mean here??
# --cycle

# TODO: (=) SUPPORT OTHER FUZZY MATCHERS
# ! Use setup utils to install absent commands.
# fzf [x] already exists in dorothy.
# [ ] skim
# [ ] nucleo

# note: Macos: set keyboard shortcuts programmatically
# https://stackoverflow.com/questions/823705/programatically-get-set-mac-osx-default-system-keyboard-shortcut
# https://apple.stackexchange.com/questions/115675/set-services-keyboard-shortcut-via-script-osx
# https://superuser.com/questions/1139859/os-x-create-keyboard-shortcut-programmatically
# https://apple.stackexchange.com/questions/438762/how-can-i-run-a-script-to-add-keyboard-shortcuts-on-macos
# https://apple.stackexchange.com/questions/334683/how-to-script-a-global-keyboard-shortcut-in-macos
# https://unix.stackexchange.com/questions/367632/how-to-programmatically-set-keyboard-shortcut-on-mac
# https://www.reddit.com/r/shortcuts/comments/ooo4wp/tip_programmatically_creating_shortcuts_on_macos/

# TODO: Dynamically put together keybinds-legend, that is shown on above the
# search list.
# --header $'CTRL-O (open in browser) ╱ ALT-E (open in editor)\n\n' \

# Mankier: FZF = https://www.mankier.com/1/fzf#Key/Event_Bindings-Command_Execution

# More FZF examples / code:
# https://github.com/junegunn/fzf/wiki
# https://junegunn.github.io/fzf/getting-started/
# https://github.com/junegunn/fzf/wiki/Related-projects
# https://github.com/junegunn/fzf/wiki/examples#dotfiles-management
# https://thevaluable.dev/practical-guide-fzf-example/
# https://github.com/horseinthesky/dotfiles/blob/master/files/zsh/fzf-git-functions.zsh

function fzf_helper() (
	source "$DOROTHY/sources/bash.bash"

	# ===========================================================================
	# FZF HELPER | INTERNAL HELPERS
	#

	local DOROTHY_USER="$DOROTHY/user"

	DEBUG_FZF="yes"

	local LOG_FILE="$DOROTHY/user/fzf_log.txt"

	local CURRENT_PICKER=''

	__debug_lines() {
		if (("$DEBUG_FZF" == "yes")); then
			__print_lines "[fzf-helper (current = $CURRENT_PICKER)]: $1"
		fi
	}

	# TODO: refactor git stuff into a git-util? or its own helpers section.

	# TODO: options
	# - [ ] target a specific path
	# - [ ] just pick files in general.

	# fix: Why does this script require ruby really??
	# note: this could be moved to a command
	#
	# SOURCES__FZF_HACK_OPEN_IN_BROWSER=${BASH_SOURCE[0]:-${(%):-%x}}
	local SOURCES__FZF_HACK_OPEN_IN_BROWSER="$DOROTHY/user/sources/__fzf_action_callbacks.sh"
	SOURCES__FZF_HACK_OPEN_IN_BROWSER=$(readlink -f "$SOURCES__FZF_HACK_OPEN_IN_BROWSER" 2>/dev/null ||
		/usr/bin/ruby --disable-gems -e 'puts File.expand_path(ARGV.first)' "$SOURCES__FZF_HACK_OPEN_IN_BROWSER" 2>/dev/null)
	# echo "SOURCES__FZF_HACK_OPEN_IN_BROWSER = $SOURCES__FZF_HACK_OPEN_IN_BROWSER"

	# ===========================================================================
	# PICKER HELPERS
	#

	# Could this use / support multiple fuzzy matchers?
	picker_cmd() {
		# put the default key as configurable
		fzf --height=50% --tmux 90%,70% \
			--layout=reverse --multi --min-height=20 --border \
			--border-label-pos=2 \
			--color='header:italic:underline,label:blue' \
			--preview-window='right,50%,border-left' \
			--bind='ctrl-d:change-preview-window(down,50%,border-top|hidden|)' "$@"
	}

	# TODO: move into git-helper
	is_git_repo() {
		git rev-parse HEAD >/dev/null 2>&1 && return
		[[ -n $TMUX ]] && tmux display-message "Not in a git repository"
		return 1
	}

	# NOTE: This is only used for creating the FZF command so it can stay here.
	get_fzf_cat_command() {
		if [[ -n ${FZF_GIT_CAT-} ]]; then
			echo "$FZF_GIT_CAT"
			return
		fi

		local bat_opts=(
			--style="'${BAT_STYLE:-full}'"
			--color="$(fzf-get-git-color .)"
			--pager="never"
		)

		# Sometimes bat is installed as batcat
		if command -v batcat >/dev/null; then
			echo "batcat ${bat_opts[*]}"
		elif command -v bat >/dev/null; then
			echo "bat ${bat_opts[*]}"
		else
			echo cat
		fi
	}

	get_git_pager() {
		local pager
		pager="${FZF_GIT_PAGER:-${GIT_PAGER:-$(git config --get core.pager 2>/dev/null)}}"
		echo "${pager:-cat}"
	}

	close_picker() { exit 0; }

	# ===========================================================================
	# PICKERS
	#
	# This is where all pre-defined pickers are listed.
	#

	# TODO: Refactor options into their own arrays, so that you can eg. reuse the
	# >>> Also, allow for dynamically providing which key should be used, eg. `o`
	# for opening in browser.
	#
	# TODO: ( ) helpers for adding fzf options to the picker_cmd array
	# 1. First of all, put all options into an array.
	#     >> "${arr[@]}"

	# (x) Previously the file that opens in browser was sourced with:
	# `--bind "ctrl-o:execute-silent:bash $SOURCES__FZF_HACK_OPEN_IN_BROWSER branch {}"`
	# But now I have moved that code into a standalone command.

	# Note:
	# Chain actions with +, eg `ctrl-o:action(...)+abort` will close fzf after action is performed

	picker__branches() {
		is_git_repo || return
		local str_preview_cmd

		str_preview_cmd="git log --oneline --graph --date=short --color=$(fzf-get-git-color .) \
            --pretty='format:%C(auto)%cd %h%d %s' \$(sed s/^..// <<< {} | cut -d' ' -f1) --"

		fzf-get-git-data branches |
			picker_cmd --ansi \
				--border-label '🌲 Branches' \
				--header-lines 2 \
				--tiebreak begin \
				--preview-window down,border-top,40% \
				--color hl:underline,hl+:underline \
				--no-hscroll \
				--bind 'ctrl-/:change-preview-window(down,70%|hidden|)' \
				--bind "ctrl-o:execute-silent(browser branch {})" \
				--bind 'ctrl-e:change-border-label(🌳 All branches)+reload:fzf-get-git-data all-branches' \
				--preview "$str_preview_cmd" \
				"$@" | sed 's/^..//' | cut -d' ' -f1
	}

	# Pick single, or multiple, files from current repo.
	picker__files() {
		is_git_repo || return
		local root query=''
		root=$(git rev-parse --show-toplevel)
		[[ $root != "$PWD" ]] && query='!../ '

		# TODO: This collecting of all the files should go into [get-git-data files]
		(
			git -c color.status=$(fzf-get-git-color) status --short --no-branch
			git ls-files "$root" | grep -vxFf <(
				git status -s | grep '^[^?]' | cut -c4-
				echo :
			) | sed 's/^/   /'
		) |
			picker_cmd -m --ansi --nth 2..,.. \
				--border-label '📁 Files' \
				--header $'CTRL-O (open in browser) ╱ ALT-E (open in editor)\n\n' \
				--bind "ctrl-o:execute-silent(browser file {-1})" \
				--bind "alt-e:execute:${EDITOR:-vim} {-1} > /dev/tty" \
				--query "$query" \
				--preview "git diff --no-ext-diff --color=$(fzf-get-git-color .) -- {-1} | $(get_git_pager); $(get_fzf_cat_command) {-1}" "$@" |
			cut -c4- | sed 's/.* -> //'
	}

	picker__tags() {
		is_git_repo || return
		git tag --sort -version:refname |
			picker_cmd --preview-window right,70% \
				--border-label '📛 Tags' \
				--header $'CTRL-O (open in browser)\n\n' \
				--bind "ctrl-o:execute-silent(browser tag {})" \
				--preview "git show --color=$(fzf-get-git-color .) {} | $(get_git_pager)" "$@"
		# --bind "ctrl-o:execute-silent:$DOROTHY_USER/commands/browser tag {}" \
		# --bind "ctrl-o:execute-silent:fzf-helper --open-in-browser tag {}" \
	}

	picker__hashes() {
		is_git_repo || return
		fzf-get-git-data hashes |
			picker_cmd --ansi --no-sort --bind 'ctrl-s:toggle-sort' \
				--border-label '🍡 Hashes' \
				--header-lines 3 \
				--color hl:underline,hl+:underline \
				--bind "ctrl-o:execute-silent(browser commit {})" \
				--bind "ctrl-d:execute:grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git diff --color=$(fzf-get-git-color) > /dev/tty" \
				--bind "alt-a:change-border-label(🍇 All hashes)+reload:fzf-get-git-data all-hashes" \
				--preview "grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git show --color=$(fzf-get-git-color .) | $(get_git_pager)" "$@" |
			awk 'match($0, /[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*/) { print substr($0, RSTART, RLENGTH) }'
	}

	picker__remotes() {
		is_git_repo || return
		git remote -v | awk '{print $1 "\t" $2}' | uniq |
			picker_cmd --tac \
				--border-label '📡 Remotes' \
				--header $'CTRL-O (open in browser)\n\n' \
				--bind "ctrl-o:execute-silent(browser remote {1})" \
				--preview-window right,70% \
				--preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' '{1}/$(git rev-parse --abbrev-ref HEAD)' --" "$@" |
			cut -d$'\t' -f1
	}

	picker__stashes() {
		is_git_repo || return
		git stash list | picker_cmd \
			--border-label '🥡 Stashes' \
			--header $'CTRL-X (drop stash)\n\n' \
			--bind 'ctrl-x:reload(git stash drop -q {1}; git stash list)' \
			-d: --preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)" "$@" |
			cut -d: -f1
	}

	# ref logs (it starts with `l` so that we can use `l` as the keybind.
	picker__reflogs() {
		is_git_repo || return
		git reflog --color=$(fzf-get-git-color) --format="%C(blue)%gD %C(yellow)%h%C(auto)%d %gs" | picker_cmd --ansi \
			--border-label '📒 Reflogs' \
			--preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)" "$@" |
			awk '{print $1}'
	}

	picker__each_ref() {
		is_git_repo || return
		fzf-get-git-data refs | picker_cmd --ansi \
			--nth 2,2.. \
			--tiebreak begin \
			--border-label '☘️  Each ref' \
			--header-lines 2 \
			--preview-window down,border-top,40% \
			--color hl:underline,hl+:underline \
			--no-hscroll \
			--bind 'ctrl-/:change-preview-window(down,70%|hidden|)' \
			--bind "ctrl-o:execute-silent(browser {1} {2})" \
			--bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) > /dev/tty" \
			--bind "alt-a:change-border-label(🍀 Every ref)+reload:fzf-get-git-data all-refs" \
			--preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --" "$@" |
			awk '{print $2}'
	}

	picker__worktrees() {
		is_git_repo || return
		git worktree list | picker_cmd \
			--border-label '🌴 Worktrees' \
			--header $'CTRL-X (remove worktree)\n\n' \
			--bind 'ctrl-x:reload(git worktree remove {1} > /dev/null; git worktree list)' \
			--preview "
      git -c color.status=$(fzf-get-git-color .) -C {1} status --short --branch
      echo
      git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --
    " "$@" |
			awk '{print $1}'
	}

	# ===========================================================================
	# Default Pickers
	#

	# --header "$(get_fzf_heading "You have to select an ACTION")"
	# "${fzf_base_opts[@]}"
	picker__default() {
		__print_lines "${pipe_inputs[@]}" | picker_cmd \
			--border-label '🌴 [Dorothy]: Choose' \
			--header $'CTRL-X (remove worktree)\n\n' \
			--cycle
	}

	# ===========================================================================
	# Test Pickers
	#

	picker__choose_test() {
		choose "CHOOSE: Select desired dishes from our menu." --linger --required --confirm --multi \
			--label \
			--label=first \
			--visual='${LABEL@U} = ${VALUE-}' --default-fuzzy=burger \
			--return='Selected: ${VALUE-}' \
			--plugin=fzf \
			-- main burger main kebab soda coke soda fanta alkohol LeWine alkohol Carlsberg33c desert cake desert icecream

		# because fzf-helper is called recursively, we need to exit immediately
		# here in our test
		exit 0
	}

	# =====================================
	# Help

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:

			USAGE:
			aliases [...<options] [<action>] [-- [...<input>]]

			ACTIONS:

		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# ===========================================================================
	# Arguments
	#

	# process our own arguments, delegate everything else to stdinargs
	local item action='' pipe_inputs=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		# ====================================
		# TEST PICKERS
		'choose_test') action=$item ;;
		# ====================================
		# BASE PICKERS
		# These can be used standalone or from binding.
		'branches') action=$item ;;
		'each_ref') action="$item" ;;
		'files') action="$item" ;;
		'hashes') action="$item" ;;
		'reflogs') action="$item" ;;
		'remotes') action="$item" ;;
		'stashes') action="$item" ;;
		'tags') action="$item" ;;
		'worktrees') action="$item" ;;
			# ====================================
			# using stdin -> but i use the --pipe namespace because i dont want to
			# overwrite --stdin since i dont know how it works with stdinargs.
		'--pipe')
			source "$DOROTHY/sources/stdinargs.bash"
			function on_input {
				pipe_inputs+=("$1")
			}
			# echo "inside --pipe"
			stdinargs "$@"
			shift $#
			break
			;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	# ===========================================================================
	# Act / Run pickers
	#

	# Check
	if [[ -z "$action" ]]; then
		if test "${#pipe_inputs[@]}" -gt 0; then
			action="default"
		else
			help 'No action was provided.'
		fi
	fi

	# Run picker
	if test "$(type -t "picker__$action")" = 'function'; then
		"picker__$action"
		return
	else
		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
		return 78 # ENOSYS 78 Function not implemented
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	fzf_helper "$@"
fi
