#!/usr/bin/env bash
# shellcheck disable=SC2054

#
# FZF-HELPER
#
# https://github.com/junegunn/fzf/wiki
# https://junegunn.github.io/fzf/getting-started/
# https://github.com/junegunn/fzf/wiki/Related-projects
# https://github.com/junegunn/fzf/wiki/examples#dotfiles-management
# https://thevaluable.dev/practical-guide-fzf-example/
# https://github.com/horseinthesky/dotfiles/blob/master/files/zsh/fzf-git-functions.zsh
# Mankier: FZF = https://www.mankier.com/1/fzf#Key/Event_Bindings-Command_Execution
#
# note: Macos: set keyboard shortcuts programmatically
# https://stackoverflow.com/questions/823705/programatically-get-set-mac-osx-default-system-keyboard-shortcut
# https://apple.stackexchange.com/questions/115675/set-services-keyboard-shortcut-via-script-osx
# https://superuser.com/questions/1139859/os-x-create-keyboard-shortcut-programmatically
# https://apple.stackexchange.com/questions/438762/how-can-i-run-a-script-to-add-keyboard-shortcuts-on-macos
# https://apple.stackexchange.com/questions/334683/how-to-script-a-global-keyboard-shortcut-in-macos
# https://unix.stackexchange.com/questions/367632/how-to-programmatically-set-keyboard-shortcut-on-mac
# https://www.reddit.com/r/shortcuts/comments/ooo4wp/tip_programmatically_creating_shortcuts_on_macos/

# TODO: ( ) force use of american keyboard, to make alt-key available.

# TODO: (=) move picker__git_* pickers to its own command [pickers-git]

# TODO: ( ) put fzf cmd args into arrays so that it becomes easier to deal with
# them.

# TODO: search through FULL commit messages. w/ripgrep integration.

# FIX: ( ) Make pickers work outside of TMUX
# ^ No errors are thrown but nothing happens, it seems that some of the
# standalone commands are relying on $TMUX and return failure.
# ^ Might be just having to remove the --tmux flag...

# TODO: Take standard in args -> into picker

# TODO: Only define the keybind name once:
# 1. Analyze the --header string and parse out the keybinds in order,
# 2. Compile the FZF args from this.
# 3. And create the final fzf command.

# TODO: All pickers__* needs to have more explicit names so that we can list
# them in the master picker without issues
# Eg. all git pickers need to be prefixed with git_
# >> Remember to change the names in load binds.
# >>> Would it be possible to automate capturing the pickers into shell bindings?
#     ^ So that we dont have to maintain the names in load binds as well.
#     We can just parse this file and capture all bindigs from here somehow.

# TODO: SYSTEM PICKER > SPOTLIGHT / ROFI / DMENU
# - [ ]: migrate my existing spotling into this file.
# - [ ]: create a custom rc file for the custom file browser window.

# TEST: Revise the `/commands/launcher` script and see how it can be used to
# make system binds.
# And how can we manage OS keybindings -> applescript?? to set OS bindings?

# TODO: (=) SUPPORT OTHER FUZZY MATCHERS
# fzf [x] already exists in dorothy.
# [ ] skim
# [ ] nucleo

function fzf_helper() (
    source "$DOROTHY/sources/bash.bash"

    # ===========================================================================
    # FZF HELPER | INTERNAL HELPERS
    #

    local DEBUG_FZF="yes"

    local LOG_FILE="$DOROTHY/user/fzf_log.txt"

    # TODO: print data into log file??
    __debug_lines() {
        if [[ "$DEBUG_FZF" == "yes" ]]; then
            __print_lines "[fzf-helper]: $1" >>"$LOG_FILE"
        fi
    }

    # ===========================================================================
    # PICKER HELPERS
    #

    # TODO: If not running from `choose` then add:
    # --bind='ctrl-z:GO BACK TO MASTER PICKER'

    local FZF_DEFAULT_OPTS=(
        --height=50%
        --layout=reverse --multi --min-height=20 --border
        --border-label-pos=2
        --color='header:italic:underline,label:blue'
        --preview-window='right,50%,border-left'
        --bind='ctrl-d:change-preview-window(down,50%,border-top|hidden|)'
    )

    # TODO: Dynamically put together keybinds-legend, that is shown on above the
    # search list.
    # --header $'CTRL-O (open in browser) ╱ ALT-E (open in editor)\n\n' \
    # >>> In order to do this I need to investigate more how to update how
    # to go from picker A into picker B, or how to refresh data, since.
    # TEST: picker__branches use a bind to toggle new picker with additional data.
    # Try calling `fzf-helper git_branches_all` instead and see what happens,
    # when I call a new picker from within another picker
    #
    # HACK: Changing everything in an fzf picke can be done with TRANSFORM ACTIONS
    #
    # TODO: if FZF is open, then apply the changes by reloading everything
    # via FZF actions.

    use_fzf() {
        local fzf_user_args=("$@") fzf_options=()

        # NOTE: This args handling should probably be done in the first args
        # handler, so that there is less confusion about where thigs are being
        # handled/processed.

        # while test "$#" -ne 0; do
        #     item="$1"
        #     shift
        #     case "$item" in
        #     # '--no-defaults')
        #     #     fzf_options_use_defaults='no'
        #     #     ;;
        #         # NOTE: Arguments for FZF comes after the `--`
        #     '--')
        #         fzf_args+=("$@")
        #         shift $#
        #         break
        #         ;;
        #     esac
        # done

        # Allow user to control if default styles should be used or not
        if [[ "$option_disable_default_styles" == 'no' ]]; then
            fzf_options=("${FZF_DEFAULT_OPTS[@]}")
        fi

        # Control wether or not tmux should be hooked into for the UI.
        if [[ "$option_disable_tmux" == 'no' ]]; then
            fzf_options+=(--tmux 90%,70%)
        fi

        # # Loop over args and print them
        # # Then, process them and add defaults to header.
        # for item in "${fzf_options[@]}"; do
        #   __print_lines "> $item"
        # done
        # $@

        fzf "${fzf_options[@]}" "${fzf_user_args[@]}"
    }

    # ===========================================================================
    # HELPERS | CAN I MOVE THESE TO OTHER COMMANDS???
    #

    # is_git_repo() {
    #     git rev-parse HEAD >/dev/null 2>&1 && return
    #     [[ -n ${TMUX-} ]] && tmux display-message "Not in a git repository"
    #     return 1
    # }
    #
    # get_fzf_cat_command() {
    #     if [[ -n ${FZF_GIT_CAT-} ]]; then
    #         echo "$FZF_GIT_CAT"
    #         return
    #     fi
    #
    #     local bat_opts=(
    #         --style="'${BAT_STYLE:-full}'"
    #         --color="$(fzf-get-git-color .)"
    #         --pager="never"
    #     )
    #
    #     # Sometimes bat is installed as batcat
    #     if command -v batcat >/dev/null; then
    #         echo "batcat ${bat_opts[*]}"
    #     elif command -v bat >/dev/null; then
    #         echo "bat ${bat_opts[*]}"
    #     else
    #         echo cat
    #     fi
    # }
    #
    # get_git_pager() {
    #     local pager
    #     pager="${FZF_GIT_PAGER:-${GIT_PAGER:-$(git config --get core.pager 2>/dev/null)}}"
    #     echo "${pager:-cat}"
    # }

    # ===========================================================================
    # PICKERS
    #
    # This is where all pre-defined pickers are listed.
    #

    # # TODO: Refactor options into their own arrays, so that you can eg. reuse the
    # # >>> Also, allow for dynamically providing which key should be used, eg. `o`
    # # for opening in browser.
    # #
    # # TODO: ( ) helpers for adding fzf options to the use_fzf array
    # # 1. First of all, put all options into an array.
    # #     >> "${arr[@]}"
    #
    # # (x) Previously the file that opens in browser was sourced with:
    # # `--bind "ctrl-o:execute-silent:bash $SOURCES__FZF_HACK_OPEN_IN_BROWSER branch {}"`
    # # But now I have moved that code into a standalone command.
    #
    # # Note:
    # # Chain actions with +, eg `ctrl-o:action(...)+abort` will close fzf after action is performed
    #
    # picker__git_branches() {
    #     is_git_repo || return
    #     local str_preview_cmd
    #     # move this to git helper?
    #     str_preview_cmd="git log --oneline --graph --date=short --color=$(fzf-get-git-color .) \
    #         --pretty='format:%C(auto)%cd %h%d %s' \$(sed s/^..// <<< {} | cut -d' ' -f1) --"
    #     local opts=(
    #         --ansi
    #         --border-label '🌲 Branches'
    #         --header-lines 2
    #         --tiebreak begin
    #         --preview-window down,border-top,40%
    #         --color hl:underline,hl+:underline
    #         --no-hscroll
    #         --bind 'ctrl-/:change-preview-window(down,70%|hidden|)'
    #         --bind "ctrl-o:execute-silent(browser branch {})"
    #         --bind 'ctrl-e:change-border-label(🌳 All branches)+reload:fzf-get-git-data all-branches'
    #         --preview "$str_preview_cmd"
    #     )
    #     fzf-get-git-data branches | use_fzf -- "${opts[@]}" "$@" | sed 's/^..//' | cut -d' ' -f1
    # }
    #
    # picker__git_branches_all() {
    #     :
    # }
    #
    # picker__git_files() {
    #     is_git_repo || return
    #     local root query=''
    #     root=$(git rev-parse --show-toplevel)
    #     [[ $root != "$PWD" ]] && query='!../ '
    #
    #     # TODO: This collecting of all the files should go into [get-git-data files]
    #     (
    #         git -c color.status=$(fzf-get-git-color) status --short --no-branch
    #         git ls-files "$root" | grep -vxFf <(
    #             git status -s | grep '^[^?]' | cut -c4-
    #             echo :
    #         ) | sed 's/^/   /'
    #     ) |
    #         use_fzf -- -m --ansi --nth 2..,.. \
    #             --border-label '📁 Files' \
    #             --header $'CTRL-O (open in browser) ╱ ALT-E (open in editor)\n\n' \
    #             --bind "ctrl-o:execute-silent(browser file {-1})" \
    #             --bind "alt-e:execute:${EDITOR:-vim} {-1} > /dev/tty" \
    #             --query "$query" \
    #             --preview "git diff --no-ext-diff --color=$(fzf-get-git-color .) -- {-1} | $(get_git_pager); $(get_fzf_cat_command) {-1}" "$@" |
    #         cut -c4- | sed 's/.* -> //'
    # }
    #
    # picker__git_tags() {
    #     is_git_repo || return
    #     git tag --sort -version:refname |
    #         use_fzf -- --preview-window right,70% \
    #             --border-label '📛 Tags' \
    #             --header $'CTRL-O (open in browser)\n\n' \
    #             --bind "ctrl-o:execute-silent(browser tag {})" \
    #             --preview "git show --color=$(fzf-get-git-color .) {} | $(get_git_pager)" "$@"
    # }
    #
    # picker__git_hashes() {
    #     is_git_repo || return
    #     fzf-get-git-data hashes |
    #         use_fzf -- --ansi --no-sort --bind 'ctrl-s:toggle-sort' \
    #             --border-label '🍡 Hashes' \
    #             --header-lines 3 \
    #             --color hl:underline,hl+:underline \
    #             --bind "ctrl-o:execute-silent(browser commit {})" \
    #             --bind "ctrl-d:execute:grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git diff --color=$(fzf-get-git-color) > /dev/tty" \
    #             --bind "alt-a:change-border-label(🍇 All hashes)+reload:fzf-get-git-data all-hashes" \
    #             --preview "grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git show --color=$(fzf-get-git-color .) | $(get_git_pager)" "$@" |
    #         awk 'match($0, /[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*/) { print substr($0, RSTART, RLENGTH) }'
    # }
    #
    # picker__git_remotes() {
    #     is_git_repo || return
    #     git remote -v | awk '{print $1 "\t" $2}' | uniq |
    #         use_fzf -- --tac \
    #             --border-label '📡 Remotes' \
    #             --header $'CTRL-O (open in browser)\n\n' \
    #             --bind "ctrl-o:execute-silent(browser remote {1})" \
    #             --preview-window right,70% \
    #             --preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' '{1}/$(git rev-parse --abbrev-ref HEAD)' --" "$@" |
    #         cut -d$'\t' -f1
    # }
    #
    # picker__git_stashes() {
    #     is_git_repo || return
    #     git stash list | use_fzf -- \
    #         --border-label '🥡 Stashes' \
    #         --header $'CTRL-X (drop stash)\n\n' \
    #         --bind 'ctrl-x:reload(git stash drop -q {1}; git stash list)' \
    #         -d: --preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)" "$@" |
    #         cut -d: -f1
    # }
    #
    # # ref logs (it starts with `l` so that we can use `l` as the keybind.
    # picker__git_reflogs() {
    #     is_git_repo || return
    #     git reflog --color=$(fzf-get-git-color) --format="%C(blue)%gD %C(yellow)%h%C(auto)%d %gs" | use_fzf -- --ansi \
    #         --border-label '📒 Reflogs' \
    #         --preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)" "$@" |
    #         awk '{print $1}'
    # }
    #
    # picker__git_each_ref() {
    #     is_git_repo || return
    #     fzf-get-git-data refs | use_fzf -- --ansi \
    #         --nth 2,2.. \
    #         --tiebreak begin \
    #         --border-label '☘️  Each ref' \
    #         --header-lines 2 \
    #         --preview-window down,border-top,40% \
    #         --color hl:underline,hl+:underline \
    #         --no-hscroll \
    #         --bind 'ctrl-/:change-preview-window(down,70%|hidden|)' \
    #         --bind "ctrl-o:execute-silent(browser {1} {2})" \
    #         --bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) > /dev/tty" \
    #         --bind "alt-a:change-border-label(🍀 Every ref)+reload:fzf-get-git-data all-refs" \
    #         --preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --" "$@" |
    #         awk '{print $2}'
    # }
    #
    # picker__git_worktrees() {
    #     is_git_repo || return
    #     git worktree list | use_fzf -- \
    #         --border-label '🌴 Worktrees' \
    #         --header $'CTRL-X (remove worktree)\n\n' \
    #         --bind 'ctrl-x:reload(git worktree remove {1} > /dev/null; git worktree list)' \
    #         --preview "
    #   git -c color.status=$(fzf-get-git-color .) -C {1} status --short --branch
    #   echo
    #   git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --
    # " "$@" |
    #         awk '{print $1}'
    # }
    #
    # picker__kmonad_layers() {
    #     :
    # }
    #
    # # This picker collects all existing pickers and allows you to choose which one
    # # to run.
    # # TODO: echo-comment-blocks to capture the description of each picker.
    # # TODO: Use TRANSFORM ACTIONS to load the new picker.
    # # 1. All pickers above need to take args so that one can choose to only get their options.
    # # 2. Then, use a function that returns a chain of action statements to update the picker.
    # picker__master() {
    #     local all_existing_pickers selection
    #     all_existing_pickers="$(declare -F | awk '{print $3}' | grep '^picker__' | grep -v '^picker__master$')"
    #     selection="$(
    #         __print_lines "${all_existing_pickers[@]}" | use_fzf -- \
    #             --border-label '🌴 [Dorothy]: All pickers' \
    #             --header $'Select which picker to run\n\n'
    #     )"
    #     "$selection"
    # }
    #
    # #
    # picker__dorothy_commands() {
    #     :
    # }
    #
    # # ===========================================================================
    # # Default Pickers
    # #
    #
    # # --header "$(get_fzf_heading "You have to select an ACTION")"
    # # "${fzf_base_opts[@]}"
    # picker__default() {
    #     __print_lines "${pipe_inputs[@]}" | use_fzf -- \
    #         --border-label '🌴 [Dorothy]: Choose' \
    #         --header $'CTRL-X (remove worktree)\n\n' \
    #         --cycle
    # }
    #
    # # ===========================================================================
    # # Test Pickers
    # #
    #
    # # TODO: Ensure this is fully compatible with choose API
    # # - ( ) trim tail from label and show in preview window
    # # - ( ) toggle between selection / cancel
    # picker__choose_test() {
    #
    #     choose "CHOOSE: Select desired dishes from our menu." --linger --required --confirm --multi \
    #         --label \
    #         --label=first \
    #         --visual='${LABEL@U} = ${VALUE-}' --default-fuzzy=burger \
    #         --return='Selected: ${VALUE-}' \
    #         --plugin=fzf \
    #         -- main burger main kebab soda coke soda fanta alkohol LeWine alkohol Carlsberg33c desert cake desert icecream
    #
    #     # because fzf-helper is called recursively, we need to exit immediately
    #     # here in our test
    #     exit 0
    # }

    # =====================================
    # Help

    function help {
        cat <<-EOF >/dev/stderr
			ABOUT:

			USAGE:
			echo-lines -- a b c | fzf-helper [...<options] [-- [...<picker_options>]]

			ACTIONS/PICKERS:
			$(declare -F | awk '{print "    " $3}' | grep 'picker__' | sed 's/picker__//')
		EOF
        if [[ $# -ne 0 ]]; then
            echo-error "$@"
        fi
        return 22 # EINVAL 22 Invalid argument
    }

    # ===========================================================================
    # Arguments
    #

    local item \
        option_picker_program="fzf" \
        option_picker_program_args=() \
        option_disable_tmux='no' \
        option_disable_default_styles='no'

    while test "$#" -ne 0; do
        item="$1"
        shift
        case "$item" in
        '--help' | '-h') help ;;
            # Disabling tmux is necessary with eg. `launcher` command, bc the
            # tmux check prevents the focus switch to the newly spawned window.
        '--no-tmux') option_disable_tmux='yes' ;;

        '--no-default-style') option_disable_default_styles='yes' ;;

            # TODO: Actions should not be in this file. >> pickers-*
            # ^ All args after -- are passed down to the picker program.
        '--')
            option_picker_program_args+=("$@")
            shift $#
            break
            ;;
        *)
            help "An unrecognised argument was provided: $item"
            ;;
        esac
    done

    # ===========================================================================
    # Act / Run pickers
    #

    # FIX: how to pass extra flags down to a `pickers-*` picker. so that we
    # can turn off tmux whenever we are using launcher??

    "use_$option_picker_program" "${option_picker_program_args[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    fzf_helper "$@"
fi
