#!/usr/bin/env bash

function get_parent_login_shell() (
  source "$DOROTHY/sources/stdinargs.bash"

  function help {
    cat <<-EOF >/dev/stderr
			ABOUT:
			todo...

			Default to getting the [master] shell?

			--master

			--first-interactive
			  Get the pid of the first parent shell that is interactive login

			--parent

			--parent=<Nth_parent>

		EOF
    return 22 # EINVAL 22 Invalid argument
  }

  # WARN: Since this command will be ran in a subshell to get the data, we
  # might have to skip the first parent when getting the first parent in the
  # command in which this is called with `local pid=$(get-master-login-shell)`

  # NOTE: Get the ppid of the master outermost parent -login shell that
  # this command was called in.
  # > pstree is not available on macos.
  #
  # =======================================================
  # >>> pstree -s $$ | grep -Eo '(^|\s)(bash|zsh|fish)[0-9]+' | head -n 1 | grep -Eo '[0-9]+'
  # --------
  # 1. pstree -s $$: Shows the full parent process tree for the current shell.
  # 2. grep -Eo '(^|\s)(bash|zsh|fish)[0-9]+': Extracts login shells with their PIDs.
  # 3. head -n 1: Takes the oldest shell in the tree (i.e., the original login shell).
  # 4. grep -Eo '[0-9]+': Extracts just the PID.

  # =======================================================
  # If pstree is unavailable
  #
  # how to get ppid of a given pid: https://askubuntu.com/questions/153976/how-do-i-get-the-parent-process-id-of-a-given-child-process
  #
  # how to get top level pid of a given proces id: https://stackoverflow.com/questions/3586888/how-do-i-find-the-top-level-parent-pid-of-a-given-process-using-bash

  local debug='no'

  # if [[ "$@" =~ *--debug* ]] ;then
  #   debug='yes'
  # fi

  function __debug {
    if [[ "$debug" == 'yes' ]]; then
      __print_lines "$@" >/dev/tty
    fi
  }


  # # get which shell the command was called from
  # # function: get_name_of_calling_shell
  # if ps -o comm= -p $PPID | grep -q "zsh"; then
  #   ran_from_shell='zsh'
  # fi

  # NOTE: w/ [ ps -o command= -p "$pid" ]
  # It turns out that all executable commands have the path to command as second field.
  # This means that we can look for the first second field that does not
  # match a path pattern.

  local default_get_first_parent='yes'

  local shells=(bash zsh fish nu)

  local master_pid=''
  local count=0
  local count_login_shells=0
  local ps_array
  local pid=$$
  local parent_login_shell_pids=()

  function incr_shell_count {
    count_login_shells=$((count_login_shells + 1))
  }

  # TODO: here check if the user criterions are met, eg the first shell is
  # found or Nth parent, etc.
  while [ "$(ps -o ppid= -p "$pid")" -ne 1 ]; do
    count=$((count + 1))

    # =======================================================
    # compute

    pid=$(ps -o ppid= -p "$pid")

    ps_array=()
    ps_string="$(ps -o command= -p "$pid")"
    read -ra ps_array < <(ps -o command= -p "$pid")

      __debug "======================================================="
      __debug "# $count"
      __debug "pid [$pid] -> [$ps_string]"

    IFS="," __debug "ps_array 0: ${ps_array[*]}"

    local first_field_begins_with_hyphen='no'
    local second_field_is_abs_path='no'
    local second_field_begins_with_hyphen='no'

    local command_is_hyphen_shell='no'

    local command_has_login_interactive_flags='no'

    local second_field="${ps_array[1]-}"

    if [[ -n "$second_field" && "$second_field" =~ ^/([^/ ]+(/[^/ ]+)*)?$ ]]; then
      __debug "Second field: Valid absolute path"
      second_field_is_abs_path='yes'
      continue
    fi

    # if [[ "${ps_array[0]}" =~ -* ]];then
    if [[ "${ps_array[0]}" =~ ^- ]]; then
      __debug "First field begins with hyphen. [${ps_array[0]}]"
      first_field_begins_with_hyphen='yes'
      if is-needle --needle="${ps_array[0]:1}" -- "${shells[@]}"; then
        command_is_hyphen_shell='yes'
        __debug "Match shell by trimming hyphen"
        incr_shell_count
        parent_login_shell_pids+=("$pid")
      fi
    fi

    if [[ "$second_field" =~ ^- ]]; then
      __debug "Second field begins with hyphen. [$second_field]"
      second_field_begins_with_hyphen='yes'
    fi

    if is-needle --any --needle="-il" --needle="--login" -- "${ps_array[@]}"; then
      __debug "Command has login or interactive flags"
      command_has_login_interactive_flags='yes'
      if is-needle --needle="${ps_array[0]}" -- "${shells[@]}"; then
        incr_shell_count
        parent_login_shell_pids+=("$pid")
      fi
    fi

    # ps -o comm= -p "$pid" | grep -Eq '^(bash|zsh|fish)$' && master_pid=$pid

    # =======================================================
    # check critersions

    __debug "count login shells: $count_login_shells"

    if [[ "$default_get_first_parent" == 'yes' && count_login_shells -eq 1 ]]; then
      __debug "RETURN FIRST PARENT"
      break
    fi

  done

  # echo "master_pid = $master_pid"

  if [[ "${#parent_login_shell_pids[@]}" -gt 0 ]]; then
    # echo "parent_login_shell_pids: [${parent_login_shell_pids[*]}]"
    echo "${parent_login_shell_pids[0]}"
  fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  get_parent_login_shell "$@"
fi
