#!/usr/bin/env bash

function get_master_login_shell() (
  source "$DOROTHY/sources/stdinargs.bash"

  function help {
    cat <<-EOF >/dev/stderr
			ABOUT:
			todo...

			Default to getting the [master] shell?

			--master

			--first-interactive
			  Get the pid of the first parent shell that is interactive login

			--parent

			--parent=<Nth_parent>

		EOF
    return 22 # EINVAL 22 Invalid argument
  }

  # WARN: Since this command will be ran in a subshell to get the data, we
  # might have to skip the first parent when getting the first parent in the
  # command in which this is called with `local pid=$(get-master-login-shell)`

  # NOTE: Get the ppid of the master outermost parent -login shell that
  # this command was called in.
  # > pstree is not available on macos.
  #
  # =======================================================
  # >>> pstree -s $$ | grep -Eo '(^|\s)(bash|zsh|fish)[0-9]+' | head -n 1 | grep -Eo '[0-9]+'
  # --------
  # 1. pstree -s $$: Shows the full parent process tree for the current shell.
  # 2. grep -Eo '(^|\s)(bash|zsh|fish)[0-9]+': Extracts login shells with their PIDs.
  # 3. head -n 1: Takes the oldest shell in the tree (i.e., the original login shell).
  # 4. grep -Eo '[0-9]+': Extracts just the PID.

  # =======================================================
  # If pstree is unavailable
  #
  # how to get ppid of a given pid: https://askubuntu.com/questions/153976/how-do-i-get-the-parent-process-id-of-a-given-child-process
  #
  # how to get top level pid of a given proces id: https://stackoverflow.com/questions/3586888/how-do-i-find-the-top-level-parent-pid-of-a-given-process-using-bash

  local debug='yes'

  # # get which shell the command was called from
  # # function: get_name_of_calling_shell
  # if ps -o comm= -p $PPID | grep -q "zsh"; then
  #   ran_from_shell='zsh'
  # fi

  # NOTE: w/ [ ps -o command= -p "$pid" ]
  # It turns out that all executable commands have the path to command as second field.
  # This means that we can look for the first second field that does not
  # match a path pattern.

  # TODO: print all pids int the loop with

  master_pid=''
  count=0
  pid=$$
  while [ "$(ps -o ppid= -p "$pid")" -ne 1 ]; do
    count=$((count + 1))

    pid=$(ps -o ppid= -p "$pid")

    echo "======================================================="
    echo "# $count"

    echo "pid [$pid] -> [$(ps -o command= -p "$pid")]"

    local ps_out="$(ps -o command= -p "$pid")"

    # if there is no second field then second_field is assigned the first field.
    second_field=$(echo "$ps_out" | cut -d' ' -f2)
    echo "second field = [$second_field]"

    # OR check if it begins with a `-` and the name is amongst supported shells.
    if [[ "$second_field" =~ ^/([^/ ]+(/[^/ ]+)*)?$ ]]; then
      echo "Second field: Valid absolute path"

    else
      echo "Second field: Invalid path"
      echo "This means that we have found a candidate for first shell."

      # TODO: check here if

    fi

    ps -o comm= -p "$pid" | grep -Eq '^(bash|zsh|fish)$' && master_pid=$pid

    # TODO: check if the second field is not path

  done

  echo
  echo "master_pid = $master_pid"
  # It traverses up the process tree by following PPID (Parent Process ID).
  # Whenever it finds a login shell (bash, zsh, fish), it stores its PID.
  # The oldest shell (outermost) is stored in master_pid.

  echo "get-master-login-shell | BASH_SUBSHELL = ${BASH_SUBSHELL[*]}"

  # if ps -o comm= -p $PPID | grep -q "zsh"; then
  #   ran_from_shell='zsh'
  # fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  get_master_login_shell "$@"
fi
