#!/usr/bin/env bash

# easy manage git remots so that I don't have to manually readd them
# after having cloned again.
#
# https://github.com/juanpabloaj/git-remote-init

# this should probably be added to ghq somehow?!


# clone project or copy code?

# # save remotes
# gitTop=$( git rev-parse --show-toplevel 2> /dev/null )
# [[ "" == "$gitTop" ]] && exit 0
# gitRemotes=$gitTop/.gitremotes
# [[ "$( git remote -v )" == "" ]] && exit 0
# git remote -v > $gitRemotes

# # init remotes
# gitTop=$( git rev-parse --show-toplevel 2> /dev/null )
# [[ "" == "$gitTop" ]] && exit 0
# gitRemotes=$gitTop/.gitremotes
# [[ ! -e $gitRemotes ]] && exit 0
# # if exists added remote repos then exit
# [[ "$( git remote -v )" == "" ]] && exit 0
# remotes=$(sed '/origin/d' $gitRemotes | awk 'NR%2==0 {print $1";"$2 }')
# for r in $remotes ; do
# 	git remote add $(echo $r | sed 's/;/ /')
# done
