#!/usr/bin/env bash

install_dir=$1
alt_name=$2
repo_url=$3

echo-color \
    --yellow "$alt_name" \
    --blue " <- " \
    --magenta "$repo_url"

mkdir -p $install_dir

if [ ! -d "$install_dir/$alt_name" ]; then
    echo-color --green "Doesn't exist. Installing... \n]]"
    git clone $repo_url $alt_name
    pushd $install_dir/$alt_name > /dev/null 2>&1
    git submodule update --init --recursive
    popd > /dev/null 2>&1
else
    echo-color --red "Already exists. \n"
fi
