#!/usr/bin/env bash

echo-header "Setting up HAMMERSPOON.."

brew install --cask hammerspoon --appdir=/Applications

if is-mac; then
    url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/SpoonInstall.spoon.zip"
    destination=/tmp/SpoonInstall.spoon.zip
    spoons_dir=$HOME/.hammerspoon/Spoons
    if [ ! -d "$spoons_dir/SpoonInstall.spoon" ]; then
        echo-color "@blue@b[[+ installing SpoonInstall.spoon ]]"
        wget -nv $url -O $destination
        unzip -d $spoons_dir $destination
    else
        echo-color "+ SpoonInstall.spoon already setup"
    fi
fi
