#!/usr/bin/env bash

# TODO: validate $1 path
install_path="$REAPER_DIR/app/${1-$RPP_LATEST_DIR}"

# if $1 not set
if test -z "${1-}"; then
    app_name="rpp-latest.app"
else
    app_name="$1.app"
fi

original="REAPER64.app"

# or if  $1 == $RPP_LATEST_DIR exit
if ! test -d $install_path; then

    echo-green "Installing latest version of Reaper to $install_path"

    git clone https://github.com/molleweide/reaper-config.git $install_path

    brew install --cask reaper --appdir=$install_path --force


    $(mv $install_path/$original $install_path/$app_name)

    # tmp_dir=$(mkdtemp $REAPER_DIR)

    # CLONE GIT TO TMP DIR AND MOVE IT TO REAPER
    # mv $tmp_dir/.git $install_path/.git
    # rm -r $tmp_dir # be careful

    # INSTALL REAPER TO TARGET DIR AND RENAME TO LATEST VERSION
    # mkdir -p $install_path

    # NAVIGATE TO (pushd/popd) REAPER INSTALL DIR AND RESTORE GIT
    pushd $install_path > /dev/null 2>&1
    git checkout rpp-latest
    git reset --hard HEAD
    git submodule update --init --recursive
    cd Scripts/reaper-keys && git checkout molleweide && cd ../..
    cd Effects/molleweide && git checkout molleweide && cd ../..
    cd ColorThemes && git checkout molleweide && cd ..
    popd > /dev/null 2>&1
fi
