#!/usr/bin/env bash

name=$1
url=$2

app="$(get-app "$name")"
if test -n "$app"; then
    echo-color "@blue@b[[+ Installing $name]]"

    dmg_path=$(installer_download "$url" "$name.dmg")
    mount_path=$(mount_dmg "$dmg_path")
    app_to_copy="$mount_path/$name.app"

    cp -r "$app_to_copy" /Applications

    unmount_dmg "$mount_path"
    rm -fr $dmg_path
else
    echo-already-installed "$name"
fi
