#!/usr/bin/env bash

echo-header "KEYBOARD"

git_clone_recursive     \
    $HOME/code/firmware \
    "qmk-firmware"      \
    git@github.com:molleweide/qmk_firmware.git

code_tools_path=$HOME/code/tools
git_clone_recursive  \
    $code_tools_path \
    "kmonad"         \
    git@github.com:molleweide/kmonad.git

if is-mac; then
    pushd $code_tools_path/kmonad > /dev/null 2>&1
    # stack clean
    if test "$arch" = 'a64'; then
        stack install --flag kmonad:dext --arch=aarch64 --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
    else
        stack install --flag kmonad:dext --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
    fi
    popd > /dev/null 2>&1
fi
