#!/usr/bin/env bash

echo-header  "Setting up Ruby..."

export PATH="$HOME/.rvm/bin:$PATH"

# install rvm
# TODO: xdg
if [ ! -e ~/.rvm ]; then
    \curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles
    [ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm
fi

# install_global_gem_hooks
# TODO: xdg
gem_hooks_path="$HOME/.rvm/hooks/after_install_add_default_gems"
# symlink_dotfile rvm/hooks/after_install_add_default_gems $gem_hooks_path
chmod +x $gem_hooks_path

rvm install ruby --latest

gem install yard
