#!/usr/bin/env bash

# ignore this title in yabairc !!
TITLE=bin_custom_launcher

SCREEN_WIDTH=`yabai -m query --displays --display | jq .frame.w*2`
SCREEN_HEIGHT=`yabai -m query --displays --display | jq .frame.h*2`

TERM_WIDTH=1280
TERM_HEIGHT=1260

let "X=SCREEN_WIDTH/2-TERM_WIDTH/2"
let "Y=SCREEN_HEIGHT/2-TERM_HEIGHT/2"

exec > "/Users/hjalmarjakobsson/.config/dorothy/commands/launcher-popup.log" 2>&1


# customizing colors is not working for me
alacritty \
  -t "${TITLE}" -o window.position.x="${X}" -o window.position.y="${Y}" \
  -o window.dimensions.lines=35 -o window.dimensions.columns=80 \
  -o window.decorations=none --working-directory "$(pwd)" -e "$1" \
  -o colors.primary.background="#74B573"

