#!/usr/bin/env bash

# USE CASE: You need user input but command is not run in a tty, eg. you run
# a command from a keybind script.

# NOTE: `launcher` is the core command and `launcher-*` are usage commands.

# TODO: Make into -> command `spotlight-launcher-menu`
# Attempt to create a dorothy based macos spotlight alternative.
#
# TODO: Absorb the launcher-filter into a func
#
# TODO: choose/fzf
#
# FIX: Currently, this command is the command responsible for spawning the
# new terminal window, and the script to be ran in that terminal is provided
# in the `-e` flag. -> I wonder if this is a similar issue to the FZF issues,
# where it didnt seem to work to pass the something in a strig to the FZF cmd.

# NOTE: Screen resolution.
# https://superuser.com/questions/196532/how-do-i-find-out-my-screen-resolution-from-a-shell-script
# https://superuser.com/questions/447295/how-can-i-get-the-current-screen-resolution-from-the-command-line-on-os-x
# https://stackoverflow.com/questions/24972338/get-macbook-screen-size-from-terminal-bash
# https://osxdaily.com/2014/08/31/how-to-get-current-screen-resolution-from-command-line-in-mac-os-x/
# https://stackoverflow.com/questions/20099333/terminal-command-to-show-connected-displays-monitors-resolutions
# https://apple.stackexchange.com/questions/162860/how-to-view-current-display-resolution

# MACOS `open` COMMAND
#
# The open command opens a file (or a directory or URL), just as if you had double-clicked the file's icon. If no application name is specified, the default application as determined via LaunchServices is used
# to open the specified files.
#
# If the file is in the form of a URL, the file will be opened as a URL.
#
# You can specify one or more file names (or pathnames), which are interpreted relative to the shell or Terminal window's current working directory. For example, the following command would open all Word files
# in the current working directory:
#
# open *.doc
#
# Opened applications inherit environment variables just as if you had launched the application directly through its full path.  This behavior was also present in Tiger.
#
# The options are as follows:
#
# -a application
#     Specifies the application to use for opening the file
#
# -b bundle_identifier
#     Specifies the bundle identifier for the application to use when opening the file
#
# -e  Causes the file to be opened with the TextEdit application
#
# -t  Causes the file to be opened with the default text editor, as determined via LaunchServices
#
# -f  Reads input from standard input and opens the results in the default text editor.  End input by sending EOF character (type Control-D).  Also useful for piping output to open and having it open in the
#     default text editor.
#
# -F  Opens the application "fresh," that is, without restoring windows. Saved persistent state is lost, except for Untitled documents.
#
# -W  Causes open to wait until the applications it opens (or that were already open) have exited.  Use with the -n flag to allow open to function as an appropriate app for the $EDITOR environment variable.
#
# -R  Reveals the file(s) in the Finder instead of opening them.
#
# -n  Open a new instance of the application(s) even if one is already running.
#
# -g  Do not bring the application to the foreground.
#
# -j  Launches the app hidden.
#
# --arch ARCH
#     Launch with the given cpu architecture type and subtype; ARCH should be one of any, arm, arm64, arm64e, arm64_32, x86_64, x86_64h, i386.  Two integers matching the values for cpu_type_t and cpu_subtype_t
#     can be specified as integers separated by a '/' character, like "12/13" for CPU_TYPE_ARM/CPU_SUBTYPE_ARM_V8.
#
# -h  Searches header locations for a header whose name matches the given string and then opens it.  Pass a full header name (such as NSView.h) for increased performance.
#
# -s  For -h, partial or full SDK name to use; if supplied, only SDKs whose names contain the argument value are searched. Otherwise the highest versioned SDK in each platform is used.
#
# -u  Opens URL with whatever application claims the url scheme, even if URL also matches a file path
#
# --args
#     All remaining arguments are passed to the opened application in the argv parameter to main().  These arguments are not opened or interpreted by the open tool.
#
# --env VAR
#     Adds VAR to the environment of the launched application.  VAR should be formatted NAME=VALUE or NAME.
#
# --stdin PATH
#     Launches the application with stdin connected to PATH.
#
# --stdout PATH
#     Launches the application with stdout connected to PATH.
#
# --stderr PATH
#     Launches the application with stderr connected to PATH.

function launcher_() (
    source "$DOROTHY/sources/bash.bash"

    # exec > "/Users/hjalmarjakobsson/.config/dorothy/commands/launcher.log" 2>&1
    #

    # NOTE: Why do we open alacritty again here?

    local terminal_popup_app="/Applications/Alacritty.app"
    local forward_terminal_args_title="Dorothy launcher default title"

    # local launcher_filter="$DOROTHY/user/commands/launcher-filter"

    local log_file="$DOROTHY/user/commands/launcher.log"

    local stdout_file="$DOROTHY/user/commands/launcher--stdout-file"
    local tty_first=$(tty)
    # local popup_storage

    echo "tty first: $tty_first"

    # TODO: create temp file. Use dorothy temp

    # popup_storage="$(
    #   fs-temp \
    #     --file="${forward_terminal_args_title}_POPUP_CAPTURE"
    # )"

    # # "$forward_terminal_args_title" # only works if last line writes to tmp file?!
    # selection=$(open -n -a "/Applications/Alacritty.app" --args -t "$forward_terminal_args_title" -e "$launcher_filter")
    #
    # NOTE: Here that -e is in this instance the find filter that is passed to
    # fzf
    #
    # NOTE: One can use the wait flag to capture output of the open command.
    # NOTE: It seems that one needs to pass a filter as script to alacritty -e.
    #       Only passing the string does not seem to do anything.
    #
    # LINKS:
    #     https://stackoverflow.com/questions/29510815/how-to-pass-command-line-arguments-to-a-program-run-with-the-open-command

    # =====================================
    # Arguments

    function help {
        cat <<-EOF >/dev/stderr
			ABOUT:
		EOF
        if test "$#" -ne 0; then
            echo-error "$@"
        fi
        return 22 # EINVAL 22 Invalid argument
    }

    # process
    local item
    local option_string=''
    local option_cmd=''
    # local option_xdg="${PREFER_XDG:-"no"}"
    # local option_directories=()
    # local option_files=()
    # local option_prefix=''
    # local option_suffix=''
    # local option_extension=''
    # local option_touch='no'
    while test "$#" -ne 0; do
        item="$1"
        shift
        case "$item" in
        '--help' | '-h') help ;;
        '--string='*) option_string="${item#*=}" ;;
        '--')
            option_cmd="$1"
            shift $#
            break
            ;;
        '--'*) help "An unrecognised flag was provided: $item" ;;
        *) help "An unrecognised argument was provided: $item" ;;
        esac
    done

    if is-mac; then
        local forward_terminal_cmd_args=("bash" "-c")
        if [[ -n $option_string ]]; then
            forward_terminal_cmd_args+=("$option_string")
        elif [[ -n "$option_cmd" ]]; then
            forward_terminal_cmd_args=("bash" "-c")
            forward_terminal_cmd_args+=("$option_cmd")
        else
            # A shell command is required!
            # echo-style error
            return 22
        fi

        if __command_missing -- yabai; then
            # setup-window-manager --use=yabai
            echo "requires yabai"
            exit
        else
            # Get focused monitor display height and width
            local PHYSICAL_SCREEN_WIDTH="$(yabai -m query --displays --display | jq '.frame.w*2')"
            local PHYSICAL_SCREEN_HEIGHT="$(yabai -m query --displays --display | jq '.frame.h*2')"


            __print_lines "phys width: $PHYSICAL_SCREEN_WIDTH"

            local TERM_WIDTH=1280
            local TERM_HEIGHT=1260
            local X=$((PHYSICAL_SCREEN_WIDTH / 2 - TERM_WIDTH / 2))
            local Y=$((PHYSICAL_SCREEN_HEIGHT / 2 - TERM_HEIGHT / 2))
        fi

        local alacritty_default_opts=(
            -o window.position.x="${X}"
            -o window.position.y="${Y}"
            -o window.dimensions.lines=35
            -o window.dimensions.columns=80
            -o window.decorations=none
            -o colors.primary.background="#74B573"
        )

        local open_cmd=("open" -n -W -a "$terminal_popup_app" --stdout "$stdout_file" --args)

        # -e "${forward_terminal_cmd_args[@]}"
        # -e "${bash_c_launch_filter[@]}"
        # -e "$launcher_filter" "$tty_first" "popup_storage"
        # -e "find /Applications -maxdepth 1 -name \"*.app\" | fzf > \"$log_file\""
        # -e "find /Applications -maxdepth 1 -name \"*.app\" | fzf > \"$log_file\"; echo \$? > \"$fifo\"" &
        # -e "echo \"hello world\"" # Should print hellow world in new terminal?
        local popup_terminal_options=(
            -t "$forward_terminal_args_title"
            "${alacritty_default_opts[@]}"
            -e "${forward_terminal_cmd_args[@]}"
        )

        local final_cmd=("${open_cmd[@]}" "${popup_terminal_options[@]}")

        echo "-----"
        __print_lines "${final_cmd[@]}"
        echo "-----"

        "${final_cmd[@]}"

        local status=$?

        # echo "forward_terminal_cmd_args: ${forward_terminal_cmd_args[*]}"

        # capture status of last command
        if [[ status -ne 0 ]]; then
            echo "[launcher]: command [open] failed for some reason.."
        fi

    else
        : # TODO: Linux
    fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    launcher_ "$@"
fi
