#!/usr/bin/env bash

# FIX:
# /Users/hjalmarjakobsson/.local/share/dorothy/user/commands/launcher: line 107: /sources/bash.bash: No such file or directory
# /Users/hjalmarjakobsson/.local/share/dorothy/user/commands/launcher: line 125: /user/commands/launcher.log: No such file or directory
# /Users/hjalmarjakobsson/.local/share/dorothy/commands/is-mac: line 21: /sources/bash.bash: No such file or directory
# /Users/hjalmarjakobsson/.local/share/dorothy/user/commands/launcher: line 220: __command_missing: command not found
# _LSOpenURLsWithCompletionHandler() failed for the application /Applications/Alacritty.app with error -10810.

# WARN: If using --tmux flag with fzf-helper, then focus is not switched to the
# new terminal, instead, the picker is spawned in the currently active tmux session? I think?
# If you remove this flag, then focus is properly switched to the new terminal,
# with the correct picker loaded.
# However, it is not clear what happens. It seems that --tmux moves the focus
# back to the terminal where the existing tmux session resides.
# I am not sure of the sequence of events here and what causes what.

function launcher_() (
	source "$DOROTHY/sources/bash.bash"

	# exec > "/Users/hjalmarjakobsson/.config/dorothy/commands/launcher.log" 2>&1
	#

	# NOTE: Why do we open alacritty again here?

	local terminal_popup_app="/Applications/Alacritty.app"
	local forward_terminal_args_title="Dorothy launcher default title"

	# local launcher_filter="$DOROTHY/user/commands/launcher-filter"

	local log_file="$DOROTHY/user/commands/launcher.log"

	local stdout_file="$DOROTHY/user/commands/launcher--stdout-file"
	local tty_first=$(tty)
	# local popup_storage

	echo "tty first: $tty_first" >"$log_file"

	# TODO: create temp file. Use dorothy temp

	# popup_storage="$(
	#   fs-temp \
	#     --file="${forward_terminal_args_title}_POPUP_CAPTURE"
	# )"

	# # "$forward_terminal_args_title" # only works if last line writes to tmp file?!
	# selection=$(open -n -a "/Applications/Alacritty.app" --args -t "$forward_terminal_args_title" -e "$launcher_filter")
	#
	# NOTE: Here that -e is in this instance the find filter that is passed to
	# fzf
	#
	# NOTE: One can use the wait flag to capture output of the open command.
	# NOTE: It seems that one needs to pass a filter as script to alacritty -e.
	#       Only passing the string does not seem to do anything.
	#
	# LINKS:
	#     https://stackoverflow.com/questions/29510815/how-to-pass-command-line-arguments-to-a-program-run-with-the-open-command

	# =====================================
	# Arguments

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:
		EOF
		if test "$#" -ne 0; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# TODO: Add more flags and actions?
	# What would be other useful operations?

	# process
	local item
	local option_string=''
	local option_cmd=''

	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--string='*) option_string="${item#*=}" ;;
		# Currently, this has to be a single string. But could we instead wrap
		# all args in a string and escape everything necessary?
		'--')
			option_cmd="$1"
			shift $#
			break
			;;
		'--'*) help "An unrecognised flag was provided: $item" ;;
		*) help "An unrecognised argument was provided: $item" ;;
		esac
	done

	if is-mac; then
		local forward_terminal_cmd_args=("bash" "-c")

		if [[ -n $option_string ]]; then
			forward_terminal_cmd_args+=("$option_string")
		elif [[ -n "$option_cmd" ]]; then
			forward_terminal_cmd_args=("bash" "-c")
			forward_terminal_cmd_args+=("$option_cmd")
		else
			# A shell command is required!
			# echo-style error
			return 22
		fi

		local new_term_win_id active_display_id PHYSICAL_SCREEN_DATA

		if __command_missing -- yabai; then
			# setup-window-manager --use=yabai
			echo "requires yabai"
			exit
		fi

		# get active display before we spawn the new window
		active_display_id=$(yabai -m query --displays | jq -r '.[] | select(."has-focus" == true) | .id')
		readarray -t PHYSICAL_SCREEN_DATA < <(yabai -m query --displays --display | jq -r '.frame | [.x*1, .y*1, .w*1, .h*1][]')
		local num_cols=75 num_lines=30
		local TERM_WIDTH=750  # $((num_cols * 10))
		local TERM_HEIGHT=510 # $((num_lines * 17))
		# Note: Im adding the physical display x/y values to shift the window to the correct monitor display.
		local X=$(((PHYSICAL_SCREEN_DATA[2] / 2) - (TERM_WIDTH / 2) + PHYSICAL_SCREEN_DATA[0]))
		local Y=$(((PHYSICAL_SCREEN_DATA[3] / 2) - (TERM_HEIGHT / 2) + PHYSICAL_SCREEN_DATA[1]))

		local alacritty_default_opts=(
			-o window.position.x="${X}"
			-o window.position.y="${Y}"
			-o "window.dimensions.lines=$num_lines"
			-o "window.dimensions.columns=$num_cols"
			-o 'window.startup_mode="Windowed"'
			-o 'window.decorations=none'
			# -o 'colors.primary.background="#009f6b"'
		)

		# -a application
		#     Specifies the application to use for opening the file
		#
		# -n  Open a new instance of the application(s) even if one is already running.
		#
		# -W  Causes open to wait until the applications it opens (or that were already open) have exited.  Use with the -n flag to allow open to function as an appropriate app for the $EDITOR environment variable.
		#
		# --args
		#     All remaining arguments are passed to the opened application in the argv parameter to main().  These arguments are not opened or interpreted by the open tool.
		#
		# --env VAR
		#     Adds VAR to the environment of the launched application.  VAR should be formatted NAME=VALUE or NAME.
		#
		# --stdin PATH
		#     Launches the application with stdin connected to PATH.
		#
		# --stdout PATH
		#     Launches the application with stdout connected to PATH.
		#
		# --stderr PATH
		#     Launches the application with stderr connected to PATH.

		local open_cmd=("open" -n -a "$terminal_popup_app" --stdout "$stdout_file" --args)

		local popup_terminal_options=(
			-T "$forward_terminal_args_title"
			"${alacritty_default_opts[@]}"
			-e "${forward_terminal_cmd_args[@]}"
		)

		local final_cmd=("${open_cmd[@]}" "${popup_terminal_options[@]}")

		# ??? Wrap trap to the popup command, so that focus can be moved back to
		# the previous command???

		# Spawn the new window
		"${final_cmd[@]}"
	else
		: # TODO: Linux
	fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	launcher_ "$@"
fi
