#!/usr/bin/env bash

# find /System/Library/CoreServices /System/Applications /Applications /System/Applications/Utilities -maxdepth 1 -name "*.app" | fzf | xargs -I {} open "{}"
find /System/Library/CoreServices /System/Applications /Applications /System/Applications/Utilities -maxdepth 1 -name "*.app" | fzf | xargs -I {} echo "{}" > "/tmp/$1"
# read -p "enter value: " my_input; echo "$my_input" > "/tmp/$1"
