#!/usr/bin/env bash

# NOTE: Replace macos Cmd-Tab to switch active application.

function launcher_app_switcher_() (
  # local launch_cmd="find /Applications -maxdepth 1 -name \"*.app\" | fzf | xargs -I {} open \"{}\""
  launcher -- find /Applications -maxdepth 1 -name \"*.app\" | fzf | xargs -I {} open "{}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  launcher_app_switcher_ "$@"
fi

