#!/usr/bin/env bash


# TODO: Use choose and fzf UI to manage prefs.
#
# if no args, then run UI.

# TODO: Later, refactor into `plist-helper`, `macos-tcc-db-helper`


# prefctl - Simple macOS preference CLI for plist editing
# Usage:
#   prefctl read domain [keypath]
#   prefctl write domain keypath type value
#   prefctl delete domain keypath

# Example for the below:
#
# Read a nested key:
#       prefctl read com.apple.symbolichotkeys AppleSymbolicHotKeys:64:enabled
#
# Write a new nested key:
#       prefctl write com.apple.finder FXPreferredViewStyle string Nlsv
#
# Delete a nested key:
#       prefctl delete com.apple.finder FXPreferredViewStyle

function macos_settings_helper() (
  source "$DOROTHY/sources/bash.bash"


  # Map all regular relevant settigs files to their respective value in the gui.
  declare -A DOMAIN_PATH_MAP=(

  # [64]="Mission Control"
  # [65]="Application windows"
  # [118]="Move left a space"
  # [119]="Move right a space"
  # [120]="Show Desktop"
  # [160]="Turn Dock Hiding On/Off"
  # [162]="Turn Dock Magnification On/Off"
  # [163]="Minimize Window"
  # [175]="Show Launchpad"
  # [176]="Show Notification Center"
  # ...add the rest from Apple's documentation or dumps
)



)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  macos_settings_helper "$@"
fi



PLISTBUDDY="/usr/libexec/PlistBuddy"

function plist_path() {
    if [[ "$1" == /* ]]; then
        echo "$1"
    else
        echo "$HOME/Library/Preferences/$1.plist"
    fi
}

cmd="$1"
domain="$2"
keypath="$3"

case "$cmd" in
    read)
        if [[ -z "$keypath" ]]; then
            defaults read "$domain"
        else
            $PLISTBUDDY -c "Print :$keypath" "$(plist_path "$domain")"
        fi
        ;;
    write)
        type="$4"
        value="$5"
        $PLISTBUDDY -c "Set :$keypath $value" "$(plist_path "$domain")" 2>/dev/null || \
        $PLISTBUDDY -c "Add :$keypath $type $value" "$(plist_path "$domain")"
        ;;
    delete)
        $PLISTBUDDY -c "Delete :$keypath" "$(plist_path "$domain")"
        ;;
    *)
        echo "Usage:"
        echo "  prefctl read domain [keypath]"
        echo "  prefctl write domain keypath type value"
        echo "  prefctl delete domain keypath"
        echo "Types: string, bool, integer, real, dict, array"
        exit 1
        ;;
esac
