#!/usr/bin/env bash

dirs_dirty=(
    after/
    ftdetect/
    keymap/
    syntax/
    plugin/keymaps.vim
    lua/examples/
    lua/snippets/
    lua/testing/
)

dir_dest=$XDG_CONFIG_HOME/doom-nvim/migrate=
mkdir -p $dir_dest


# for i in $dirs_dirty[@]; do
# # add recursive dirs flag
#     cp $i # into $dir_dest/$i
# done

copy_dirty_files_to_migr() {

}

# config_files_list=(

#     )

# $1 = from_branch
checkout_config_files_from_main() {
# for i in $dirs_dirty[@]; do
#     cp $i # into $dir_dest/$i
    # git checkout $1 -- $i
# done
}

case "$1" in
    "cpmig") copy_dirty_files_to_migr;;
     "gcocfg") checkout_config_files_from_main;
    # *) apply_grid "cf";;
esac

$_f ${@:2}
