#!/usr/bin/env bash

#
# NVIM HELPER
#

# TODO: ( ) handle startup mode / doom modes.
# 1. doom.is_mode
# 2. doom.mode == ...

# TODO: doom modes
# - reduced   -> for editing a few files in basic mode, eg from ranger or dorothy edit.
# - firenvim  -> modules to be loaded with firenvim.
# - full      -> all enabled modules except for beta
# - full_beta -> including beta modules / testing modules

nvim_helper() (
	source "$DOROTHY/sources/bash.bash"

	# execute_neovim

	# NOTE:
	# play around with ways for opening nvim in various ways, so that i start
	# to use nvim more as a versatile tool rather than just an IDE.
	#
	# execute nvim with a special mode

	# TEST:
	# -   Reads text from standard input until EOF, then opens a buffer with that
	#     text.  User input is read from standard

	# ( ) pass which version / installation that should be used.
	# ( ) pass version to use
	#
	# ( ) picker grep files and pass selection into quickfix list and launch in
	# basic mode.

	picker__grep_qf() {
		:
	}

	#
	# -q [errorfile]
	#            QuickFix mode.  Display the first error in errorfile.  If errorfile is omitted, the value of the 'errorfile'
	#            option is used (defaults to errors.err).  Further errors can be jumped to with the :cnext command.  :help quickfix
	#
	#            >> use this to find the error file automatically.

	# NOTE: But most of this stuff could just be put in command aliases...
	#
	# ( ) pe specify window layout etc when upon starting, maybe for special files?
	#
	# open with a terminal?? this could be a mode and then i set the logic in the
	# module itself, so it can perform certain startup action based on which mode
	# is started with.
	# --mode="advanced" -> open terminal on startup

	# ( ) fuzzy grep sessions before starting?

	# ( ) run with clean env env -i

	# ( ) -P altpath || or run on mult dirs select with fuzzy find grep.

	# NOTE: mode implementation -> run nvim with env -i and pass DOOM_STARTUP_MODE={mode}

	# try use -S for setting the env.

	# start listening to a special location or something?

	# startup time and dump info into dorothy user file.

	# ( ) grep file open at found word linenumber just like how telescope grep
	# works

	# a lot of this command will be to create pickers for how to open nvim.
	#
	# subsequent picker that takes startup pattern?

	# picker open selected files horz/vert stacked.

	picker__horz_stacked() {
		:
	}

	picker__vert_stacked() {
		:
	}

	# --[no]-swap

	# --open-stdin-eof

	# --error-file=
	# --tag=

	# --vimrc=

	# TODO: ( ) if doom.mode_is(<mode>|{<modes>}) then do...
	# > this requires only attaching a function to doom table.
	# ( ) if doom.mode == <mode>|{<modes>} then ... end
	# > this would require a meta table.
	#
	# TODO: ( ) Make tests to ensure that the core works properly??

	# nvim: Make tests to ensure that the core works properly??

	# =======================================================
	# Args

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:

			Run [nvim] command with flags or custom environment.

			USAGE:
			nvim-helper [...<options>]

			ACTIONS/PICKERS:
			$(declare -F | awk '{print "    " $3}' | grep 'picker__' | sed 's/picker__//')

			OPTIONS:

			--stdin
			          Pass data and options to a picker with Dorothy's own API wrapper.

			--section=<string>
			    String can be a comma separated list of module sections. Exclude
			    sections by prefixing with [!].

			--tags=<string>
			    String should be a comma separated list of tags. Load only modules
			    with specific tags, OR, exclude them by prefixing with [!].


		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	local item option_dry_run='no' option_env=() option_nvim_flags=()

	local option_sections='' option_tags=''

	while [[ $# -ne 0 ]]; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--dry' | '-d') option_dry_run='yes' ;;
		'--mode'=*) option_env+=("DOOM_STARTUP_MODE=${item#*=}") ;;

		'--sections='*) option_sections="${item#*=}" ;;
		'--tags='*) option_tags="${item#*=}" ;;
		'--exclude-sections='*) option_sections="!${item#*=}" ;;
		'--exclude-tags='*) option_tags="!${item#*=}" ;;

		# '--no-skip-solo'* | '--skip-solo'*)
		# 	option_confirm_solo="$(get-flag-value --non-affirmative --fallback="$option_confirm_solo" -- "$item")"
		# 	;;

		'--reset')
			# run neovim with env -i
			;;
		*)
			option_nvim_flags+=("$item")
			;;
		esac
	done

	# CC=gcc-12
	local nvim_bin=~/.local/share/bob/nvim-bin/nvim

	if [[ -n "$option_sections" ]]; then
		option_env+=("DOOM_LOAD_SECTIONS=$option_sections")
	fi

	if [[ -n "$option_tags" ]]; then
		option_env+=("DOOM_LOAD_TAGS=$option_tags")
	fi

	local final_command=(env "${option_env[@]}" "$nvim_bin" "${option_nvim_flags[@]}")

	echo-join '.' -- "${final_command[*]}"

	# printf '%s ' "${final_command[@]}"

	# env "$"

	if [[ "$option_dry_run" == 'no' ]]; then
		exec "${final_command[@]}"
	fi

)

# fire if invoked standalone
if [[ $0 == "${BASH_SOURCE[0]}" ]]; then
	nvim_helper "$@"
fi
