#!/usr/bin/env bash

# create new main branch
# enter main_new
# `nvim-checkout-configs gco molldev_m1`

# shouldn't contain core files
files_nvim_doom_configs_personal=(

    notes/

    after/
    ftdetect/
    keymap/
    syntax/
    plugin/keymaps.vim

    lua/examples/
    lua/snippets/
    lua/testing/

)

doom_configs=(

    doom_config.lua
    doom_modules.lua
    doom_userplugins.lua
)

dir_migr="$XDG_CONFIG_HOME/doom-nvim/migrate"


# for i in $dirs_dirty[@]; do
# # add recursive dirs flag
#     cp $i # into $dir_dest/$i
# done

collect_config_files_in_migr() {
    echo "collect"
    # mkdir -p $dir_migr

}

# config_files_list=(

#     )

# $1 = from_branch
checkout_files_from_migr_dir() {
    for i in ${files_nvim_doom_configs_personal[@]}; do
        git checkout $1 -- $i
    done
}

everything_else() {
    for i in ${doom_configs[@]}; do
        git checkout $1 -- $i
    done
}

case "$1" in
    "cpmig") _f=collect_config_files_in_migr;;
    "gco")  _f=checkout_files_from_migr_dir;;
    "ee") _f=everything_else;;
    # *) apply_grid "cf";;
esac

$_f ${@:2}
