#!/usr/bin/env bash
# shellcheck disable=SC2054

function pickers_git() (
	source "$DOROTHY/sources/bash.bash"

	# ===========================================================================
	# HELPERS
	#

	is_git_repo() {
		git rev-parse HEAD >/dev/null 2>&1 && return
		[[ -n ${TMUX-} ]] && tmux display-message "Not in a git repository"
		return 1
	}

	get_fzf_cat_command() {
		if [[ -n ${FZF_GIT_CAT-} ]]; then
			echo "$FZF_GIT_CAT"
			return
		fi

		local bat_opts=(
			--style="'${BAT_STYLE:-full}'"
			--color="$(fzf-get-git-color .)"
			--pager="never"
		)

		# Sometimes bat is installed as batcat
		if command -v batcat >/dev/null; then
			echo "batcat ${bat_opts[*]}"
		elif command -v bat >/dev/null; then
			echo "bat ${bat_opts[*]}"
		else
			echo cat
		fi
	}

	get_git_pager() {
		local pager
		pager="${FZF_GIT_PAGER:-${GIT_PAGER:-$(git config --get core.pager 2>/dev/null)}}"
		echo "${pager:-cat}"
	}

	# ===========================================================================
	# PICKERS
	#
	# This is where all pre-defined pickers are listed.
	#

	# TODO: Refactor options into their own arrays, so that you can eg. reuse the
	# >>> Also, allow for dynamically providing which key should be used, eg. `o`
	# for opening in browser.
	#
	# TODO: ( ) helpers for adding fzf options to the make_picker_cmd array
	# 1. First of all, put all options into an array.
	#     >> "${arr[@]}"

	# (x) Previously the file that opens in browser was sourced with:
	# `--bind "ctrl-o:execute-silent:bash $SOURCES__FZF_HACK_OPEN_IN_BROWSER branch {}"`
	# But now I have moved that code into a standalone command.

	# Note:
	# Chain actions with +, eg `ctrl-o:action(...)+abort` will close fzf after action is performed

	picker__branches() {
		is_git_repo || return
		local str_preview_cmd
		# move this to git helper?
		str_preview_cmd="git log --oneline --graph --date=short --color=$(fzf-get-git-color .) \
            --pretty='format:%C(auto)%cd %h%d %s' \$(sed s/^..// <<< {} | cut -d' ' -f1) --"
		local opts=(
			--ansi
			--border-label '🌲 Branches'
			--header-lines 2
			--tiebreak begin
			--preview-window down,border-top,40%
			--color hl:underline,hl+:underline
			--no-hscroll
			--bind 'ctrl-/:change-preview-window(down,70%|hidden|)'
			--bind "ctrl-o:execute-silent(browser branch {})"
			--bind 'ctrl-e:change-border-label(🌳 All branches)+reload:fzf-get-git-data all-branches'
			--preview "$str_preview_cmd"
		)
		fzf-get-git-data branches | make_picker_cmd -- "${opts[@]}" "$@" | sed 's/^..//' | cut -d' ' -f1
	}

	picker__branches_all() {
	  :
	}

	picker__files() {
		is_git_repo || return
		local root query=''
		root=$(git rev-parse --show-toplevel)
		[[ $root != "$PWD" ]] && query='!../ '

		# TODO: This collecting of all the files should go into [get-git-data files]
		(
			git -c color.status=$(fzf-get-git-color) status --short --no-branch
			git ls-files "$root" | grep -vxFf <(
				git status -s | grep '^[^?]' | cut -c4-
				echo :
			) | sed 's/^/   /'
		) |
			make_picker_cmd -- -m --ansi --nth 2..,.. \
				--border-label '📁 Files' \
				--header $'CTRL-O (open in browser) ╱ ALT-E (open in editor)\n\n' \
				--bind "ctrl-o:execute-silent(browser file {-1})" \
				--bind "alt-e:execute:${EDITOR:-vim} {-1} > /dev/tty" \
				--query "$query" \
				--preview "git diff --no-ext-diff --color=$(fzf-get-git-color .) -- {-1} | $(get_git_pager); $(get_fzf_cat_command) {-1}" "$@" |
			cut -c4- | sed 's/.* -> //'
	}

	picker__tags() {
		is_git_repo || return
		git tag --sort -version:refname |
			make_picker_cmd -- --preview-window right,70% \
				--border-label '📛 Tags' \
				--header $'CTRL-O (open in browser)\n\n' \
				--bind "ctrl-o:execute-silent(browser tag {})" \
				--preview "git show --color=$(fzf-get-git-color .) {} | $(get_git_pager)" "$@"
	}

	picker__hashes() {
		is_git_repo || return
		fzf-get-git-data hashes |
			make_picker_cmd -- --ansi --no-sort --bind 'ctrl-s:toggle-sort' \
				--border-label '🍡 Hashes' \
				--header-lines 3 \
				--color hl:underline,hl+:underline \
				--bind "ctrl-o:execute-silent(browser commit {})" \
				--bind "ctrl-d:execute:grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git diff --color=$(fzf-get-git-color) > /dev/tty" \
				--bind "alt-a:change-border-label(🍇 All hashes)+reload:fzf-get-git-data all-hashes" \
				--preview "grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git show --color=$(fzf-get-git-color .) | $(get_git_pager)" "$@" |
			awk 'match($0, /[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*/) { print substr($0, RSTART, RLENGTH) }'
	}

	picker__remotes() {
		is_git_repo || return
		git remote -v | awk '{print $1 "\t" $2}' | uniq |
			make_picker_cmd -- --tac \
				--border-label '📡 Remotes' \
				--header $'CTRL-O (open in browser)\n\n' \
				--bind "ctrl-o:execute-silent(browser remote {1})" \
				--preview-window right,70% \
				--preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' '{1}/$(git rev-parse --abbrev-ref HEAD)' --" "$@" |
			cut -d$'\t' -f1
	}

	picker__stashes() {
		is_git_repo || return
		git stash list | make_picker_cmd -- \
			--border-label '🥡 Stashes' \
			--header $'CTRL-X (drop stash)\n\n' \
			--bind 'ctrl-x:reload(git stash drop -q {1}; git stash list)' \
			-d: --preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)" "$@" |
			cut -d: -f1
	}


	# ref logs (it starts with `l` so that we can use `l` as the keybind.
	picker__reflogs() {
		is_git_repo || return
		git reflog --color=$(fzf-get-git-color) --format="%C(blue)%gD %C(yellow)%h%C(auto)%d %gs" | make_picker_cmd -- --ansi \
			--border-label '📒 Reflogs' \
			--preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)" "$@" |
			awk '{print $1}'
	}

	picker__each_ref() {
		is_git_repo || return
		fzf-get-git-data refs | make_picker_cmd -- --ansi \
			--nth 2,2.. \
			--tiebreak begin \
			--border-label '☘️  Each ref' \
			--header-lines 2 \
			--preview-window down,border-top,40% \
			--color hl:underline,hl+:underline \
			--no-hscroll \
			--bind 'ctrl-/:change-preview-window(down,70%|hidden|)' \
			--bind "ctrl-o:execute-silent(browser {1} {2})" \
			--bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) > /dev/tty" \
			--bind "alt-a:change-border-label(🍀 Every ref)+reload:fzf-get-git-data all-refs" \
			--preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --" "$@" |
			awk '{print $2}'
	}

	picker__worktrees() {
		is_git_repo || return
		git worktree list | make_picker_cmd -- \
			--border-label '🌴 Worktrees' \
			--header $'CTRL-X (remove worktree)\n\n' \
			--bind 'ctrl-x:reload(git worktree remove {1} > /dev/null; git worktree list)' \
			--preview "
      git -c color.status=$(fzf-get-git-color .) -C {1} status --short --branch
      echo
      git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --
    " "$@" |
			awk '{print $1}'
	}

	# This picker collects all existing pickers and allows you to choose which one
	# to run.
	# TODO: echo-comment-blocks to capture the description of each picker.
	# TODO: Use TRANSFORM ACTIONS to load the new picker.
	# 1. All pickers above need to take args so that one can choose to only get their options.
	# 2. Then, use a function that returns a chain of action statements to update the picker.
	picker__master() {
		local all_existing_pickers selection
		all_existing_pickers="$(declare -F | awk '{print $3}' | grep '^picker__' | grep -v '^picker__master$')"
		selection="$(
			__print_lines "${all_existing_pickers[@]}" | make_picker_cmd -- \
				--border-label '🌴 [Dorothy]: All pickers' \
				--header $'Select which picker to run\n\n'
		)"
		"$selection"
	}

	# =====================================
	# Help

	function help {
		cat <<-EOF >/dev/stderr
			ABOUT:

			Only the last supplied action will be ran.

			Defaults to running a master picker that lists all existing pickers

			USAGE:
			aliases [...<options] [<action>] [-- [...<picker_options>]]

			ACTIONS/PICKERS:
			$(declare -F | awk '{print "    " $3}' | grep 'picker__' | sed 's/picker__//')

			OPTIONS:

			--stdin
		      Pass data and options to a picker with Dorothy's own API wrapper.


		EOF
		if [[ $# -ne 0 ]]; then
			echo-error "$@"
		fi
		return 22 # EINVAL 22 Invalid argument
	}

	# ===========================================================================
	# Arguments
	#

	local item action='' pipe_inputs=()
	while test "$#" -ne 0; do
		item="$1"
		shift
		case "$item" in
		'--help' | '-h') help ;;
		'--pipe')
			# Using stdin -> but i use the --pipe namespace because i dont want to
			# overwrite --stdin since i dont know how it works with stdinargs.
			source "$DOROTHY/sources/stdinargs.bash"
			function on_input {
				pipe_inputs+=("$1")
			}
			# echo "inside --pipe"
			stdinargs "$@"
			shift $#
			break
			;;
		'--')
			# TODO: instead of selecting action here, I should pass additional
			# args to the picker itself.
			if [[ "$#" -gt 0 ]]; then
				action=$1
			else
				help "Supplying [--] expects a picker name after it"
			fi
			shift $#
			break
			;;
		*)
			# If you supply multiple non flags then the last one will be the action.
			action="$item"
			# help "An unrecognised argument was provided: $item"
			;;
		esac
	done

	# ===========================================================================
	# Act / Run pickers
	#

	# Check
	if [[ -z "$action" ]]; then
		if test "${#pipe_inputs[@]}" -gt 0; then
			action="default" # stdin
		else
			picker__master
		fi
	fi

	# TODO: Run default picker if only --stdin is used.

	__debug_lines "Action = $action"

	# Run picker
	if test "$(type -t "picker__$action")" = 'function'; then
		"picker__$action"
		return
	else
		echo-style --error="Action [$action] not yet implemented." >/dev/stderr
		return 78 # ENOSYS 78 Function not implemented
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	pickers_git "$@"
fi

