#!/usr/bin/env bash
# shellcheck disable=SC2054

function pickers_dorothy() (
  source "$DOROTHY/sources/bash.bash"
  source "$DOROTHY/user/sources/pickers.bash"

  # TODO: ( ) command aliases (DCA's)
  # TODO: ( ) regular aliases (DRA's)
  #
  # TODO: ( ) commands all
  # TODO: ( ) commands user
  # TODO: ( ) commands core
  #
  # TODO: ( ) sources user
  # TODO: ( ) sources core
  #
  # TODO: ( ) docs
  #
  # TODO: ( ) configs user
  # TODO: ( ) configs core

  # pipe debug --x into fzf and allow for fuzzy filtering by various
  # predicates so that you can quickly narrow down and filter out
  # irrelevant lines.
  # eg. only show lines pertainig to function [_ask], or range between line numbers..

  pickers_args "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  pickers_dorothy "$@"
fi
