#!/usr/bin/env bash
# shellcheck disable=SC2054

function pickers_dorothy() (
	source "$DOROTHY/sources/bash.bash"
  source "$DOROTHY/user/sources/pickers.bash"

	pickers_args "$@"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	pickers_dorothy "$@"
fi


