#!/usr/bin/env bash
# shellcheck disable=SC2054

function pickers_various() (
  source "$DOROTHY/sources/bash.bash"

  # Collect all pickers, from all [pickers-*] commands and display.
  picker__master() {
    # todo: echo-comment-blocks to capture the description of each picker.
    # todo: Use TRANSFORM ACTIONS to load the new picker.
    # 1. All pickers above need to take args so that one can choose to only get their options.
    # 2. Then, use a function that returns a chain of action statements to update the picker.

    local all_existing_pickers selection pickers_files=() picker_cmds=()

    mapfile -t pickers_files < <(find "$DOROTHY/commands" "$DOROTHY/user/commands" -type f -name "pickers-*")

    for file in "${pickers_files[@]}"; do
      local function_names=()

      # TODO: move this to the get-func-definitions file
      mapfile -t function_names < <(
        cat "$file" | gawk 'match($0, / *picker__(.*)\(\)/, a) {print a[1]}' |
          grep -v '^master'
      )

      # TODO: use printf '%n.ns' to format nicely
      for fn_name in "${function_names[@]}"; do
        picker_cmds+=("$(basename "$file") $fn_name")
      done
    done

    selection="$(
      __print_lines "${picker_cmds[@]}" |
        fzf-helper \
          --border-label '🌴 [Dorothy]: All pickers' \
          --header $'Select which picker to run\n\n' \
          -- --stdin
    )"

    local split_selection
    read -r -a split_selection <<<"$selection"

    # __print_lines "selection: $selection"

    "${split_selection[@]}"
  }

  picker__kmonad_layers() {
    :
  }

  # =====================================
  # Help

  function help {
    cat <<-EOF >/dev/stderr
			ABOUT:
			Various pickers

			PICKERS:
			$(declare -F | awk '{print "    " $3}' | grep 'picker__' | sed 's/picker__//')
		EOF
    if [[ $# -ne 0 ]]; then
      echo-error "$@"
    fi
    return 22 # EINVAL 22 Invalid argument
  }

  # ===========================================================================
  # Arguments
  #

  local item action='' options_flags=()
  while test "$#" -ne 0; do
    item="$1"
    shift
    case "$item" in
    '--help' | '-h') help ;;
    '--'*) options_flags+=("${item#*=}") ;;
    *)
      action="$item"
      ;;
    esac
  done

  if [[ -z "$action" ]]; then
    help "No action was provided."
  fi

  if test "$(type -t "picker__$action")" = 'function'; then
    "picker__$action" "${options_flags[@]}"
  else
    echo-style --error="Action [$action] does not exist." >/dev/stderr
    return 78 # ENOSYS 78 Function not implemented
  fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  pickers_various "$@"
fi
