#!/usr/bin/env bash
# shellcheck disable=SC2054

# ( ) picker: search through FULL commit messages. w/ripgrep integration.

# TODO: move git helpers back into this command.

function pickers_git() (
  source "$DOROTHY/sources/bash.bash"

  # ===========================================================================
  # HELPERS
  #

  is_git_repo() {
    git rev-parse HEAD >/dev/null 2>&1 && return
    [[ -n ${TMUX-} ]] && tmux display-message "Not in a git repository"
    return 1
  }

  get_fzf_cat_command() {
    if [[ -n ${FZF_GIT_CAT-} ]]; then
      echo "$FZF_GIT_CAT"
      return
    fi

    local bat_opts=(
      --style="'${BAT_STYLE:-full}'"
      --color="$(fzf-get-git-color .)"
      --pager="never"
    )

    # Sometimes bat is installed as batcat
    if command -v batcat >/dev/null; then
      echo "batcat ${bat_opts[*]}"
    elif command -v bat >/dev/null; then
      echo "bat ${bat_opts[*]}"
    else
      echo cat
    fi
  }

  get_git_pager() {
    local pager
    pager="${FZF_GIT_PAGER:-${GIT_PAGER:-$(git config --get core.pager 2>/dev/null)}}"
    echo "${pager:-cat}"
  }

  # ===========================================================================
  # PICKERS
  #

  picker__branches() {
    is_git_repo || return
    local str_preview_cmd
    # move this to git helper?
    str_preview_cmd="git log --oneline --graph --date=short --color=$(fzf-get-git-color .) \
            --pretty='format:%C(auto)%cd %h%d %s' \$(sed s/^..// <<< {} | cut -d' ' -f1) --"
    local opts=(
      --ansi
      --border-label '🌲 Branches'
      --header-lines 2
      --tiebreak begin
      --preview-window down,border-top,40%
      --color hl:underline,hl+:underline
      --no-hscroll
      --bind 'ctrl-/:change-preview-window(down,70%|hidden|)'
      --bind "ctrl-o:execute-silent(browser branch {})"
      --bind 'ctrl-e:change-border-label(🌳 All branches)+reload:fzf-get-git-data all-branches'
      --preview "$str_preview_cmd"
    )
    # fzf-get-git-data branches | make_picker_cmd -- "${opts[@]}" "$@" | sed 's/^..//' | cut -d' ' -f1
    fzf-get-git-data branches | fzf-helper "${opts[@]}" "$@" -- --stdin | sed 's/^..//' | cut -d' ' -f1
  }

  picker__branches_all() {
    :
  }

  picker__files() {
    is_git_repo || return
    local root query=''
    root=$(git rev-parse --show-toplevel)
    [[ $root != "$PWD" ]] && query='!../ '

    local opts=(
      -m --ansi --nth 2..,..
      --border-label '📁 Files'
      --header $'CTRL-O (open in browser) ╱ ALT-E (open in editor)\n\n'
      --bind "ctrl-o:execute-silent(browser file {-1})"
      --bind "alt-e:execute:${EDITOR:-vim} {-1} > /dev/tty"
      --query "$query"
      --preview "git diff --no-ext-diff --color=$(fzf-get-git-color .) -- {-1} | $(get_git_pager); $(get_fzf_cat_command) {-1}"
    )

    # TODO: This collecting of all the files should go into [get-git-data files]
    (
      git -c color.status=$(fzf-get-git-color) status --short --no-branch
      git ls-files "$root" | grep -vxFf <(
        git status -s | grep '^[^?]' | cut -c4-
        echo :
      ) | sed 's/^/   /'
    ) | fzf-helper "${opts[@]}" "$@" -- --stdin | cut -c4- | sed 's/.* -> //'
  }

  picker__tags() {
    is_git_repo || return
    local opts=(
      --preview-window right,70%
      --border-label '📛 Tags'
      --header $'CTRL-O (open in browser)\n\n'
      --bind "ctrl-o:execute-silent(browser tag {})"
      --preview "git show --color=$(fzf-get-git-color .) {} | $(get_git_pager)"
    )
    git tag --sort -version:refname | fzf-helper "${opts[@]}" "$@" -- --stdin
  }

  picker__hashes() {
    is_git_repo || return
    local opts=(

      --ansi --no-sort --bind 'ctrl-s:toggle-sort'
      --border-label '🍡 Hashes'
      --header-lines 3
      --color hl:underline,hl+:underline
      --bind "ctrl-o:execute-silent(browser commit {})"
      --bind "ctrl-d:execute:grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git diff --color=$(fzf-get-git-color) > /dev/tty"
      --bind "alt-a:change-border-label(🍇 All hashes)+reload:fzf-get-git-data all-hashes"
      --preview "grep -o '[a-f0-9]\{7,\}' <<< {} | head -n 1 | xargs git show --color=$(fzf-get-git-color .) | $(get_git_pager)"
    )
    fzf-get-git-data hashes | fzf-helper "${opts[@]}" "$@" -- --stdin |
      awk 'match($0, /[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]*/) { print substr($0, RSTART, RLENGTH) }'
  }

  picker__remotes() {
    is_git_repo || return
    local opts=(
      --tac
      --border-label '📡 Remotes'
      --header $'CTRL-O (open in browser)\n\n'
      --bind "ctrl-o:execute-silent(browser remote {1})"
      --preview-window right,70%
      --preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' '{1}/$(git rev-parse --abbrev-ref HEAD)' --"

    )
    git remote -v | awk '{print $1 "\t" $2}' | uniq | fzf-helper "${opts[@]}" "$@" -- --stdin |
      cut -d$'\t' -f1
  }

  picker__stashes() {
    is_git_repo || return
    local opts=(

      --border-label '🥡 Stashes'
      --header $'CTRL-X (drop stash)\n\n'
      --bind 'ctrl-x:reload(git stash drop -q {1}; git stash list)'
      -d: --preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)"
    )
    git stash list | fzf-helper "${opts[@]}" "$@" -- --stdin | cut -d: -f1
  }

  # ref logs (it starts with `l` so that we can use `l` as the keybind.
  picker__reflogs() {
    is_git_repo || return
    local opts=(
      --ansi
      --border-label '📒 Reflogs'
      --preview "git show --color=$(fzf-get-git-color .) {1} | $(get_git_pager)"
    )
    git reflog --color="$(fzf-get-git-color)" --format="%C(blue)%gD %C(yellow)%h%C(auto)%d %gs" |
      fzf-helper "${opts[@]}" "$@" -- --stdin |
      awk '{print $1}'
  }

  picker__each_ref() {
    is_git_repo || return
    local opts=(
      --ansi
      --nth 2,2..
      --tiebreak begin
      --border-label '☘️  Each ref'
      --header-lines 2
      --preview-window down,border-top,40%
      --color hl:underline,hl+:underline
      --no-hscroll
      --bind 'ctrl-/:change-preview-window(down,70%|hidden|)'
      --bind "ctrl-o:execute-silent(browser {1} {2})"
      --bind "alt-e:execute:${EDITOR:-vim} <(git show {2}) > /dev/tty"
      --bind "alt-a:change-border-label(🍀 Every ref)+reload:fzf-get-git-data all-refs"
      --preview "git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --"
    )
    fzf-get-git-data refs | fzf-helper "${opts[@]}" "$@" -- --stdin | awk '{print $2}'
  }

  picker__worktrees() {
    is_git_repo || return
    local opts=(
      --border-label '🌴 Worktrees'
      --header $'CTRL-X (remove worktree)\n\n'
      --bind 'ctrl-x:reload(git worktree remove {1} > /dev/null; git worktree list)'
      --preview "
      git -c color.status=$(fzf-get-git-color .) -C {1} status --short --branch
      echo
      git log --oneline --graph --date=short --color=$(fzf-get-git-color .) --pretty='format:%C(auto)%cd %h%d %s' {2} --
    "
    )
    git worktree list | fzf-helper "${opts[@]}" "$@" -- --stdin | awk '{print $1}'
  }

  # =====================================
  # Help

  function help {
    cat <<-EOF >/dev/stderr
			...load pickers help file.

					ABOUT:

					      1. Run git pickers.
					      2. <action> is the picker name
					      3. Options will be passed down to [fzf-helper]

					USAGE:

					pickers-* [...<options>] <action>

					ACTIONS/PICKERS:
					$(declare -F | awk '{print "    " $3}' | grep 'picker__' | sed 's/picker__//')

					OPTIONS:
					    Options will be forwarded to [fzf]

		EOF
    if [[ $# -ne 0 ]]; then
      echo-error "$@"
    fi
    return 22 # EINVAL 22 Invalid argument
  }

  # ===========================================================================
  # Arguments

  # TODO: this will be the same for all pickers-* commands?
  # Move to its own command?

  local item action='' options_flags=()
  while test "$#" -ne 0; do
    item="$1"
    shift
    case "$item" in
    '--help' | '-h') help ;;
    '--'*) options_flags+=("${item#*=}") ;;
    *)
      action="$item"
      ;;
    esac
  done

  if [[ -z "$action" ]]; then
    help "No action was provided."
  fi

  if test "$(type -t "picker__$action")" = 'function'; then
    "picker__$action" "${options_flags[@]}"
  else
    echo-style --error="Action [$action] does not exist." >/dev/stderr
    return 78 # ENOSYS 78 Function not implemented
  fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  pickers_git "$@"
fi
