#!/usr/bin/env bash

# TODO: validate $1 path

echo-green "Installing latest version of Reaper to $RPP_LATEST_DIR"

mkdir -p $REAPER_DIR/app
mkdir -p $REAPER_DIR/projects
mkdir -p $REAPER_DIR/tmp
mkdir -p $REAPER_DIR/backup

# original="REAPER64.app"
# tmp_dir=$(mkdtemp $REAPER_DIR)

# # INSTALL REAPER TO TARGET DIR AND RENAME TO LATEST VERSION
# mkdir -p $RPP_LATEST_DIR
# brew install --cask reaper --appdir=$RPP_LATEST_DIR --force
# $(mv $RPP_LATEST_DIR/$original "$RPP_LATEST_DIR/rpp-latest.app")

# # CLONE GIT TO TMP DIR AND MOVE IT TO REAPER
# git clone https://github.com/molleweide/reaper-app-config.git $tmp_dir
# mv $tmp_dir/.git $RPP_LATEST_DIR/.git
# rm -r $tmp_dir # be careful

# # NAVIGATE TO (pushd/popd) REAPER INSTALL DIR AND RESTORE GIT
# pushd $RPP_LATEST_DIR > /dev/null 2>&1

# git checkout rpp-latest
# git reset --hard HEAD

# git submodule update --init --recursive

# # submodule branches
# cd Scripts/reaper-keys && git checkout molleweide && cd ../..
# cd Effects/molleweide && git checkout molleweide && cd ../..
# cd ColorThemes && git checkout molleweide && cd ..

# popd > /dev/null 2>&1


