#!/usr/bin/env bash

echo-header "SETUP REAPER"

# https://forum.cockos.com/showthread.php?p=2487247#post2487247
# https://forum.cockos.com/showthread.php?t=242922&highlight=reaper+update+utility
# https://github.com/iliaspoulakis/Reaper-Tools/blob/master/Various/REAPER%20Update%20Utility.lua

# - get reaper 6 23 to work
# - install latest reaper and create rpp_latest
# - cli > write log file to $RPP_LATEST_DIR/rpp.log
# - look at reaper update utility.
#   can this one be used / compatible with branches

export REAPER_DIR=~/reaper
export RPP_LATEST_DIR=$REAPER_DIR/app/rpp-latest
# export REAPER_CLI=$RPP_LATEST_DIR/reaper-latest
export PATH="$PATH:$RPP_LATEST_DIR"

if reaper-latest-exists; then

    echo-bold "Reaper already exists"
    # if reaper-has-new-version; then

    #     echo-red "Your version of Reaper is outdated." && exit 1

    #     read -r -p "Do you want to update Reaper to the latest version? [y|N] " response

    #     [[ $response =~ (y|yes|Y) ]] || exit 1

    #     reaper-mv-outdated
    #     reaper-install-latest

    # else
    #     reaper-pull
    # fi

else

    read -r -p "Do you want to install Reaper to $RPP_LATEST_DIR? [y|N] " response
    [[ $response =~ (y|yes|Y) ]] || exit 1

    # reaper-install-latest
fi
