#!/usr/bin/env bash

# FIX: EXTERNAL DISPLAYS ARE NOT INCLUDED

screenshot_dir="$HOME/Documents/Screenshots"

mkdir -p $screenshot_dir

if is-mac; then
    screencapture -x "$HOME/Documents/Screenshots/$(date "+DATE-%Y-%m-%d-TIME-%H-%M-%S").jpg"
else
    echo "linux todo.."
fi
