#!/usr/bin/env bash

# NOTE: 1. qutebrowser now works on both linux and macos!!!!
# 2. I have my own dark mode config for qute.
# 3. Needs to be symlinked to $HOME on macos...

function setup_util_qutebrowser() (
    source "$DOROTHY/sources/bash.bash"

    # setup
    local options=(
        --name='Qute Browser'
        --cli=qutebrowser
        "$@"
        BREW='qutebrowser'
    )
    setup-util "${options[@]}"

    local config_destination

    if is-mac; then
        config_destination="$HOME/.qutebrowser"
    else
        config_destination="$XDG_CONFIG_HOME/qutebrowser"
    fi

    util-config-helper qutebrowser "$config_destination"

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_util_qutebrowser "$@"
fi
