#!/usr/bin/env bash

echo-header "SETTING UP GIT..."

if [ ! -f "${XDG_CONFIG_HOME:-$HOME/.config}/git/config.user" ]; then

    printf "What is your GitHub username? > "
    read github_user
    git config -f "${XDG_CONFIG_HOME:-$HOME/.config}/git/config.user" github.user "$github_user"


    printf "What is your full name for commit messages (e.g. Jane Smith)? > "
    read git_name
    git config -f "${XDG_CONFIG_HOME:-$HOME/.config}/git/config.user" user.name "$git_name"


    printf "What is your git email? (e.g. blah@blah.com) > "
    read git_email
    git config -f "${XDG_CONFIG_HOME:-$HOME/.config}/git/config.user" user.email "$git_email"

fi
