#!/usr/bin/env bash

echo-header "SETTING UP TERMINAL.."

if is-mac; then
    brew install --cask alacritty
    brew install --cask kitty
    if command-exists "alacritty"; then
        echo-color "@blue@b[[+ Installing Alacritty terminfo ]]"
        git clone https://github.com/alacritty/alacritty.git /tmp/alacritty
        cd /tmp/alacritty
        sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
        cd $HOME
        rm -fr /tmp/alacritty
    fi
    # get fucking bent, Catalina | what is this??
    xattr -r -d com.apple.quarantine /Applications/Alacritty.app
fi

echo-header "SETTING UP TILING.."

if is-mac; then
    brew install jq
    brew tap koekeishiya/formulae
    brew install yabai
    brew install skhd
    git_clone_recursive \
        $HOME/code/tools    \
        "limelight"         \
        git@github.com:molleweide/limelight.git

    pushd $HOME/code/tools/limelight > /dev/null 2>&1
    make
    popd $dest> /dev/null 2>&1
    create-symlink $install_dir/limelight/bin/limelight /usr/local/bin/limelight
    # TODO: uebersicht yabai
    brew services start skhd
    brew services start yabai
fi
