#!/usr/bin/env bash

# https://github.com/rvaiya/warpd

# NOTE: currently dependent on GHQ (x-motemen/ghq)

# TODO: ask build for X or Wayland??

function setup_util_warpd() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance
	if is-needle --quiet "setup-util-warpd" && ! is-needle --upgrade "setup-util-warpd" && ! is-needle --uninstall "setup-util-warpd" && command-exists warpd; then
		return 0
	fi

	local GHQ_WARPD_REPO=''

	local gh_repo="rvaiya/warpd"

	# TODO: put all deps in array -> loop over them and run the setup-util command

	# Install dependencies
	if is-linux; then
		setup-util --cli='libxi-dev' APT='libxi-dev'
		setup-util --cli='libxinerama-dev' APT='libxinerama-dev'
		setup-util --cli='libxft-dev' APT='libxft-dev'
		setup-util --cli='libxfixes-dev' APT='libxfixes-dev'
		setup-util --cli='libxtst-dev' APT='libxtst-dev'
		setup-util --cli='libx11-dev' APT='libx11-dev'
		setup-util --cli='libcairo2-dev' APT='libcairo2-dev'
		setup-util --cli='libxkbcommon-dev' APT='libxkbcommon-dev'
		setup-util --cli='libwayland-dev' APT='libwayland-dev'
	fi

	GHQ_WARPD_REPO=$(ghm-get-repo-path "$gh_repo")

	# # Build
	cd "$GHQ_WARPD_REPO" && git pull


	# PR: the make command fails if the bin already exists, which should be
	# fixed in the origin repo
	make
	sudo make install
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_warpd "$@"
fi
