#!/usr/bin/env bash

echo-style "SETTING UP SURFINGKEYS"

git-clone-recursive \
    $HOME/code/web \
    "Surfingkeys" \
    git@github.com:molleweide/Surfingkeys.git

pushd $HOME/code/web/Surfingkeys >/dev/null 2>&1
git checkout molleweide
npm install
npm run build
popd >/dev/null 2>&1
