#!/usr/bin/env bash

# echo-style --g1="SETUP REAPER"

# @notes
# this script uses ghq get in some cases to clone projects that aren't
# available via a package manager.


# @todo notifications
# @todo check if exists
# @todo if macos..
# @todo add necesarry setup stuff to secrets.sh
#       use with dorothy secrets command
#       read secrets: neomutt.

# ---------------------------
# ---       neomutt       ---
# ---------------------------
# https://github.com/LukeSmithxyz/mutt-wizard
# todo: ghq get mw
mw=$(which mw)
if test -z $mw; then
    ghq get "https://github.com/LukeSmithxyz/mutt-wizard"
    cd ~/code/repos/github.com/LukeSmithxyz/mutt-wizard
    sudo make install


    # @todo
    # setup pass init for email
    # loop all emails in config.local

    # mw -a hjalmar.jakobsson@telia.com -i mailout.telia.com -s mailout.telia.com

    # todo setup mail sync.
else
    echo "TG (TELEGRAM) exists..."
fi


# ----------------------------
# ---       TELEGRAM       ---
# ----------------------------
# setup: https://github.com/paul-nameless/tg#configuration
tg=$(which tg)
if test -z $tg; then
    brew tap paul-nameless/homebrew-repo
    brew install tg
else
    echo "TG (TELEGRAM) exists..."
fi

# --------------------------
# ---       SIGNAL       ---
# --------------------------
# setup:https://github.com/derricw/siggo#dependencies
# https://github.com/boxdot/gurk-rs
if ! test -x $HOME/.local/bin/discordo; then
    ghq get "https://github.com/derricw/siggo"
    cd ~/code/repos/github.com/derricw/siggo
    make build
    mv ./bin/siggo ~/.local/bin/siggo
    brew install dbus # dependency
else
    echo "SIGGO (SIGNAL) exists..."
fi

# ---------------------------
# ---       twitter       ---
# ---------------------------
# https://github.com/sferik/twitter
# https://github.com/search?q=twitter+cli

# -----------------------------
# ---       mastodoon       ---
# -----------------------------
# https://github.com/ihabunek/toot

# -------------------------
# ---       SLACK       ---
# -------------------------
# https://github.com/erroneousboat/slack-term
# https://github.com/haskellcamargo/sclack

# ---------------------------
# ---       weechat       ---
# ---------------------------
# https://github.com/weechat/weechat

# ----------------------------
# ---       whatsapp       ---
# ----------------------------
#   https://github.com/gimploo/scuffed_whatsapp
#     ask maintainer > is there anything important that I should be aware of
#     when using???
#   https://github.com/sspeedy99/whatsapp-cli
# header titl


# ---------------------------
# ---       DISCORD       ---
# ---------------------------

# @todo test if discord exists

if ! test -x $HOME/.local/bin/discordo; then
    ghq get "git@github.com:ayntgl/discordo.git"
    cd ~/code/repos/github.com/ayntgl/discordo
    make build
    mv ./discordo ~/.local/bin/discordo
else
    echo "DISCORDO (DISCORD) exists..."
fi
