#!/usr/bin/env bash

# TODO: launcher -> fzf -> select yabai action -> run
# ^ Ie. create a controller for the window manager that does not require eating
#   up keybindings real estate
# ^ Eg. select <target>s -> <action>s -> Show `This will do XYZ - [CONFIRM]`

# ============================================
# TESTS FOR `SETUP_WINDOW_MANAGER`

function setup_window_manager_test() (
    source "$DOROTHY/sources/bash.bash"
    echo-segment --h1="TEST: $0"
    echo-segment --g1="TEST: $0"
    return 0
)
# =====================================
# MAIN COMMAND `SETUP-WINDOW-MANAGER`

# TODO: list available window managers

function setup_window_manager() (
    source "$DOROTHY/sources/bash.bash"

    local mac_available_window_managers=(
        "yabai"
        "aerospace"
    )

    local linux_available_window_managers=(
        awesomewm
        i3
    )

    function help {
        cat <<-EOF >/dev/stderr
			      USAGE:
			        setup-window-manager ...


			        install

			        uninstall

			        restart
		EOF
        if test "$#" -ne 0; then
            echo-error "$@"
        fi
        return 22 # EINVAL 22 Invalid argument
    }

    local option_action='' option_target_wm=''

    while test "$#" -ne 0; do
        item="$1"
        shift
        case "$item" in
        '--help' | '-h') help ;;
        '--use='*)
            option_action="install"
            option_target_wm="${item#*=}"
            ;;
        '--uninstall='*)
            option_action="uninstall"
            option_uninstall_target="${item#*=}"
            ;;
        *) help "An unrecognised argument was provided: $item" ;;
        esac
    done

    # choose window manager
    if [[ -z $option_target_wm ]]; then
        option_target_wm="$(
            choose --required --linger \
                --question='Which window manager to setup?' \
                -- "${mac_available_window_managers[@]}"
        )"
    fi

    # choose action
    if [[ -z "$option_action" ]]; then
        option_action="$(
            choose --required --linger \
                --question='What action to perform?' \
                -- "install" "uninstall" "restart"
        )"
    fi

    if is-mac; then

        # TODO: Support https://github.com/FelixKratz/JankyBorders
        # Window borders were removed from yabai due to too many issues.
        # https://github.com/koekeishiya/yabai/issues/1889
        # A more recent project janky borders, to which yabai dev has contributed
        # to now exists.

        # WARN: Remember, to put each specific package in a setup-util-.. command.

        # macos: yabai

        if [[ $option_target_wm == "yabai" ]]; then

            if [[ "$option_action" == "install" ]]; then

                # TODO: ensure other window managers are not used/setup
                # ask uninstall others?

                setup-util --cli="yabai" BREW="koekeishiya/formulae/yabai"

                if [[ -d "$DOROTHY/user/config.xdg/yabai" ]]; then
                    symlink-helper \
                        --existing="$DOROTHY/user/config.xdg/yabai" \
                        --symlink="$XDG_CONFIG_HOME/yabai"

                # else
                #     mkdir -p ~/.config/sketchybar/plugins
                #     cp "$(brew --prefix)/share/sketchybar/examples/sketchybarrc" ~/.config/sketchybar/sketchybarrc
                #     cp -r "$(brew --prefix)/share/sketchybar/examples/plugins/" ~/.config/sketchybar/plugins/
                fi

                # old: brew services start yabai
                yabai --start-service
                # Error: yabai: service file '/Users/<USER>/Library/LaunchAgents/com.koekeishiya.yabai.plist' is not installed! attempting installation..
                # https://github.com/koekeishiya/yabai/issues/2156
                # ^ Solution: perms for LaunchAgents/ dir has to be read AND write for `staff`.

                # TODO: Capture stdout from yabai to pattern match if the string
                # is non-empty and if it contains ``

                sudo chown -R :staff ~/Library/LaunchAgents/
                sudo chmod -R 770 ~/Library/LaunchAgents/

                # TODO: how to grant accessibility permisions here? <<

                yabai --restart-service
            elif [[ "$option_action" == "uninstall" ]]; then

                if __command_exists yabai; then

                    yabai --stop-service
                    yabai --uninstall-service

                    # Can only be done with disabled SIP
                    # sudo yabai --uninstall-sa # uninstall the scripting addition

                    # brew uninstall yabai # replace with setup-util
                    setup-util --uninstall --cli="yabai" BREW="koekeishiya/formulae/yabai"

                    # these are logfiles that may be created when running yabai as a service.
                    rm -rf "/tmp/yabai_$USER.out.log"
                    rm -rf "/tmp/yabai_$USER.err.log"

                    # remove config and various temporary files
                    # rm ~/.yabairc
                    rm "/tmp/yabai_$USER.lock"
                    rm "/tmp/yabai_$USER.socket"
                    rm "/tmp/yabai-sa_$USER.socket"

                    # unload the scripting addition by forcing a restart of Dock.app
                    killall Dock
                fi

            elif [[ "$option_action" == "restart" ]]; then
                yabai --restart-service

            elif [[ "$option_action" == "launcher_actions" ]]; then
                :
                # TODO: Run launcher.
                # List possible actions that could be done with yabai.
                #   Eg. browse existing apps? Focus selection
                #   Eg. browse existing desktop "spaces"
                # ^ The Launcher should b spawned in the currently active monitor window.
            fi
        fi

        # macos: aerospace

        if [[ $option_target_wm == "aerospace" ]]; then
            if [[ "$option_action" == "install" ]]; then
                # TODO: ensure other window managers are not used/setup
                # ask uninstall others?

                setup-util --cli="aerospace" BREW="nikitabobko/tap/aerospace"

                if [[ -d "$DOROTHY/user/config.xdg/aerospace" ]]; then
                    symlink-helper \
                        --existing="$DOROTHY/user/config.xdg/aerospace" \
                        --symlink="$XDG_CONFIG_HOME/aerospace"
                else
                    # i believe that the default config doesnt need to be created.
                    mkdir -p ~/.config/aerospace
                    cp /Applications/AeroSpace.app/Contents/Resources/default-config.toml "$XDG_CONFIG_HOME/aerospace/aerospace.toml"
                fi

            elif [[ "$option_action" == "uninstall" ]]; then
                :
            fi

        fi

        # NOTE: This macos option supposedly improves experience. I dunno what it does yet.

        # # https://felixkratz.github.io/SketchyBar/setup#prerequisite
        # # https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces
        # defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer

    else

        if [ "$XDG_SESSION_TYPE" = "x11" ]; then
            setup-util-bspwm
        elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
            setup-util-sway
        else
            echo "Unknown session type or not set."
        fi
    fi
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_window_manager "$@"
fi
