#!/usr/bin/env bash

function setup_util_ghq() (
  source "$DOROTHY/sources/bash.bash"

  # improve performance for detectable utilities with conditional assets
  if setup-util "$@" --check --cli=ghq; then
    return 0
  fi

  # setup
  local options=(
    --cli='ghq'
    "$@"
    BREW='ghq'
    CONDA='ghq'
    GO='github.com/x-motemen/ghq@latest'
    GUIX='ghq' # VOID
    SCOOP='ghq'
    XBPS='ghq' # VOID
  )

  setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  setup_util_ghq "$@"
fi
