#!/usr/bin/env bash

echo-style --h1 "SETTING UP UBERSICHT.."

mac_uber_dir="$HOME/Library/Application Support/Übersicht/widgets"

# https://github.com/Mortennn/Dozer
# https://github.com/exelban/stats
# https://github.com/matryer/xbar
# https://github.com/chrisshiplet/btcbar
# https://github.com/igorkulman/ChangeMenuBarColor
# https://github.com/blaadje/fancyBar#readme
# https://github.com/apierz/nerdbar.widget
# https://github.com/Jean-Tinland/simple-bar
# https://github.com/kkga/nibar

function uber_widget() {
    local alt_name=$1
    local uber_repo=$2
    local install_dir=$HOME/code/widgets
    local WIDGET_DIR="$HOME/Library/Application Support/Übersicht/widgets"
    git-clone-recursive  \
        $install_dir     \
        $alt_name        \
        $uber_repo

    symlink-file "$install_dir/$alt_name" "$WIDGET_DIR/$alt_name"
}

echo-style --h1 --cyan "WIDGET: BAR"
if is-mac; then
    uber_widget "simple-bar"  "git@github.com:molleweide/simple-bar.git"
    # symlink-dir "$HOME/code/widgets/simple-bar" $mac_uber_dir
    # https://github.com/molleweide/spacebar     <<<------ C
else
    echo "linux todo: polybar"
    # https://github.com/polybar/polybar
    # https://github.com/LukeSmithxyz/dwmblocks.git
fi
