#!/usr/bin/env bash

# echo-header "SETTING UP NODE.."
# [ ! -d $NVM_DIR ] && curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
# # [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# nvm install stable


