#!/usr/bin/env bash

# https://github.com/tmux-plugins/tmux-urlview
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
# https://github.com/sigpipe/urlview

function setup_util_tmux() (

    # setup
    local options=(
        --name='Tmux'
        --cli=tmux
        "$@"
        APK='tmux' # ALPINE
        APT='tmux' # UBUNTU
        AUR='tmux' # ARCH
        BREW='tmux'
    )

    # NOTE: Now this should pick up on my config and symlink it

    setup-util "${options[@]}"

    # Setup plugins
    local config_dir="$XDG_CONFIG_HOME/tmux" tmux_plug_dir
    if [[ -d "$config_dir" ]]; then

        if confirm --positive --ppid=$$ -- "Do you want to setup the tmux plugin manager inside your config?"; then

            tmux_plug_dir="$config_dir/plugins/tpm"

            if [[ ! -d "$tmux_plug_dir" ]]; then
                mkdir -p "$config_dir/plugins"
                git clone git@github.com:tmux-plugins/tpm.git "$tmux_plug_dir"
            fi

            install_script="$tmux_plug_dir/bin/install_plugins"

            if [ -x "$install_script" ]; then
                $install_script
            fi
        fi
    fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_util_tmux "$@"
fi
