#!/usr/bin/env bash

# NOTE: Ideally, use KMonad or Kanata for all keymappings.
# The issue is however, that on MacOS you cant call some binaries from the
# above mentionned keymappings due to some permissions issues, that seem
# impossible to overcome.
# ^ Therefore, these tools can be used to setup hotkeys, both on linux and mac,
# but mainly intended for mac, to make these special mappings that require
# calling these "problematic" binaries.

# https://support.apple.com/en-gb/guide/terminal/apdc6c1077b-5d5d-4d35-9c19-60f2397b2369/mac
# https://iboysoft.com/wiki/library-launchagents.html

# TODO: support
# mac:
# ~ skhd (maintenance mode) | https://github.com/koekeishiya/skhd
# ~ skhd.zig (bc compat predecessor) | https://github.com/jackielii/skhd.zig
#   ^ Default to zig, but allow for installing the older version.
#   >> setup-util-skhd
# linux:
# ??

function setup_hotkeys() (
    source "$DOROTHY/sources/bash.bash"

    # FIX: skhd: could not lock pid-file! abort..

    local launch_agent_config="$HOME/Library/LaunchAgents/com.koekeishiya.skhd.plist"

    plist-helper --domain="$launch_agent_config" --add -- string EnvironmentVariables:DOROTHY "$DOROTHY"

    local action=''

    while test "$#" -ne 0; do
        item="$1"
        shift
        case "$item" in
        install) action='install' ;;
        uninstall) action='uninstall' ;;
        reset) action='reset' ;;
        print) action='print' ;;
        *) exit 0 ;;
        esac
    done

    if [[ -z $action ]]; then
        action="install"
    fi

    function rm_logs() {
        rm -rf "/tmp/skhd_$USER.out.log"
        rm -rf "/tmp/skhd_$USER.out.log"
        rm -rf "/tmp/skhd_$USER.pid"

    }

    if [[ "$action" == "install" ]]; then

        setup-util --cli="skhd" BREW="koekeishiya/formulae/skhd"
        # brew install jackielii/tap/skhd-zig
        # setup-util --cli="skhd" BREW="jackielii/tap/skhd-zig"

        rm_logs

        # this should amongst other ensure that the launch agent file is created.
        skhd --install-service

        plist-helper --domain="$launch_agent_config" --add --quiet -- string EnvironmentVariables:DOROTHY "$DOROTHY"

        skhd --start-service

    elif [[ "$action" == "print" ]]; then
        plist-helper --domain="$launch_agent_config" --print

    elif [[ "$action" == "reset" ]]; then

        skhd --stop-service || :

        rm_logs

        skhd --uninstall-service
        skhd --install-service

        sudo chown -R :staff ~/Library/LaunchAgents/
        sudo chmod -R 770 ~/Library/LaunchAgents/

        plist-helper --domain="$launch_agent_config" --add --quiet -- string EnvironmentVariables:DOROTHY "$DOROTHY"

        skhd --start-service

    elif [[ "$action" == "uninstall" ]]; then

        skhd --stop-service
        skhd --uninstall-service

        setup-util --uninstall --cli="skhd" BREW="koekeishiya/formulae/skhd"

        # logs
        rm -rf "/tmp/skhd_$USER.out.log"
        rm -rf "/tmp/skhd_$USER.out.log"
        rm -rf "/tmp/skhd_$USER.pid"

        # NEW
        # brew uninstall jackielii/tap/skhd-zig
        # setup-util --uninstall --cli="skhd" BREW="jackielii/tap/skhd-zig"
    fi
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_hotkeys "$@"
fi
