#!/usr/bin/env bash

function setup_user() (

    util-config-helper --symlink-simple

    # Opt-in to create links
    export SETUP_UTIL_LINK_CONFIGS=yes

    ghm restore "github.com/molleweide/doom-nvim" "$XDG_CONFIG_HOME/nvim"


    # TEST: to see that the user exported config vars exist.
    setup-util-neovim-test

    # Notes
    ghm restore "github.com/molleweide/neorg_user" "$HOME/neorg"

    # setup-kmonad

    # setup-util-hammerspoon

    # Will this be picked up by `setup-util` and moved to the setup-util segment of setup.bash?
    setup-util-tmux

    # if is-mac; then
    #     setup-user-osx
    # fi

    # confirm -> do you want to setup system?
    # setup-system

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_user "$@"
fi
