#!/usr/bin/env bash

# NOTE: Ideally, use KMonad or Kanata for all keymappings.
# The issue is however, that on MacOS you cant call some binaries from the
# above mentionned keymappings due to some permissions issues, that seem
# impossible to overcome.
# ^ Therefore, these tools can be used to setup hotkeys, both on linux and mac,
# but mainly intended for mac, to make these special mappings that require
# calling these "problematic" binaries.

function setup_hotkeys() (
	source "$DOROTHY/sources/bash.bash"

	# TODO: support
	# mac:
	# ~ skhd (maintenance mode) | https://github.com/koekeishiya/skhd
	# ~ skhd.zig (bc compat predecessor) | https://github.com/jackielii/skhd.zig
	#   ^ Default to zig, but allow for installing the older version.
	#   >> setup-util-skhd
	# linux:
	# ??

	# FIX: skhd: could not lock pid-file! abort..

	local launch_agent_config=~/Library/LaunchAgents/com.koekeishiya.skhd.plist

	if [[ -z "${1-}" ]]; then

		# OLD
		setup-util --cli="skhd" BREW="koekeishiya/formulae/skhd"

        # remove outdated logs
		rm -rf "/tmp/skhd_$USER.out.log"
		rm -rf "/tmp/skhd_$USER.out.log"
		rm -rf "/tmp/skhd_$USER.pid"

        # this should amongst other ensure that the launch agent file is created.
		skhd --install-service

		if defaults read "$launch_agent_config" EnvironmentVariables | grep -q 'DOROTHY ='; then
			echo "dorothy env var exists in SKHD launc agent config"
		else
			echo "dorothy did not exist in launch config"
			echo "adding it now..."
			defaults write "$launch_agent_config" EnvironmentVariables -dict-add DOROTHY "$DOROTHY"
		fi

		skhd --start-service

		# NEW
		# brew install jackielii/tap/skhd-zig
		# setup-util --cli="skhd" BREW="jackielii/tap/skhd-zig"

	else

		skhd --stop-service
		skhd --uninstall-service

		setup-util --uninstall --cli="skhd" BREW="koekeishiya/formulae/skhd"

        # logs
		rm -rf "/tmp/skhd_$USER.out.log"
		rm -rf "/tmp/skhd_$USER.out.log"
		rm -rf "/tmp/skhd_$USER.pid"

		# NEW
		# brew uninstall jackielii/tap/skhd-zig
		# setup-util --uninstall --cli="skhd" BREW="jackielii/tap/skhd-zig"
	fi
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_hotkeys "$@"
fi
