#!/usr/bin/env bash

# NOTE: 1. qutebrowser now works on both linux and macos!!!!
# 2. I have my own dark mode config for qute.
# 3. Needs to be symlinked to $HOME on macos...

function setup_util_qutebrowser() (
    source "$DOROTHY/sources/bash.bash"

    # setup
    local options=(
        --name='Qute Browser'
        --cli=qutebrowser
        "$@"
        BREW='qutebrowser'
    )

    # NOTE: Pass down the custom config location to setup-util.

    if is-mac; then
        options+=(--user-config-target="$HOME/.qutebrowser")
    else
        options+=(--user-config-target="$XDG_CONFIG_HOME/qutebrowser")
    fi

    setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_util_qutebrowser "$@"
fi
