#!/usr/bin/env bash

echo-header "SETTING UP HASKELL.."

if is-mac; then
  brew install ghc
  if test ! $(which stack); then
      curl -sSL https://get.haskellstack.org/ | sh
  fi
  stack upgrade
  stack install yesod-bin --install-ghc
fi

