#!/usr/bin/env bash

echo-header "SETTING UP SYMLINKS..."


#   https://stackoverflow.com/questions/22558245/exclude-list-of-files-from-find
#

# find "${BASH_SOURCE%/*}"/home/.config -maxdepth 1 -mindepth 1 # -print '%f\n'
# find home/.config -maxdepth 1 -mindepth 1 # -print '%f\n'

# for dir in /tmp/*/     # list directories in the form "/tmp/dirname/"
# do
#     dir=${dir%*/}      # remove the trailing "/"
#     echo "${dir##*/}"    # print everything after the final "/"
# done

symlink-create .zshenv ~/.zshenv

symlink-create .config/shell              ~/.config/shell
symlink-create .config/zsh                ~/.config/zsh
symlink-create .config/alacritty          ~/.config/alacritty
symlink-create .config/base16-shell       ~/.config/base16-shell
symlink-create .config/bat                ~/.config/bat
symlink-create .config/calcurse           ~/.config/calcurse
symlink-create .config/chad-nvim          ~/.config/chad-nvim
symlink-create .config/doom-nvim          ~/.config/doom-nvim
symlink-create .config/doom.d             ~/.config/doom.d
symlink-create .config/gem                ~/.config/gem
symlink-create .config/git                ~/.config/git
symlink-create .config/irb                ~/.config/irb
symlink-create .config/irssi              ~/.config/irssi
symlink-create .config/karabiner          ~/.config/karabiner
symlink-create .config/kitty              ~/.config/kitty
symlink-create .config/luacheck           ~/.config/luacheck
symlink-create .config/limelight          ~/.config/limelight
symlink-create .config/molleweide-nvim    ~/.config/molleweide-nvim
symlink-create .config/most               ~/.config/most
symlink-create .config/mpv                ~/.config/mpv
symlink-create .config/mutt               ~/.config/mutt
symlink-create .config/neovhy-nvim        ~/.config/neovhy-nvim
symlink-create .config/nnn                ~/.config/nnn
symlink-create .config/nvim               ~/.config/nvim
symlink-create .config/octave             ~/.config/octave
symlink-create .config/pry                ~/.config/pry
symlink-create .config/qutebrowser        ~/.config/qutebrowser
symlink-create .config/ranger             ~/.config/ranger
symlink-create .config/readline           ~/.config/readline
symlink-create .config/rvm                ~/.config/rvm
symlink-create .config/sc-im              ~/.config/sc-im
symlink-create .config/skhd               ~/.config/skhd
symlink-create .config/shell               ~/.config/shell
symlink-create .config/surfingkeys        ~/.config/surfingkeys
symlink-create .config/tg                 ~/.config/tg
symlink-create .config/tmux               ~/.config/tmux
symlink-create .config/tmuxinator         ~/.config/tmuxinator
symlink-create .config/vscode             ~/.config/vscode
symlink-create .config/yabai              ~/.config/yabai
symlink-create .local/scripts ~/.local/scripts
symlink-create .hammerspoon ~/.hammerspoon

# how to do this???
# symlink-create home/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf \
#     ~/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf
# symlink-create home/.rvm/hooks/after_cd_nvm \
#     ~/.rvm/hooks/after_cd_nvm
# symlink-create home/.rvm/hooks/after_install_add_default_gems \
#     ~/.rvm/hooks/after_install_add_default_gems
