#!/usr/bin/env bash

echo-header "SETTING UP NODE.."

# install nvm
if [ ! -d $NVM_DIR ]; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
fi

# This loads nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

nvm install stable

brew install yarn
