#!/usr/bin/env bash

# https://github.com/golang/go/wiki/Ubuntu

function setup_util_stack() (

	if ! command-exists stack; then

		if command-exists curl; then
			curl -sSL https://get.haskellstack.org/ | sh
		elif command-exists wget; then
			wget -qO- https://get.haskellstack.org/ | sh
		else
			echo-error "Failed to install Stack. Neither [curl] or [wget] command exists on system."
		fi
	else
		echo "STACK EXISTS"
	fi
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_stack "$@"
fi
