#!/usr/bin/env bash

echo-header "SETTING UP PYTHON..."

arch="$(get-arch)"

# is-mac && export PYTHON_CONFIGURE_OPTS="--enable-framework"
# is-linux && export PYTHON_CONFIGURE_OPTS="--enable-shared"

# export PYENV_VIRTUALENV_DISABLE_PROMPT=1
# export PATH="$PYENV_ROOT/bin:$PATH"

# install pyenv
if ! command-exists "pyenv"; then
    curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
fi

# install pyenv virtualenv
plugin_path="$PYENV_ROOT/plugins/pyenv-virtualenv"
if [ ! -d "$plugin_path" ]; then
    git clone https://github.com/pyenv/pyenv-virtualenv.git "$plugin_path"
fi

# load pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# install python
pyenv install -s 3.9.1
if is-mac && test "$arch" = 'a64'; then
    pyenv global 3.9.1
else
    pyenv install -s 2.7.16
    pyenv global 2.7.16
fi

# install virtual python env
if [ ! -d $PYENV_ROOT/plugins/pyenv-virtualenv ]; then
    git clone https://github.com/yyuu/pyenv-virtualenv.git $PYENV_ROOT/plugins/pyenv-virtualenv
fi
if ! pyenv virtualenvs | grep -q py2neovim; then
    pyenv virtualenv 2.7.16 py2neovim
    pyenv activate py2neovim
fi
if ! pyenv virtualenvs | grep -q py3neovim; then
    pyenv virtualenv 3.9.1 py3neovim
    pyenv activate py3neovim
fi
pip install --upgrade pip
# pip install neovim
