#!/usr/bin/env bash

echo-header --h1 "SETTING UP TERMINAL.."
if is-mac; then
    if command-exists "alacritty"; then
        echo-style --blue "[[+ Installing Alacritty terminfo ]]"
        git clone https://github.com/alacritty/alacritty.git /tmp/alacritty
        cd /tmp/alacritty
        sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
        cd $HOME
        rm -fr /tmp/alacritty
    fi
    xattr -r -d com.apple.quarantine /Applications/Alacritty.app
fi
