#!/usr/bin/env bash


# NOTE: 1. qutebrowser now works on both linux and macos!!!!
# 2. I have my own dark mode config for qute.
# 3. Needs to be symlinked to $HOME on macos...

function setup_util_qute_browser() (
  source "$DOROTHY/sources/bash.bash"


  # NOTE: install `qutebrowser`

  # setup-util

  # NOTE: setup-config
  #
  # NOTE: GHQ?
  # The issue with ghq is that we cannot know what someones config repo
  # is called and therefore it is a bit unreliable to check for names
  # here. but we could at least do a check??

  if is-mac; then
    :
    # symlink to ~
  else
    :
    # symlink to .config
  fi


)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
  setup_util_qute_browser "$@"
fi
