#!/usr/bin/env bash

echo-style --h1+red="SETTING UP WALLPAPER.."
# https://apple.stackexchange.com/questions/75081/automatically-change-os-x-desktop-background-for-all-desktops-monitors
# https://stackoverflow.com/questions/5550895/shell-script-changing-desktop-wallpaper
# https://www.howtogeek.com/258461/how-to-use-a-screensaver-as-your-background-on-os-x/
# https://stackoverflow.com/questions/431205/how-can-i-programmatically-change-the-background-in-mac-os-x
WALLPAPER="$DOROTHY/user/media/wallpaper/wallpaper2.png"
osascript -e \
    "tell application \"Finder\" to set desktop picture to POSIX file \"$WALLPAPER\""
