#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

echo-style --h1 --green "LINK USER CONFIGS.."
export FORCE_LINK='yes'

ghq_user="$HOME/code/repos/github.com/molleweide"
conf_dst=$HOME/.config

for f in "$DOROTHY"/user/config.xdg/*; do
	if test "$(basename "$f")" = "_"; then
		# echo ">>>>>>> $f"
		continue # Ignore the folder and move to the next iteration of the loop
	fi
	symlink-file "$f" "$conf_dst/$(basename "$f")"
done

# symlink-file "$ghq_user/doom-nvim" "$conf_dst/nvim"
# symlink-file "$HOME/code/repos/github.com/molleweide/doom-nvim" "$conf_dst/nvim"

if is-mac; then
	# ~/Library/Application Support/obs-studio/
	# symlink-file "$ghq_user/config_hammerspoon" "$conf_dst/hammerspoon"
	:
elif is-linux; then
	# ~/.config/obs-studio/
	# symlink-file "$ghq_user/config_hammerspoon" "$conf_dst/hammerspoon"
	:
fi

## SPECIAL SNOWFLAKES
# ln -s ~/.config/mbsync/config ~/.mbsyncrc
