#!/usr/bin/env bash

echo-style --g1="SETUP REAPER"

# https://forum.cockos.com/showthread.php?p=2487247#post2487247
# https://forum.cockos.com/showthread.php?t=242922&highlight=reaper+update+utility
# https://github.com/iliaspoulakis/Reaper-Tools/blob/master/Various/REAPER%20Update%20Utility.lua
# - cli > write log file to $REAPER_APP_DIR/rpp.log
# - look at reaper update utility.
#   can this one be used / compatible with branches

export REAPER_DIR=$HOME/reaper
export REAPER_APP_DIR=$REAPER_DIR/app
# export REAPER_CLI=$REAPER_APP_DIR/reaper-latest
# export PATH="$PATH:$REAPER_APP_DIR"

mkdir -p $REAPER_DIR/app
mkdir -p $REAPER_DIR/projects
mkdir -p $REAPER_DIR/tmp
mkdir -p $REAPER_DIR/backup

export GIT_DEFAULT_BRANCH="molleweide" # rm...

github_user=$(git config github.user)
install_path="$REAPER_APP_DIR/${1-reaper}"
app_name="${1-reaper}.app"

if ! test -d $install_path; then
    if ! confirm-bool --ppid=$$ -- "Do you want to install Reaper to [$install_path]?"; then
    #     install-reaper
    # else
        exit 1
    fi
else
    echo-style --g3="Reaper already exists at '$install_path'. \ You can install a new instance by 'setup-reaper <name>'."
    exit 1
fi

if ! test -d $install_path; then
    echo-style --green="Installing latest version of Reaper to $install_path"
	if test -n "$github_user"; then
		reaperConfig="git@github.com:$github_user/reaper-config.git"
		if ! confirm-bool --ppid=$$ -- "Does this repository house your Reaper configuration? [$reaperConfig]"; then
			reaperConfig=''
		fi
	fi
	echo-style --purple="Cloning the Reaper configuration into $install_path"
	if ! git clone "$reaperConfig" $install_path; then
		echo-style --orange="The clone of the repository [$reaperConfig] to [$install_path] failed."
		echo-style --orange="Dorothy will initialise the directory as a git repository, and leave it up to you to sync it up with a remote."
		echo-style
		pushd $install_path > /dev/null || exit 1
		silent git init
		popd > /dev/null || exit 1
	else
	    echo-style --magenta="checkout branch ($GIT_DEFAULT_BRANCH)!!"
        pushd $install_path > /dev/null 2>&1
        git checkout $GIT_DEFAULT_BRANCH
        git submodule update --init --recursive
        # cd Scripts/reaper-keys && git checkout molleweide && cd ../..
        # cd Effects/molleweide && git checkout molleweide && cd ../..
        # cd ColorThemes && git checkout molleweide && cd ..
        popd > /dev/null 2>&1
	fi
	echo-style --g2="Downloading the reaper executable."
    brew install --cask reaper --appdir=$install_path --force
    $(mv "$install_path/REAPER.app" $install_path/$app_name)
fi
