#!/usr/bin/env bash

echo-header "SETTING UP LUA.."

brew install lua
brew install luarocks
brew install ninja

luarocks install loop
luarocks install dkjson
luarocks install inspect
luarocks install --server=http://luarocks.org/dev lua-lsp
luarocks install luacheck
luarocks install lcf

# INSTALL LUA LANGUAGE SERVER
lspdir="$HOME/.local/nvim/lsp"
location="$lspdir/lua-language-server"
if [ ! -d "$location" ]; then
    echo-color "@b@blue[[+ Installing sumneko Lua LSP]]"
    mkdir -p "$lspdir"
    git clone https://github.com/sumneko/lua-language-server "$location"
    cd "$location" || exit 1
    git checkout tags/1.14.2 -b install-1.14.2
    git submodule update --init --recursive
    cd 3rd/luamake || exit 1
    ninja -f ninja/macos.ninja
    cd ../.. || exit 1
    ./3rd/luamake/luamake rebuild
fi

echo-header "SETTING UP HASKELL.."

is-mac && brew install ghc
test ! $(which stack) && curl -sSL https://get.haskellstack.org/ | sh
stack upgrade
# stack install yesod-bin --install-ghc

