#!/usr/bin/env bash

# https://github.com/tmux-plugins/tmux-urlview
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
# https://github.com/sigpipe/urlview

function setup_util_tmux() (

    # Install CLI

    # Setup plugins

    local TMUX_PLUG_DIR="$HOME/.config/tmux/plugins/tpm"

    [ ! -d "$TMUX_PLUG_DIR" ] && git clone git@github.com:tmux-plugins/tpm.git "$TMUX_PLUG_DIR"

    install_script="$TMUX_PLUG_DIR/bin/install_plugins"

    if [ -x "$install_script" ]; then
        $install_script
    fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_util_tmux "$@"
fi
