#!/usr/bin/env bash

# NOTE: STATUS BARS TO CHECK OUT
# setup-util-polybar
# lemonbar
# i3status
# https://codeberg.org/xmobar/xmobar
# spacebar for macos
# https://github.com/FelixKratz/SketchyBar
# https://github.com/Jean-Tinland/simple-bar

# NOTE: sketchybar configs
# setup -> https://felixkratz.github.io/SketchyBar/setup
#
# config files:
#   https://gist.github.com/johnallen3d/6c002ef1f4e1e0fc15ce74bfc8390614
#   https://github.com/mvritz/dotfiles/tree/main/sketchybar
#   https://github.com/sasha-id/dotfiles/tree/master/sketchybar
#
#   https://github.com/FelixKratz/SketchyBar
#
#   NOTE: [sketchybar] is the predecessor to [spacebar]
#
#   NOTE: https://felixkratz.github.io/SketchyBar/setup

# spacebar
#
# brew install cmacrae/formulae/spacebar
# brew services start spacebar
# https://github.com/Jean-Tinland/simple-bar
# simple-bar requires hammerspoon
# setup-util-hammerspoon

# TODO:
# ~ switch bar
# ~ uninstall bar
# ~ browse bars current/installed/available..
#

function setup_status_bar() (
    source "$DOROTHY/sources/bash.bash"

    function help {
        cat <<-EOF >/dev/stderr
			      USAGE:
			        setup-status-bar ...

			      DESCRIPTION:
			        ...

		EOF
        if test "$#" -ne 0; then
            echo-error "$@"
        fi
        return 22 # EINVAL 22 Invalid argument
    }

    if is-mac; then
        setup-util --cli="sketchybar" BREW="FelixKratz/formulae/sketchybar"

        if [[ -d "$DOROTHY/user/config.xdg/sketchybar" ]]; then
            symlink-helper \
                --existing="$DOROTHY/user/config.xdg/sketchybar" \
                --symlink="$XDG_CONFIG_HOME/sketchybar"

        else
            mkdir -p ~/.config/sketchybar/plugins
            cp "$(brew --prefix)/share/sketchybar/examples/sketchybarrc" ~/.config/sketchybar/sketchybarrc
            cp -r "$(brew --prefix)/share/sketchybar/examples/plugins/" ~/.config/sketchybar/plugins/
        fi

        brew services start sketchybar

    else
        if [ "$XDG_SESSION_TYPE" = "x11" ]; then
            setup-util-polybar
        elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
            setup-util-waybar
        else
            echo "Unknown session type or not set."
        fi

    fi
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_status_bar "$@"
fi
