#!/usr/bin/env bash

if is-mac; then
    echo-header "Setting up HAMMERSPOON.."
    brew install --cask hammerspoon --appdir=/Applications
    url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/SpoonInstall.spoon.zip"
    destination=/tmp/SpoonInstall.spoon.zip
    spoons_dir=$HOME/.config/hammerspoon/Spoons
    if [ ! -d "$spoons_dir/SpoonInstall.spoon" ]; then
        echo-color "@blue@b[[+ installing SpoonInstall.spoon ]]"
        wget -nv $url -O $destination
        unzip -d $spoons_dir $destination
    else
        echo-color "+ SpoonInstall.spoon already setup"
    fi
    defaults write org.hammerspoon.Hammerspoon MJConfigFile "~/.config/hammerspoon/init.lua"
fi
