#!/usr/bin/env bash

echo-header "SETTING UP NODE.."

# install nvm
if [ ! -d $NVM_DIR ]; then
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
fi

# This loads nvm
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

nvm install stable

echo-header  "SETTING UP RUBY..."

# TODO: xdg >> create $RVM_DIR
#   https://stackoverflow.com/questions/15282509/how-to-change-rvm-install-location
export PATH="$HOME/.rvm/bin:$PATH"
if [ ! -e ~/.rvm ]; then
    \curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles
    [ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm
fi
rvm install ruby --latest
