#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

echo-style --h1 --green "LINK USER CONFIGS.."
export FORCE_LINK='yes'

ghq_user="$HOME/code/repos/github.com/molleweide"
conf_dst=$HOME/.config

# CONFIG.XDG
for f in $ghq_user/xdg_configs/*; do
    symlink-file "$f" "$conf_dst/$(basename $f)"
done

# NEOVIM / DOOM
symlink-file "$ghq_user/doom-nvim" "$conf_dst/nvim"
# symlink-file "$HOME/code/repos/github.com/molleweide/doom-nvim" "$conf_dst/nvim"

# HAMMERSPOON
symlink-file "$ghq_user/config_hammerspoon" "$conf_dst/hammerspoon"

## SPECIAL SNOWFLAKES
# ln -s ~/.config/mbsync/config ~/.mbsyncrc
