#!/usr/bin/env bash

echo-header "KEYBOARD"

# TODO:
# - linux

arch="$(get-arch)"
github_user=$(git config github.user)

# QMK | move this into its own `setup-user-qmk`

# TODO: check for github_user=$(git config github.user)
git_clone_recursive \
    $HOME/code/firmware \
    "qmk-firmware" \
    git@github.com:molleweide/qmk_firmware.git



# ---------------------------------------------------------------------
#
# KMONAD

# TODO:
#
#   1. check for github_user=$(git config github.user)
#       if user has fork
#       else clone upstream

# ---------------------------------------------------------------------

function macos_install_dext() {
    dext_path="c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/dist/Karabiner-DriverKit-VirtualHIDDevice-1.15.0.dmg"
    dext_path=$(defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion | grep 1.15.0)
    if test -z "$check_dext"; then
        sudo installer -pkg "$dext_path" -target /Applications
    else
        echo-style --green "dext v1.15.0 already installed"
    fi
    /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate
}

code_tools_path=$HOME/code/tools
git_clone_recursive \
    $code_tools_path \
    "kmonad" \
    git@github.com:molleweide/kmonad.git

pushd $code_tools_path/kmonad >/dev/null 2>&1
# stack clean / redo complete build
if is-mac; then
    # macos_install_dext # TODO: needs testing first
    if test "$arch" = 'a64'; then
        stack install --flag kmonad:dext --arch=aarch64 --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
    else
        stack install --flag kmonad:dext --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
    fi
else
    echo "linux todo.."
    # stack install # Check `stack path`. Should install to `$USER/.local/bin`.
    # or
    # aur: https://aur.archlinux.org/packages/kmonad-bin

fi
popd >/dev/null 2>&1
