#!/usr/bin/env bash

# NOTE: 1. qutebrowser now works on both linux and macos!!!!
# 2. I have my own dark mode config for qute.
# 3. Needs to be symlinked to $HOME on macos...

function setup_util_qutebrowser() (
    source "$DOROTHY/sources/bash.bash"

    local name=qutebrowser

    # TODO: Should we export the

    util-config-helper __setup_for_utility "$name" "$HOME/.$name"

    if is-mac; then
        :
        # symlink to ~
    else
        :
        # symlink to .config
    fi

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    setup_util_qutebrowser "$@"
fi
