#!/usr/bin/env bash

function setup_user_symlinks() {
	source "$DOROTHY/sources/strict.bash"

	echo-style --h1 --green "LINK USER CONFIGS.."
	export FORCE_LINK='yes'

	GHQ_ROOT_GH_USER="$GHQ_ROOT/github.com/molleweide"

	for f in "$GHQ_ROOT_GH_USER"/xdg_configs/*; do
		if test "$(basename "$f")" = "_"; then
			# echo ">>>>>>> $f"
			continue # Ignore the folder and move to the next iteration of the loop
		fi
		symlink-file "$f" "$XDG_CONFIG_HOME/$(basename "$f")"
	done

	# symlink-file "$GHQ_ROOT_GH_USER/doom-nvim" "$XDG_CONFIG_HOME/nvim"
	# # symlink-file "$HOME/code/repos/github.com/molleweide/doom-nvim" "$XDG_CONFIG_HOME/nvim"

	if is-mac; then
		# ~/Library/Application Support/obs-studio/
		# symlink-file "$GHQ_ROOT_GH_USER/config_hammerspoon" "$XDG_CONFIG_HOME/hammerspoon"
		:
	elif is-linux; then
		# ~/.config/obs-studio/
		# symlink-file "$GHQ_ROOT_GH_USER/config_hammerspoon" "$XDG_CONFIG_HOME/hammerspoon"
		:
	fi

	## SPECIAL SNOWFLAKES
	# ln -s ~/.config/mbsync/config ~/.mbsyncrc

}

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_user_symlinks "$@"
fi
