#!/usr/bin/env bash

echo-header "SETTING UP TMUX..."
# https://github.com/tmux-plugins/tmux-urlview
# https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
# https://github.com/sigpipe/urlview
tmux_plug_dir="$HOME/.config/tmux/plugins/tpm"
[ ! -d $tmux_plug_dir ] && git clone git@github.com:tmux-plugins/tpm.git $tmux_plug_dir
# install_script="$HOME/.tmux/plugins/tpm/bin/install_plugins"
# [ -x $install_script ] && $install_script
