#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# pull
pushd $DOROTHY/user >/dev/null 2>&1
echo "doro user pwd: $PWD"
# git submodule update --init --recursive || exit 1
popd >/dev/null 2>&1

if is-mac; then
	# setup-user-osx
	:
fi

# setup-user-config

# setup-user-base

# setup-user-keyboard

# setup-user-surfingkeys

# setup-user-neomutt

# setup-user-scim

# # setup-reaper
