#!/usr/bin/env bash

echo-header "SETTING UP SPREADSHEETS.."

# NOTE: xslx support
# https://github.com/andmarti1424/sc-im/wiki/Install-sc-im-with-xls-support-on-macOS

if is-mac; then
    # https://github.com/andmarti1424/sc-im
    # libxlsxreader (not brew)
    #     https://github.com/AsperaGmbH/xlsx-reader
    brew install ncurses gnuplot libxml2 libzip # added to generic setup utils

    install_dir=$HOME/code/apps
    dotlib_git_clone_recursive  \
        $install_dir            \
        "sc-im"           \
        git@github.com:molleweide/sc-im.git
    pushd $install_dir/sc-im > /dev/null 2>&1
    make -C src install # Edit src/Makefile according to your system and needs
    popd > /dev/null 2>&1

    # basic brew install | eg. no gnuplot...
    # brew tap nickolasburr/pfa
    # brew install sc-im
fi
