#!/usr/bin/env bash

# pushd $DOROTHY/user > /dev/null 2>&1
# git submodule update --init --recursive || exit 1
# popd > /dev/null 2>&1
# setup-user-osx
# setup-user-configs
# setup-user-base
# setup-user-ruby-node
# setup-user-python
# setup-user-lua
# setup-user-haskell
# setup-user-tmux-nvim
# setup-user-mac-apps
# setup-user-hammerspoon
# setup-user-ubersicht
# setup-user-keyboard
# setup-user-surfingkeys
# setup-user-neomutt
# setup-user-scim
# setup-user-reaper
# ../personal/stuff
