#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# TODO: if regular existing > prompt user overwrite??? yes/no

existing="${1:-"$(ask --question="What is the existing path that you want to symlink elsewhere?" --required)"}"
symlink="${2:-"$(ask --question="What is the new path that you want to redirect?" --required)"}"
force="${FORCE:-"$(get-flag-value force --missing=no -- "$@")"}"

# 1. check if symlink already is a link. if true force create new link
if test -L "$symlink"; then
    if test "$force" = 'yes' || confirm-bool "Symlink already exists at $symlink, recreate it to point to $existing?"; then
        echo-color "@b@blue[[ Re-linking: $existing -> $symlink ]]"
        rm -rf $symlink # be carefull;
        ln -s "$existing" "$symlink"
    else
        exit 1
    fi

# 2. check if $symlink already is file/dir
elif test -d "$symlink" -o -f "$symlink"; then
    echo-color "@b@red[[ Cannot link: \`$symlink\` is a regular file/dir and needs to be removed manually first... ]]"

# 3. if not link, and not file/dir > create new symlink
else
    echo-color "@b@green[[ Symlinking: $existing -> $symlink ]]"

    # create dirs up until $symlink in case
    # $symlink is a file and in a completely new
    # location.
    mkdir -p "$(dirname $symlink)"

    ln -s "$existing" "$symlink"
fi
