#!/usr/bin/env bash
source "$DOROTHY/sources/strict.bash"

# link all files from dir

export FORCE_LINK='yes'

existing_dir="${1:-"$(ask --question="What is the existing DIR PATH that you want to symlink elsewhere?" --required)"}"
symlink_dir="${2:-"$(ask --question="What is the new DIR PATH that you want to redirect MULTIPLE FILES to?" --required)"}"

for f in $existing_dir/*; do
    echo "!!!!!!!!!"
    echo "$f"
    echo "$(basename $f)"
    echo "$symlink_dir/$(basename $f)"
    echo
    symlink-file "$f" "$symlink_dir/$(basename $f)"
done
