#!/usr/bin/env bash

# TODO: if regular file > prompt user overwrite??? yes/no

file=$1
link_destination=$2
force=$3

if [ ! -e "$link_destination" ]; then
    echo-color "@b@green[[ Symlinking: $file -> $link_destination ]]"
    mkdir -p "$(dirname "$link_destination")"
    ln -s "$file" "$link_destination"
elif [[ -L $link_destination ]]; then
    echo-color "@b@blue[[ Re-linking: $file -> $link_destination ]]"
    rm -rf $link_destination # be carefull;
    ln -s "$file" "$link_destination"
else
    echo-color "@b@red[[ Cannot link: \`$link_destination\` is a regular file/dir and needs to be removed manually first... ]]"
fi
