#!/usr/bin/env bash

function util_config_helper() (
    if [[ "$DOROTHY_SETUP_UTIL_CONFIGS" == 'no' ]]; then
        return
    fi

    source "$DOROTHY/sources/bash.bash"

    # =====================================
    # Arguments

    function help {
        __print_help "$@" <<-EOF || return
			ABOUT:
			Looks for utility configs in standardized locations.

			This feature should ideally be located in a post_install,
			or action in \`setup-util\`.

			Opt-in by setting \`DOROTHY_SETUP_UTIL_CONFIGS='yes'\`.

			TYPES OF CONFIG

			            ~ public / private
			~ simple configs
			~ complex configs (hosted in their own repos)

			            SCENARIOS / SOURCES

			            ~ use external package manager (1)
			            ~ use setup-util-* (2)

			            You can either [install], or just [setup configs]

			            For (1)

			            1. check confix.xdg ??
			            2. check GHM
			            3. Query known/supported hosts for complex configs

			            For (2)

			            1. check confix.xdg ??
			            2. check GHM
			            3. Query known/supported hosts for complex configs

			            ^ In the above, for each CLI/APP, user can export their own complex
			            repo override names, by eg. \`__UC_NEOVIM=doom-neovim\`

			            ^^ I believe, that this handles all special cases that are possible.

			USAGE:
			???

			OPTIONS:



			ACTIONS:
			setup [...arguments]
			    --setup-xdg-all
			        Tries to symlink all simple configs.
			    <util_name>
			        Try to setup <util_name> by following 1-3 above.

		EOF
        return 22 # EINVAL 22 Invalid argument
    }

    # process
    local item action='' option_test_mode='no' option_args=() # option_quiet='no'
    while test "$#" -ne 0; do
        item="$1"
        shift
        case "$item" in
        --help | -h) help ;;
        --)
            option_args+=("$@")
            shift "$#"
            break
            ;;
        '--'*)
            if [[ -z $action ]]; then
                help 'An unrecognised global flag argument was provided: ' --variable-value={item}
            else
                option_args+=("$item") # forward to action
            fi
            ;;
        *)
            if [[ -z $action ]]; then
                action="$item"
            else
                option_args+=("$item")
            fi
            ;;
        esac
    done

    # check
    if [[ -z $action ]]; then
        action="testing"
        # help 'No ' --code='<action>' ' was provided.'
    fi

    # =======================================================
    # Configuration

    # TODO: If ghm backup is parsed, then export it once so that
    # it doesnt need to be done every time the command is called?

    # =======================================================
    # Helpers

    function __symlink_all_simple() {
        echo-style --h1="SETTING UP USER SYMLINKS"
        local util_name destination

        for util_path in "$DOROTHY/user/config.xdg"/* "$DOROTHY/user/config.local/config.xdg"; do
            util_name="$(basename "$util_path")"
            destination="$XDG_CONFIG_HOME/$util_name"

            # WARN: Ask Ben about naming convention for setup utils, how should it be??
            # should it be the name of the CLI?
            # ^ Maybe the setup-util database map needs to be used check for special
            # case name maps, sqlite -> sqlite3; neovim -> nvim

            if [[ -f "$DOROTHY/commands/setup-util-$util_name" ]] ; then
                __print_lines "[$util_name] is handled by setup-util-$util_name"
                continue
            fi

            symlink-helper --existing="$util_path" --symlink="$destination" --log-if-overriding-file # \ --quiet --log-if-overriding-symlink
        done

        echo-style --g1="SETTING UP USER SYMLINKS"
    }

    # TODO: ( ) Support other hosts than github.com
    __setup_config_for_utility() {
        local util_name=$1 repo_block GITHUB_USER destination repo_slug repo_block
        local util_config_override_prefix="UCO_"
        local config_override_name default_config_name="$util_name-config"

        GITHUB_USER=$(git config github.user)

        __print_lines "---- Setup configuration symlink for UTIL = [$util_name] ----"

        # ---------------------------------
        # 1. CHECK FOR SIMPLE CONFIG
        __print_lines ":: Check if a simple config exists, ie. user/config.{xdg,xdg.local} ::"

        local config_simple_path
        if [[ -f "$DOROTHY/user/config.xdg/$util_name" ]]; then
            config_simple_path="$DOROTHY/user/config.xdg/$util_name"
        fi
        if [[ -f "$DOROTHY/user/config.local/config.xdg/$util_name" ]]; then
            config_simple_path="$DOROTHY/user/config.local/config.xdg/$util_name"
        fi

        if [[ -n "$config_simple_path" ]] ; then
            __print_lines "Found simple config: $config_simple_path"
            # symlink-helper --existing="$config_simple_path" --symlink="$destination" --log-if-overriding-file # \ --quiet --log-if-overriding-symlink
            return
        fi
            __print_lines "Could not find simple config. Proceeding to check for compex config."

        # ---------------------------------
        # 2. CHECK FOR REPO STORAGE CONFIG
        __print_lines ":: Check if a complex config is managed with GHM ::"

        local cloned_path tracked_key

        # Handle env var overrides
        local config_override_name="$util_config_override_prefix${util_name^^}"
        if [[ -n "${!config_override_name}" ]]; then
            repo_slug="$GITHUB_USER/$config_override_name"
        else
            repo_slug+="$GITHUB_USER/$default_config_name" # default repo name
        fi

        repo_block="github.com/$repo_slug"

        if cloned_path="$(ghm is-cloned "$repo_block")"; then
            __print_lines "Found repo in GHM already cloned out. Linking..."
            # symlink-helper --existing="$cloned_path" --symlink="$destination" --log-if-overriding-file # \ --quiet --log-if-overriding-symlink
        elif tracked_key="$(ghm is-tracked "$repo_block")"; then
            __print_lines "Found repo is tracked in GHM database. Restore and linking..."
            # ghm restore "repo_block" "$destination"
        fi

        # ---------------------------------
        # 3. QUERY KNOWN/SUPPORTED HOSTS FOR COMPLEX CONFIGS

        __print_lines ":: Check for remote config ::"

        local repo_url

        local repo_url="sss@github.com:$repo_slug.git"

        if gh repo view "$repo_slug" &>dev/null; then
            #   ^ if mult, then prompt user to select which to use
            # ~ ghm clone <util> <destination>
            __print_lines "Remote config was found. Clone and linking..."

            ghm clone "$repo_url" "$destination"
        fi

        # ---------------------------------
        # No config was found

        __print_lines "No config could be found for util [$util_name]"

    }

    # =======================================================
    # Action

)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    util_config_helper "$@"
fi
