#!/usr/bin/env bash

# NOTE: This aims to be a unified monitor, display, window and tiling-wm helper
# so that we have a good API to manage and control applications through dorothy.

# TODO: Create a browser that allows one to query the system for

# Query
# General Syntax
#     yabai -m query <COMMAND> [<PROPERTIES>] [<ARGUMENT>]
#
# COMMAND
#     --displays
#         Retrieve information about displays.
#
#     --spaces
#         Retrieve information about spaces.
#
#     --windows
#         Retrieve information about windows.
#
# ARGUMENT
#     --display [<DISPLAY_SEL>]
#         Constrain matches to the selected display.
#
#     --space [<SPACE_SEL>]
#         Constrain matches to the selected space.
#
#     --window [<WINDOW_SEL>]
#         Constrain matches to the selected window.
#
# PROPERTIES
#     A comma-separated string containing the name of fields to include in the output.
#     The name of the provided fields must be present in the dataformat of the corresponding entity.
#
# DATAFORMAT
#     DISPLAY
#
#         {
#             "id": number,
#             "uuid": string,
#             "index": number,
#             "label": string,
#             "frame": object {
#                 "x": number,
#                 "y": number,
#                 "w": number,
#                 "h": number
#             },
#             "spaces": array of number,
#             "has-focus": bool
#         }
#
#     SPACE
#
#         {
#             "id": number,
#             "uuid": string,
#             "index": number,
#             "label": string,
#             "type": string,
#             "display": number,
#             "windows": array of number,
#             "first-window": number,
#             "last-window": number,
#             "has-focus": bool,
#             "is-visible": bool,
#             "is-native-fullscreen": bool
#         }
#
#     WINDOW
#
#         {
#             "id": number,
#             "pid": number,
#             "app": string,
#             "title": string,
#             "scratchpad": string,
#             "frame": object {
#                 "x": number,
#                 "y": number,
#                 "w": number,
#                 "h": number,
#             },
#             "role": string,
#             "subrole": string,
#             "root-window": bool,
#             "display": number,
#             "space": number,
#             "level": number,
#             "sub-level": number,
#             "layer": string,
#             "sub-layer": string,
#             "opacity": number,
#             "split-type": string,
#             "split-child": string,
#             "stack-index": number,
#             "can-move": bool,
#             "can-resize": bool,
#             "has-focus": bool,
#             "has-shadow": bool,
#             "has-parent-zoom": bool,
#             "has-fullscreen-zoom": bool,
#             "has-ax-reference": bool,
#             "is-native-fullscreen": bool,
#             "is-visible": bool,
#             "is-minimized": bool,
#             "is-hidden": bool,
#             "is-floating": bool,
#             "is-sticky": bool,
#             "is-grabbed": bool
#         }
#
#     Some window properties are only accessible when yabai has a valid AX-reference for that window.
#     This AX-reference can only be retrieved when the space that the window is visible on, is active.
#     If windows are already opened on inactive spaces when yabai is launched, yabai can detect those
#     windows and retrieve a limited amount of information about them. In addition, yabai window commands
#     will NOT WORK for these windows. These windows can be identified by looking at the has-ax-reference
#     property. Once the space that the window belongs to becomes active, yabai will automatically create
#     an AX-reference. The queries will from that point forwards contain complete information, and the window
#     can be used with yabai window commands.
#
#     The properties that contain incorrect information for windows with has-ax-reference: false are as follows:
#
#         {
#             "role": string,
#             "subrole": string,
#             "can-move": bool,
#             "can-resize": bool
#         }

# TODO: Maybe put the below info into a `view-helper`.
# https://stackoverflow.com/questions/20099333/terminal-command-to-show-connected-displays-monitors-resolutions
# https://apple.stackexchange.com/questions/141213/grab-the-active-window-in-applescript
# https://www.macscripter.net/t/possible-to-identify-screen-monitor-of-current-cursor-position/71446/2
# https://www.reddit.com/r/applescript/comments/za3jtv/help_with_scripting_monitor_display_mode/
# https://apple.stackexchange.com/questions/316213/can-i-use-applescript-to-detect-if-there-are-any-windows-on-screen
# https://stackoverflow.com/questions/14773974/set-focus-to-specific-window-of-an-application-using-applescript
# https://stackoverflow.com/questions/1146472/applescript-to-target-frontmost-application?rq=3
# https://www.macscripter.net/t/setting-focus-to-a-window-by-title/48824
# https://stackoverflow.com/questions/18372328/applescript-get-list-of-running-apps
# https://stackoverflow.com/questions/1562513/applescript-list-all-running-applications?rq=3
# https://stackoverflow.com/questions/14551419/listing-all-windows-of-all-applications?rq=3
# https://stackoverflow.com/questions/16064957/how-to-check-in-applescript-if-an-app-is-running-without-launching-it-via-osa?rq=3

# NOTE: Screen resolution.
# https://superuser.com/questions/196532/how-do-i-find-out-my-screen-resolution-from-a-shell-script
# https://superuser.com/questions/447295/how-can-i-get-the-current-screen-resolution-from-the-command-line-on-os-x
# https://stackoverflow.com/questions/24972338/get-macbook-screen-size-from-terminal-bash
# https://osxdaily.com/2014/08/31/how-to-get-current-screen-resolution-from-command-line-in-mac-os-x/
# https://stackoverflow.com/questions/20099333/terminal-command-to-show-connected-displays-monitors-resolutions
# https://apple.stackexchange.com/questions/162860/how-to-view-current-display-resolution

# NOTE: hide apps on macos
# osascript -e 'tell application "System Events" to set visible of process "Brave" to false'

function window_helper() (
    source "$DOROTHY/sources/bash.bash"

    # TODO: add flag processing.

    # TODO:
    # picker-yabai: displays, spaces, windows
    #
    #
    # TODO: Show status (Macos) quicly show which wm service that is
    # running.
    #
    # Switch to other wm [yabai <-> aerospace]

    # TODO:
    # ~ ( ) Ensure displays are properly named.
    # ~ (x) Windows cant be named
    #

    # TODO: FZF WINDOW ACTIONS PIPELINE
    # Select `window` -> select `action` -> select `selector`
    # Use dict to track what `actions` map to possible `selectors`
    #
    # ^ Over time we will evaluate which actions are useful and which
    # are stupid to support. This is not supposed to be a gigantic project.
    # Just a helper that allows for managing windows a bit better.

    # picker -> only visible windows in current monitor

    # picker -> focus window -> select by name

    # TODO: MACOS PSEUDO `SPACES`
    # Use yabai signals to write running/on-<open|close> to a text file, so that
    # we can manage which apps that should be visible in bulk.
    # ^ Including which display that is used.
    # ^^ One issue tho is handling apps that go fullscreen w eg. video.


    local window_picker_alternatives=(displays spaces windows)

    selection="$(
        echo-lines -- "${window_picker_alternatives[@]}" |
            fzf-helper -- \
                --border-label '🌴 [Window helper]: yabai picker' \
                --header $'Select which query type to inspect:\n\n'
    )"

    __print_lines "$selection"

    # TODO: jq get [index:id:label]
    # TODO: preview -> just run the yabai command for this id

    yabai -m query "--$selection" | jq '.[].id' | fzf-helper -- --preview "yabai -m query --$selection --${selection::-1} {}"

    # Use this function as a workaround to using multiple spaces (since spaces require disabling SIP with yabai),
    # so that we can show/hid windows in groups.
    show_these_only() {
        # Pass app names you want to keep visible as arguments
        local keep_list=("$@")

        # Convert Bash array to AppleScript list
        local keep_applescript_list
        keep_applescript_list=$(printf '"%s", ' "${keep_list[@]}" | sed 's/, $//')

        osascript <<-EOF
			tell application "System Events"
			    set keepList to {${keep_applescript_list}}
			    set appList to name of every process whose background only is false
			    repeat with appName in appList
			        if appName is in keepList or appName is "Finder" then
			            set visible of process appName to true
			        else
			            set visible of process appName to false
			        end if
			    end repeat
			end tell
		EOF
    }
)

# Fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
    window_helper "$@"
fi
