#!/usr/bin/env bash

# @param command        Retrieve information about command.
# @param [ argument ]   Constrain matches to argument.
test -z "${1-}" && exit 1
cmd=$1
arg=$2
if is-mac; then
    ypre="yabai -m query"
    ycmd=""
    yarg=""
    case "$cmd" in
        "dsp" | "d") ycmd="displays";;
        "spc" | "s") ycmd="spaces";;
        "win" | "w") ycmd="windows";;
        *) echo "NO_MATCH";;
    esac
    case "$arg" in
        "dsp" | "d") yarg="display";;
        "spc" | "s") yarg="space";;
        "win" | "w") yarg="window";;
        *) echo "NO_MATCH";;
    esac
    call "$ypre --$ycmd --$yarg"
else
    echo "linux todo..."
fi
