#!/usr/bin/env bash

test -z "${1-}" && exit 1

if is-mac; then
    if test "$1" = "add" -o "$1" = "a"; then
        event=$2
        action=$3 # Arbitrary command executed through /usr/bin/env sh -c
        case "$event" in
            "aac")        ybie="application_activated";;
            "ada")        ybie="application_deactivated";;
            "afs")        ybie="application_front_switched";;
            "ahi")        ybie="application_hidden";;
            "ak")         ybie="application_terminated";;
            "al")         ybie="application_launched";;
            "avi")        ybie="application_visible";;
            "dkdcp")     ybie="dock_did_change_pref";;
            "dkdr")      ybie="dock_did_restart";;
            "dmonmsg")   ybie="daemon_message";;
            "dsad")      ybie="display_added";;
            "dsch")      ybie="display_changed";;
            "dsmv")      ybie="display_moved";;
            "dsrm")      ybie="display_removed";;
            "dsrz")      ybie="display_resized";;
            "micfx")  ybie="mission_control_check_for_exit";;
            "mie")     ybie="mission_control_enter";;
            "mix")    ybie="mission_control_exit";;
            "msdn")        ybie="mouse_down";;
            "msdr")        ybie="mouse_dragged";;
            "msmv")        ybie="mouse_moved";;
            "msup")        ybie="mouse_up";;
            "mubhc")     ybie="menu_bar_hidden_changed";;
            "muo")       ybie="menu_opened";;
            "sch")          ybie="space_changed";;
            "syswk")     ybie="system_woke";;
            "wc")       ybie="window_created";;
            "wdm")       ybie="window_deminimized";;
            "wf")       ybie="window_focused";;
            "wk")       ybie="window_destroyed";;
            "wmi")       ybie="window_minimized";;
            "wmv")       ybie="window_moved";;
            "wrz")       ybie="window_resized";;
            "wtc")       ybie="window_title_changed";;
            *) echo "NO_MATCH" && exit 1;;
        esac
        for i in ${@:4}; do
            pre=${i%=*}
            post=${i#*=}
            if test "$pre" = "label" -o "$pre" = "l"; then
                yl="label=\"$post\""
            elif test "$pre" = "app" -o "$pre" = "a"; then
                ya="app=\"$post\""
            elif test "$pre" = "title" -o "$pre" = "t"; then
                yt="title=\"$post\""
            fi
        done
        echo "yabai -m signal --add event=$ybie action=\"$action\" $yl $ya $yt"
	elif test "$1" = 'remove' -o "$1" = 'rm'; then
        echo "yabai -m signal --remove $2"
	elif test "$1" = 'list' -o "$1" = 'ls'; then
        echo "yabai -m signal --list"
	fi
else
    echo "linux todo..."
fi
