#!/usr/bin/env bash

test -z "${1-}" && exit 1

if is-mac; then
    if test "$1" = "add" -o "$1" = "a"; then
        event=$2
        action=$3 # Arbitrary command executed through /usr/bin/env sh -c
        case "$event" in
            "aac")        ye="application_activated";;
            "ada")        ye="application_deactivated";;
            "afs")        ye="application_front_switched";;
            "ahi")        ye="application_hidden";;
            "ak")         ye="application_terminated";;
            "al")         ye="application_launched";;
            "avi")        ye="application_visible";;
            "dkdcp")     ye="dock_did_change_pref";;
            "dkdr")      ye="dock_did_restart";;
            "dmonmsg")   ye="daemon_message";;
            "dsad")      ye="display_added";;
            "dsch")      ye="display_changed";;
            "dsmv")      ye="display_moved";;
            "dsrm")      ye="display_removed";;
            "dsrz")      ye="display_resized";;
            "micfx")  ye="mission_control_check_for_exit";;
            "mie")     ye="mission_control_enter";;
            "mix")    ye="mission_control_exit";;
            "msdn")        ye="mouse_down";;
            "msdr")        ye="mouse_dragged";;
            "msmv")        ye="mouse_moved";;
            "msup")        ye="mouse_up";;
            "mubhc")     ye="menu_bar_hidden_changed";;
            "muo")       ye="menu_opened";;
            "sch")          ye="space_changed";;
            "syswk")     ye="system_woke";;
            "wc")       ye="window_created";;
            "wdm")       ye="window_deminimized";;
            "wf")       ye="window_focused";;
            "wk")       ye="window_destroyed";;
            "wmi")       ye="window_minimized";;
            "wmv")       ye="window_moved";;
            "wrz")       ye="window_resized";;
            "wtc")       ye="window_title_changed";;
            *) echo "NO_MATCH" && exit 1;;
        esac
        for i in ${@:4}; do
            pre=${i%=*}
            post=${i#*=}
            if test "$pre" = "label" -o "$pre" = "n"; then
                yl="label=\"$post\""
            elif test "$pre" = "app" -o "$pre" = "a"; then
                ya="app=\"$post\""
            elif test "$pre" = "title" -o "$pre" = "t"; then
                yt="title=\"$post\""
            fi
        done
        eval "yabai -m signal --add event=$ye action=\"$action\" $yl $ya $yt"
	elif test "$1" = 'remove' -o "$1" = 'rm'; then
        eval "yabai -m signal --remove $2"
	elif test "$1" = 'list' -o "$1" = 'ls'; then
        eval "yabai -m signal --list"
	fi
else
    echo "linux todo..."
fi
