#!/usr/bin/env bash

# @param command
# @param value
# @param space_selection

test -z "${1-}" && exit 1

if is-mac; then
    case "$1" in
        "focus" | "fc")    ycmd="--focus" ;; # <SPACE_SEL>
        "create" | "nw")   ycmd="--create" ;;
        "destroy" | "rm")  ycmd="--destroy" ;;
        "move" | "mv")     ycmd="--move" ;; # <SPACE_SEL>                        Move position of the selected space to the position of the given space. The selected space and given space must both belong to the same display.
        "swap" | "sw")     ycmd="--swap" ;; # <SPACE_SEL>                        Swap the selected space with the given space. The selected space and given space must both belong to the same display.
        "display" | "dsp") ycmd="--display" ;; # <DISPLAY_SEL>                           Send the selected space to the given display.
        "balance" | "bl")  ycmd="--balance" ;; # Adjust the split ratios of the selected space so that all windows occupy the same area.
        "mirror" | "mir")  ycmd="--mirror" ;; # x-axis|y-axis                            Flip the tree of the selected space.
        "rotate" | "rot")  ycmd="--rotate" ;; # 90|180|270                               Rotate the tree of the selected space.
        "padding" | "pad") ycmd="--padding" ;; # abs|rel:<top>:<bottom>:<left>:<right>   Padding added at the sides of the selected space.
        "gap" | "gp")      ycmd="--gap" ;; # abs|rel:<gap>                               Size of the gap that separates windows on the selected space.
        "toggle" | "tg")   ycmd="--toggle" ;; # padding|gap|mission-control|show-desktop Toggle space setting on or off for the selected space.
        "layout" | "lt")   ycmd="--layout" ;; # bsp|stack|float                          Set the layout of the selected space.
        "label" | "lb")    ycmd="--label" ;; # [<LABEL>]                                 Label the selected space, allowing that label to be used as an alias in commands that take a SPACE_SEL parameter. If the command is called without an argument it will try to remove a previously assigned label.
        *) echo "NO_MATCH";;
    esac
    yabai -m space $ycmd $2
else
    echo "linux todo..."
fi
