#!/usr/bin/env sh

# USER CONFIGS

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# -----------------------------------
# ---       GLOBAL SETTINGS       ---
# -----------------------------------
wmc     fmsf    off
wmc     ffms    off
wmc     wp      second_child
wmc     wtm     off
wmc     ws      on
wmc     wop     on
wmc     wopd    0.0
wmc     waop    1.0
wmc     wnop    0.90
wmc     wb      off
wmc     wbw     12
wmc     wabc    0xff775759
wmc     wnbc    0xff555555
wmc     ifc     0xffd75f5f
wmc     sr      0.50
wmc     ab      off
wmc     msm     fn
wmc     ms1     move
wmc     ms2     resize

# ------------------------------------
# ---       general settings       ---
# ------------------------------------
wmc y    bsp
wmc pt    6
wmc pb    6
wmc pl    6
wmc pr    6
wmc gap   6
# wmc bar   off # all:28:0
# SPACEBAR_HEIGHT=$(spacebar -m config height)
wmc bar all:$(spacebar -m config height):0

# ---------------------------------------------
# ---       SPACES NAMING & BEHAVIOUR       ---
# ---------------------------------------------
wms n web 1
wms n dev 2
wms n social 3
wmc y bsp 3
wms n misc 4

# --------------------------
# ---       EVENTS       ---
# --------------------------

reset_all_events
# for i in $(seq 1 $(wme ls | jq 'length')); do wme rm 0; done # refresh event listeners

# # Refresh process widget when current window title changes
wme a wtc "osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'" \
    a="wtc" t="wtc" n="wtc"

# # Refresh spaces widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on display focus change
# yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on window resize
# yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh process widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# -------------------------
# ---       RULES       ---
# -------------------------

rules_reset_all
# for i in $(seq 1 $(wmr ls | jq 'length')); do wmr rm 0; done # refresh rules

# --- APPS NOT MANAGED ---
wmr a n="System Preferences" a="^System Preferences$"           mg=off
wmr a n="Finder"             a="^Finder$"                       mg=off
wmr a n="Hammerspoon"        a="^Hammerspoon$"                  mg=off
wmr a n="Colorpicker"        a="^Colorpicker$"                  mg=off
wmr a n="Activity Monitor"   a="^Activity Monitor$"             mg=off
wmr a n="App Store"          a="^App Store$"                    mg=off
wmr a n="Calculator"         a="^Calculator$"                   mg=off
wmr a n="Dictionary"         a="^Dictionary$"                   mg=off
wmr a n="The Unarchiver"     a="^The Unarchiver$"               mg=off
wmr a n="iTerm2 settings"    a="^iTerm2$" title="^Preferences"  mg=off
wmr a n="Transmission"       a="^Transmission$"                 mg=off
# yabai -m rule --add label="mpv" app="^mpv$" mg=off
# yabai -m rule --add label="Spark" app="^Spark$" title!="^Spark" mg=off
# yabai -m rule --add label="SSH Tunnel Manager" app="^SSH Tunnel Manager$" mg=off
# yabai -m rule --add label="ImageOptim" app="^ImageOptim$" mg=off
# yabai -m rule --add label="AppCleaner" app="^AppCleaner$" mg=off
# yabai -m rule --add label="Pika" app="^Pika$" mg=off

# --- APPS SPECIAL RULES ---
# yabai -m rule --add label="iTerm2" app="^iTerm2$" mg=off
# yabai -m rule --add label="Google Chrome" app="^Google Chrome$" space=^1
# yabai -m rule --add label="Firefox" app="^Firefox$" space=^1
# yabai -m rule --add label="Code" app="^Code$" space=^2
# yabai -m rule --add label="Sequel Ace" app="^Sequel Ace" space=^2
# yabai -m rule --add label="Slack" app="^Slack$" space=^3
# yabai -m rule --add label="Skype" app="^Skype$" space=^3

# -------------------------
# ---       OTHER       ---
# -------------------------

# configure to work with custom launcher under .local/bin
wmr a n="cust_launch" t='bin_custom_launcher' mg=off st=on y=above b=off

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &>/dev/null
limelight &>/dev/null &
