#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../../lib/_"

echo-header "SETTING UP RUST.."

if ! command_exists "cargo" ; then
    if is-mac; then
        brew_install rustup
    elif is-linux; then
        curl https://sh.rustup.rs -sSf | sh
    fi
    rustup-init -y

    # TODO: xdg...
    source $HOME/.cargo/env
fi
