#!/usr/bin/env bash

# MAKE SUBDIR INTO SUBMODULE
# B = https://github.com/molleweide/mollew-config.nvim.git

# target branch, target dir, new repo remote url
#
# examle
# NOTE: ```git_make_subdir_into_repo branchX some/dir git@github.com:git_user/new_repo.git```


TARGET_BRANCH=$1
TRG_SUB_DIR=$2
NEW_REPO_URL=$(git ls-remote --get-url $3)
ROOT_REPO_URL=$(git config --get remote.origin.url)
TMP_DIR=~/git-tmp-script-dir

echo "TRG_SUB_DIR = $TRG_SUB_DIR"; echo "NEW_REPO_URL = $NEW_REPO_URL"; echo "ROOT_REPO_URL = $ROOT_REPO_URL"

function extract_dir_into_repo() {
    git clone $ROOT_REPO_URL $TMP_DIR
    pushd $TMP_DIR > /dev/null 2>&1
    git checkout $TARGET_BRANCH
    git merge --strategy=ours master
    git checkout master
    git merge $TARGET_BRANCH
    git filter-branch --subdirectory-filter $TRG_SUB_DIR -- --all
    git remote remove origin
    git remote add origin $NEW_REPO_URL
    git push origin master
    popd > /dev/null 2>&1

    git rm -r $TRG_SUB_DIR
    rm -rf $TRG_SUB_DIR
    git submodule add $NEW_REPO_URL $TRG_SUB_DIR
    rm -rf $TMP_DIR
}

if [ ! -z $NEW_REPO_URL ]; then
    extract_dir_into_repo
else
    echo "New remote need to be created first. 😎" && exit 0
fi
