#!/usr/bin/env bash

FROMDIR=nvim
TEMPDIR=ntesiroarn
TODIR=nvim.config/molleweide

# git mv $FROMDIR $TEMPDIR
# mkdir -p $TEMPDIR
# git mv $TEMPDIR $TODIR

git submodule add https://github.com/molleweide/mollew-config.nvim.git "nvim.config/molleweide"
git submodule add https://github.com/molleweide/cheovim.git nvim

