#!/usr/bin/env bash

mctl="mctl"

if is-mac; then
  mctl="XX"
fi

# result=$(($condition ? "true-value" : "false-value"))


cat << EOF
;; VIM MODE
(defalias
  v00 next
  v01 mute
  v02 vold
  v03 volu
  v04 mctl
  v05 XX ;;-------------
  v06 XX
  v07 XX
  v08 XX
  v09 XX

  v10 XX
  v11 XX
  v12 brdn
  v13 brup
  v14 lp
  v15 pp ;;-------------
  v16 vold
  v17 volu
  v18 XX
  v19 XX

  v20 prev
  v21 pp
  v22 bldn
  v23 blup
  v24 mctl
  v25 lp  ;; ----------
  v26 mctl
  v27 pp
  v28 XX
  v29 XX

  v40 XX
  v41 tab
  v42 spc
  v43 XX  ;; second double space...
  v44 ret
  v45 XX
)

(deflayer VIM_MODE
  @v00 @v01 @v02 @v03 @v04      @v05 @v06 @v07 @v08 @v09
  @v10 @v11 @v12 @v13 @v14      @v15 @v16 @v17 @v18 @v19
  @v20 @v21 @v22 @v23 @v24      @v25 @v26 @v27 @v28 @v29
            @BQ  @v41      @v42           @v44 @BQ
)
EOF
