#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../../lib/_"

require_installer package-manager

function install_latest_ruby() { rvm install ruby --latest; }

function install_global_gem_hooks() {
    local destination="$HOME/.rvm/hooks/after_install_add_default_gems"
    # symlink_dotfile rvm/hooks/after_install_add_default_gems $destination
    chmod +x $destination
}

function install_rvm() {
    if [ ! -e ~/.rvm ]; then
        \curl -L https://get.rvm.io | bash -s -- --ignore-dotfiles
        export PATH="$HOME/.rvm/bin:$PATH"
        [ -f ~/.rvm/scripts/rvm ] && source ~/.rvm/scripts/rvm
        install_global_gem_hooks
        install_latest_ruby
    fi
}

function install_yard() { gem install yard; }

function bootstrap_rvm() {
    if use_rvm; then
        dotsay "@b@blue[[Installing RVM...]]"
        # setup_rvmrc
        install_rvm
        install_global_gem_hooks
        install_yard
    else
        dotsay "@b@yellow[[Skipping RVM, we aren't using it]]"
    fi
}

dotheader "Setting up Ruby..."
bootstrap_rvm
