#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../../lib/_"

function install_rust() {
  if ! command_exists "cargo" ; then

    if is_macos; then
      brew_install rustup
    elif is_linux; then
      curl https://sh.rustup.rs -sSf | sh
    fi

    rustup-init -y
    source $HOME/.cargo/env
  fi
}

dotheader "SETTING UP RUST.."

install_rust
