#!/usr/bin/env bash
# NAME: fk
# -------------------------------------------------------
# DESCRIPTION:
#  File browser custom func
# -------------------------------------------------------
ranger2 "$@"
