#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# HAMMERSPOON

require_installer package-manager
dotheader "Setting up HAMMERSPOON.."
brew_cask_install hammerspoon --appdir=/Applications

function setup_spoon_install() {
    local url="https://github.com/Hammerspoon/Spoons/raw/master/Spoons/SpoonInstall.spoon.zip"
    local destination=/tmp/SpoonInstall.spoon.zip
    local spoons_dir=$HOME/.hammerspoon/Spoons

    if [ ! -d "$spoons_dir/SpoonInstall.spoon" ]; then
        dotsay "@blue@b[[+ installing SpoonInstall.spoon ]]"

        wget -nv $url -O $destination
        unzip -d $spoons_dir $destination
    else
        dotsay "+ SpoonInstall.spoon already setup"
    fi
}

# modify function
#   $1 = git user
#   $2 = repo name
function setup_development_spoon_from_git_repo() {
    local name=$1
    local code_dir=$HOME/code
    local source_dir=$code_dir/$name.spoon

  # TODO: why symlink like this??
  local symlink_destination=$HOME/.hammerspoon/Spoons/$name.spoon

  mkdir -p "$code_dir"

  if [ ! -d $source_dir ]; then
      dotsay "@blue@b[[+ cloning development copy of $name.spoon ]]"
      git clone https://github.com/dbalatero/$name.spoon "$source_dir"
  else
      dotsay "+ $name.spoon dev copy already checked out"
  fi

  if [ ! -d $symlink_destination ]; then
      dotsay "@blue@b[[+ symlinking development copy of $name.spoon ]]"
      ln -s "$source_dir" "$symlink_destination"
  else
      dotsay "+ $name.spoon already installed to Hammerspoon"
  fi
}

if is_macos; then
    symlink_dotfile hammerspoon ~/.hammerspoon
    setup_spoon_install

  # refactor function so that i pass the git username first >> balatero VimMode
  #   so that i can install other spoons here
  setup_development_spoon_from_git_repo HyperKey
  setup_development_spoon_from_git_repo VimMode

  # >>> I have to check if it exists so i don't overwrite...
  # setup_development_kmonad_from_git_repo

  fi
