#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# KEYS

dotheader "Setting up keys..."

# mv to shared
function install_from_github() {
  local user=$1
  local name=$2
  local code_dir=$HOME/code
  local dest=$code_dir/$name

  mkdir -p "$code_dir"

  if [ ! -d $dest ]; then
    dotsay "+ cloning $dest"
    git clone https://github.com/molleweide/$name.git $dest
  else
    dotsay "+ $dest already exists"
  fi

}

if is_macos; then
  install_from_github molleweide "KE-complex_modifications"
  install_from_github molleweide "Karabiner-Elements"
fi
install_from_github molleweide "qmk_firmware"
# install_from_github molleweide "HyperKey" # replace balateros...
