#!/usr/bin/env bash

lib_dir="${BASH_SOURCE%/*}"

if [[ "$HAS_BEEN_SOURCED" != "yes" ]]; then
  source "$lib_dir/aptitude.sh"
  source "$lib_dir/config.sh"
  source "$lib_dir/custom-installers.sh"
  source "$lib_dir/git.sh"
  source "$lib_dir/homebrew.sh"
  source "$lib_dir/mac-app-store.sh"
  source "$lib_dir/os-detection.sh"
  source "$lib_dir/packages.sh"
  source "$lib_dir/require.sh"
  source "$lib_dir/stdout.sh"
  source "$lib_dir/symlinks.sh"

  HAS_BEEN_SOURCED="yes"
fi
