#!/usr/bin/env bash

local install_dir=$1
local alt_name=$2
local repo_url=$3
dotsay "@b@blue[[ @yellow$alt_name <- @magenta$repo_url]]"
mkdir -p $install_dir
if [ ! -d "$install_dir/$alt_name" ]; then
    dotsay "@b@green[[ Doesn't exist. Installing... \n]]"
    git clone $repo_url $alt_name
    pushd $install_dir/$alt_name > /dev/null 2>&1
    git submodule update --init --recursive
    popd > /dev/null 2>&1
else
    dotsay "@b@red[[ Already exists. \n]]"
fi
