#!/usr/bin/env bash

rvm $rvm_ruby_string do rvm gemset create global

rvm $rvm_ruby_string@global do gem install \
  awesome_print \
  bundler \
  cani \
  hirb \
  neovim \
  pry \
  tmuxinator \
  zeus
