#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../../lib/_"

dotheader "INSTALL PERSONAL REPOS/PROJECTS"

home_code_plugins=(

    $HOME/code/plugins

    # NOTE: use ssh instead of https
    "better-escape.nvim"    "git@github.com:jdhao/better-escape.vim.git"
    "cheovim.nvim"          "git@github.com:NTBBloodbath/cheovim.git"
    "colors.nvim"           "git@github.com:molleweide/colors.nvim.git"
    "lazy.nvim"             "git@github.com:molleweide/lazy.nvim.git"
    "lookup.nvim"           "git@github.com:molleweide/lookup.nvim.git"
    "neorg.nvim"            "git@github.com:molleweide/neorg.git"
    "plenary.nvim"          "git@github.com:molleweide/plenary.nvim.git"
    "which-key.nvim"        "git@github.com:folke/which-key.nvim.git"
)

# passing an array as argument is a bit quirky..
dotlib_clone_projects_from_array "${home_code_plugins[@]}"
# dotlib_clone_projects_from_array arstrst
