#!/usr/bin/env bash

# ============================================
# User config variables
# TODO: move all of these to dorothy/user/config/keyboard.bash
#       but first maybe just keep it inside of the kmonad config dir
#       before I move it into dorothy.

# Hardware name
USER_HARDWARE_KEYBOARD_LIST=(
	"ergo"
	"mbpro_x86"
	"mbair_m1"
	"mbpro_x86_ubuntu"
)

# Base file for hardware (same can be used for multiple)
declare -A DEFSRC_FILES=(
	[ergo]="defsrc_ergodox.kbd"
	[mbpro_x86]="defsrc_mbpro_swe.kbd"
	[mbair_m1]="defsrc_mbair.kbd"
	[mbpro_x86_ubuntu]="defsrc_mbpro_swe.kbd" # should this be its own file?
)

# Input string for hardware (same can be used for multiple)
declare -A DEFCFG_INPUT_STRINGS=(
	[ergo]="Ergodox EZ"
	[mbpro_x86]="Apple Internal Keyboard / Trackpad"
	[mbair_m1]="Apple Internal Keyboard / Trackpad"
	[mbpro_x86_ubuntu]="/dev/input/by-id/usb-Apple_Inc._Apple_Internal_Keyboard___Trackpad-event-kbd"
)
