#!/usr/bin/env bash

local -A keyboards=(

)

# input (iokit-name "Apple Internal Keyboard / Trackpad")
# input (iokit-name "Ergodox EZ")

# (defcfg
#   output (kext)
#   fallthrough true
# )


# -----------------------------------
# ---       muhammad script      ---
# -----------------------------------


# local -A keyboards=( [ergodox.sh]="<ergodox's product name"
#                      [mac-air.sh]="<product name>"
#                      [mac-pro.sh]="<product name>"
#                    )

# local input="(iokit-name \"${keyboards[$0]}\")"

# kmonad common-layout.kbd --fallthrough false --input "$input"

# -----------------------------------
# ---       muhammad common       ---
# -----------------------------------


# (defcfg
#   input (iokit-name "common layout") ;; just a placeholder
#   output (kext)
# )

# (defsrc
#   ;; your common layout
# )

# (deflayer baselayer
#   ;; your common layout
# )

# ;; etc...


# -------------------------------------------
# ---       muhammad script initial       ---
# -------------------------------------------

# #!/sbin/env zsh

# local defsrc="${K_DEFSRC:-$HOME/.config/kmonad/defsrc.kbd}"
# local baselayer="${K_BASELAYER:-$HOME/.config/kmonad/ansi_base.kbd}"

# # $1 => config
# # $2-$n => kmonad args
# exec kmonad =(cat "$defsrc" "$baselayer" "$1") "$@[2,-1]"

