#!/usr/bin/env bash

# (defcfg
#   output (kext)
#   fallthrough true
# )

if test -z ${1-}; then
    echo "No input specified. You need to specify what key board"
    echo "you want to run kmonad for."
    echo "(ergodox|macbook_air|macbook_pro_swe)"
    exit 1
fi

declare -A keyboards=(
    [ergodox]="Ergodox EZ"
    [macbook_air]="Apple Internal Keyboard / Trackpad"
    [macbook_pro_swe]="Apple Internal Keyboard / Trackpad"
)

echo "\$0 = $0"
echo "\$1 = $1"
echo

# input="(iokit-name \"${keyboards[$1]}\")"
input_str=${keyboards[$1]}
input="(iokit-name \"$input_str\")"


defsrc="${K_DEFSRC:-$HOME/.config/kmonad/defsrc.kbd}"
# common="${K_common:-$HOME/.config/kmonad/ansi_base.kbd}"
defsrc="./defsrc/defsrc_${1}.kbd"
common=./common/common.kbd

echo "input = $input"
echo "defsrc = $defsrc"
echo "common = $common"

# kmonad common-layout.kbd --fallthrough false --input "$input"

# -------------------------------------------
# ---       muhammad script initial       ---
# -------------------------------------------


# # $1 => config
# # $2-$n => kmonad args
# exec kmonad =(cat "$defsrc" "$baselayer" "$1") "$@[2,-1]"

# -----------------------------------
# ---       muhammad common       ---
# -----------------------------------

# (defcfg
#   input (iokit-name "common layout") ;; just a placeholder
#   output (kext)
# )

# (defsrc
#   ;; your common layout
# )

# (deflayer baselayer
#   ;; your common layout
# )

# ;; etc...

