#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  require_installer package-manager

  # uebersicht ui widgets
  # https://github.com/felixhageloh/uebersicht

  symlink_dotfile bin/custom_launcher ~/.local/bin/custom_launcher
fi
