#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# NOTE: CALENDAR

dotheader "SETTING UP CALENDAR.."

require_installer package-manager

if is_macos; then
    brew_install calcurse

    # elif is_linux; then
fi
