#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# CHAT

# TODO
#
# - slack
# - setup irssi?
# send sms from commandline/pc

dotheader "SETTING UP CHAT.."

require_installer package-manager

# function install_imessageclient() {
#     local install_path=$HOME/code/imessageclient
#     local git_src="https://github.com/CamHenlin/imessageclient.git"

#     if [ ! -d $install_path ]; then
#         git clone $git_src $install_path
#         pushd $install_path > /dev/null 2>&1
#         npm install
#         popd > /dev/null 2>&1
#     else
#         dotsay "+ $install_path already exists"
#     fi
# }

cargo install --git https://github.com/boxdot/gurk-rs

if is_macos; then
    brew_install irssi
    brew tap paul-nameless/homebrew-repo
    brew install tg
    # install_imessageclient # did not really work...
    # elif is_linux; then
fi
