#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# CHAT

# build signal messenger
# build telegram?

require_installer package-manager

brew_install irssi
symlink_dotfile irssi ~/.irssi

cargo install --git https://github.com/boxdot/gurk-rs

brew tap paul-nameless/homebrew-repo
brew install tg

