#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# CRYPTO

dotheader "SETTING UP CRYPTO.."

require_installer package-manager

if is_macos; then

    brew_install cointop

    # elif is_linux; then
fi
