#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# LAUNCH DAEMONS

if is_macos; then
  symlink_dotfile kmonad/local.kmonad.plist /Library/LaunchDaemons/local.kmonad.plist

# elif is_linux; then
fi

