#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

function configure_ctags() {
  symlink_dotfile ctags ~/.ctags
}

packages=(
  chromedriver
  ctags
  phantomjs
)

brew_install_all "${packages[@]}"
