#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

dotheader "Setting up devtools..."

brew_cask_install chromedriver
apt_install chromium-chromedriver

brew_cask_install alacritty

brew_install fd

brew_install postgres

brew_install coreutils

brew_install the_silver_searcher
apt_install silversearcher-ag

brew_install ripgrep
apt_install ripgrep

install_package sl
install_package wget

brew_install ack
apt_install ack-grep

brew_install gnu-tar
brew_install heroku/brew/heroku
brew_install hub
brew_install redis

heroku plugins:install heroku-repo
