#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function configure_ctags() {
  symlink_dotfile ctags.d ~/.ctags.d
}

dotheader "Setting up devtools..."

brew_cask_install chromedriver
apt_install chromium-chromedriver

brew_install fd

brew_install phantomjs
apt_install phantomjs

configure_ctags
