#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# Documents etc.
#
# todo
#   - pandoc
#     https://github.com/jgm/pandoc/blob/master/INSTALL.md
#
#   - zathura
#     https://ports.macports.org/port/zathura/summary

dotheader "SETTING UP DOCS..."

require_installer package-manager

if is_macos; then
  brew install pandoc
  # additional stuff
  # brew install librsvg python homebrew/cask/basictex

# elif is_linux; then
fi
