#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function install_kiex() {
  if [ ! -d $HOME/.kiex ]; then
    curl -sSL https://raw.githubusercontent.com/taylor/kiex/master/install | bash -s
  fi
}

dotheader "Setting up Elixir..."

brew_install erlang
install_kiex
