#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

function install_emacs() {
  if ! brew_is_tapped "d12frosted/emacs-plus"; then
    brew_tap d12frosted/emacs-plus
  fi

  brew_install emacs-plus --with-jansson
  ln -sf /usr/local/opt/emacs-plus/Emacs.app /Applications/Emacs.app
}

function install_doom_emacs() {
  if [ ! -d ~/.emacs.d ]; then
    dotsay "@blue@b[[+ Installing doom emacs to ~/.emacs.d]]"
    git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
    ~/.emacs.d/bin/doom install
  fi
}

function install_doom_dependencies() {
  brew_install shellcheck
}

symlink_dotfile doom.d ~/.doom.d
install_doom_dependencies
install_emacs
install_doom_emacs
