#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# FILE MANAGEMENT AND SEARCHING

require_installer package-manager

if is_macos; then

  # file managers
  brew_install ranger
  brew_install nnn
  brew_install lf
  brew_install fff
  # https://github.com/sayanarijit/xplr

  # search
  brew_install dmenu-mac

  # TODO: mv to bin
  symlink_dotfile bin/custom_launcher ~/.local/bin/custom_launcher

elif is_linux; then
  apt_install ranger
fi

symlink_dotfile ranger ~/.config/ranger

