#!/usr/bin/env bash

echo-header "SETTING UP FILE MANAGERS AND SEARCH.."

if is-mac; then
  brew install ranger
  brew install nnn
  brew install lf
  brew install fff
  # https://github.com/sayanarijit/xplr

  brew install dmenu-mac
fi
