#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

curl -sSL https://get.haskellstack.org/ | sh
# wget -qO- https://get.haskellstack.org/ | sh

stack upgrade
