#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if test ! $(which brew); then
  echo "Installing homebrew"
  ruby -e "$(curl -fsSL \
    https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew update
fi

packages=(
  ack
  emojify
  reattach-to-user-namespace
  sl
  the_silver_searcher
  wget
)

dotheader "Setting up Homebrew..."

brew_install_all "${packages[@]}"
