#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

dotheader "KEYBOARD"

require_installer package-manager

# https://github.com/kmonad/kmonad/issues/334

function install_ke_complex_mod() {
    dotlib_git_clone_recursive  \
        $HOME/code/tools        \
        "ke-complex-mods"       \
        git@github.com:molleweide/KE-complex_modifications.git
    }

function install_qmk_firmware() {
    dotlib_git_clone_recursive  \
        $HOME/code/firmware     \
        "qmk-firmware"          \
        git@github.com:molleweide/qmk_firmware.git
    }

function install_kmonad() {
    dotlib_git_clone_recursive  \
        $HOME/code/tools        \
        "kmonad"                \
        git@github.com:molleweide/kmonad.git

    pushd $install_dir > /dev/null 2>&1
    # echo "kmonad ? PWD = $PWD"
    if is_macos; then
        # https://github.com/kmonad/kmonad/blob/master/doc/installation.md#macos
        stack build \
            --flag kmonad:dext \
            --local-bin-path=/usr/local/bin/kmonad \
            --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
    fi
    popd > /dev/null 2>&1
}

########

# TODO: replace if/else with && / || to make things look better
is_macos && brew_cask_install karabiner-elements
is_macos && install_ke_complex_mod
install_qmk_firmware
install_kmonad
