#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

dotheader "KEYBOARD"

require_installer package-manager


function install_ke_complex_mod() {
    dotlib_git_clone_recursive  \
        $HOME/code/tools        \
        "ke-complex-mods"       \
        git@github.com:molleweide/KE-complex_modifications.git
    }

function install_qmk_firmware() {
    dotlib_git_clone_recursive  \
        $HOME/code/firmware     \
        "qmk-firmware"          \
        git@github.com:molleweide/qmk_firmware.git
    }

# https://github.com/kmonad/kmonad/blob/master/doc/installation.md#macos
# https://github.com/kmonad/kmonad/issues/334
# https://stackoverflow.com/questions/56437280/where-is-the-local-bin-path-of-my-stack-executables
function install_kmonad() {
    local install_dir=$HOME/code/tools
    dotlib_git_clone_recursive  \
        $install_dir            \
        "kmonad"                \
        git@github.com:molleweide/kmonad.git

    pushd $install_dir/kmonad > /dev/null 2>&1
    if is_macos; then
        # https://github.com/kmonad/kmonad/blob/master/doc/installation.md#macos
        stack build \
            --flag kmonad:dext \
            --local-bin-path=/usr/local/bin/kmonad \
            --extra-include-dirs=c_src/mac/Karabiner-VirtualHIDDevice/dist/include
    fi
    popd > /dev/null 2>&1
}

# NOTE: installers

is_macos && brew_cask_install karabiner-elements
is_macos && install_ke_complex_mod
install_qmk_firmware
install_kmonad
