#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# KTH

dotheader "Setting up keys..."

# mv to shared
function install_from_github() {
  local user=$1
  local name=$2
  local code_dir=$HOME/code
  local dest=$code_dir/$name

  mkdir -p "$code_dir"

  if [ ! -d $dest ]; then
    dotsay "+ cloning $dest"
    git clone https://github.com/$user/$name.git $dest
  else
    dotsay "+ $dest already exists"
  fi

}

install_from_github molleweide "hjajak_msc_thesis_overleaf"
install_from_github molleweide "msc_thesis"
