#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../../lib/_"

require_installer package-manager

# https://www.haskell.org/ghcup/
# https://gitlab.haskell.org/haskell/ghcup-hs#manual-install

dotheader "SETTING UP HASKELL.."

if is_macos; then

  # # GHCUP
  # if test ! $(which ghc); then
  #     curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
  # fi
  brew_install ghc

  # STACK
  # wget -qO- https://get.haskellstack.org/ | sh
  if test ! $(which stack); then
      curl -sSL https://get.haskellstack.org/ | sh
  fi
  stack upgrade

  stack install yesod-bin --install-ghc
  # elif is_linux; then
fi

