#!/usr/bin/env bash

echo-header "SETTING UP LUA.."

brew install lua
brew install luarocks

luarocks install loop
luarocks install dkjson
luarocks install inspect
luarocks install --server=http://luarocks.org/dev lua-lsp
luarocks install luacheck
luarocks install lcf

