#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  require_installer package-manager

  mas_app_id() {
    local name=$1

    mas search "$name" | awk '{ print $1 }'
  }

  mas_install() {
    local name=$1
    local app_id=$2

    if ! mas list | grep -q $app_id; then
      dotsay "@b@yellow[[+ installing $name]]"
      mas install $app_id
    else
      dotsay "+ $name already installed"
    fi
  }

  mas_ensure_signed_in() {
    if ! mas account >/dev/null 2>&1; then
      printf "What is your Apple ID? > "
      read apple_id
      mas signin $apple_id
    else
      dotsay "@b@blue[[Currently signed into the App Store as $(mas account)]]"
    fi
  }

  install_xcode() {
    mas_install "Xcode" 497799835
    sudo xcodebuild -license accept
  }


  dotheader "Setting up Mac App Store..."

  brew_install mas
  mas_ensure_signed_in

  mas_install "Amphetamine" 937984704
  mas_install "Boom 2" 948176063
  mas_install "Capo 3" 696977615
  mas_install "Fantastical 2" 975937182
  mas_install "GarageBand" 682658836
  mas_install "Logic Pro X" 634148309
  mas_install "Markoff" 1084713122
  mas_install "Paste 2" 967805235
  mas_install "Pixelmator" 407963104
  mas_install "Slack" 803453959
  mas_install "Timeout" 402592703
  install_xcode
fi
