#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  if dotfiles_config_set "no-mac-apps"; then
    dotsay "@b@blue[[Skipping Mac app store, no-mac-apps set]]"
  else
    require_installer package-manager

    dotheader "Setting up Mac App Store..."

    brew_install mas
    mas_ensure_signed_in

    # mas_install "Amphetamine" 937984704
    # mas_install "Blackmagic Disk Speed Test" 425264550
    # mas_install "Boom 2" 948176063
    # mas_install "Capo 3" 696977615
    # mas_install "Fantastical 2" 975937182
    # mas_install "GarageBand" 682658836
    # mas_install "Logic Pro X" 634148309
    # mas_install "Markoff" 1084713122
    # mas_install "Paste 2" 967805235
    # mas_install "Pixelmator" 407963104
    # mas_install "Slack" 803453959
    # mas_install "Timeout" 402592703
    # mas_install "The Unarchiver" 425424353
  fi
fi
