#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"


dotheader "Setting up Hammerspoon..."


function install_personal_master_repos() {
  local name=$1
  local code_dir=$HOME/code
  local source_dir=$code_dir/$name

  mkdir -p "$code_dir"

  if [ ! -d $source_dir ]; then
    dotsay "+ cloning $source_dir"
    # dotsay "@blue@b[[+ cloning development copy of $name.spoon ]]"
    git clone https://github.com/molleweide/$name.git "$source_dir"
  else
    dotsay "+ $source_dir already exists"
  fi

}

install_personal_master_repos keys
install_personal_master_repos vim
install_personal_master_repos kth
install_personal_master_repos apps
install_personal_master_repos wp
