#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# dont use this file

dotheader "Setting up personal projects..."


function install_personal_master_repos() {
  local name=$1
  local code_dir=$HOME/code
  local source_dir=$code_dir/$name

  mkdir -p "$code_dir"

  if [ ! -d $source_dir ]; then
    dotsay "+ cloning $source_dir"
    git clone https://github.com/molleweide/$name.git "$source_dir"
    pushd $source_dir
    git submodule update --init --recursive
    popd
  else
    dotsay "+ $source_dir already exists"
  fi

}

# install_personal_master_repos keys
# install_personal_master_repos vim
# install_personal_master_repos kth
# install_personal_master_repos apps
# install_personal_master_repos wp
