#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# MULTIMEDIA

dotheader "SETTING UP MULTIMEDIA.."

require_installer package-manager

if is_macos; then

  # audio
  brew_install spotify-tui

  # video
  brew_cask_install mpv
  brew_install mps-youtube

fi
