#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

if is_macos; then
  brew_install ranger

elif is_linux; then
  apt_install ranger
fi

symlink_dotfile ranger ~/.config/ranger

