#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# NEOMUTT

# refactor this into `code_install <args>`
function install_muttwizard() {
  local gith="https://github.com"
  local proj="LukeSmithxyz/mutt-wizard"
  local dest=$HOME/code/mutt-wizard

  if [ ! -d $dest ]; then
    git clone $gith/$proj $dest
    pushd $dest> /dev/null 2>&1
    sudo make install
    popd $dest> /dev/null 2>&1
  fi


}

if is_macos; then
  require_installer package-manager

  # default macos dependencies
  brew install neomutt curl isync msmtp pass

  # Optional Dependencies
  #    pam-gnupg - Automatically logs you into your GPG key on login so you will never need to input your password once logged on to your system. Check the repo and directions out here.
  #    lynx - view HTML email in neomutt.
  #    notmuch - index and search mail. Install it and run notmuch setup, tell it that your mail is in ~/.local/share/mail/ (although mw will do this automatically if you haven't set notmuch up before). You can run it in mutt with ctrl-f. Run notmuch new to process new mail.
  #    abook - a terminal-based address book. Pressing tab while typing an address to send mail to will suggest contacts that are in your abook.
  #    urlview - outputs urls in mail to browser.
  #    cronie - (or any other major cronjob manager) to set up automatic mail syncing.
  #    mpop - If you want to use POP protocol instead of IMAP.
  #
  # additional packages
  # eg. my personal mail uses pop but that doesn't seem to be as common as
  # imap which is default.

  brew install mpop

  install_muttwizard
  fi

