#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer fonts
require_installer ruby
require_installer python

function install_neovim() {
  if ! brew tap | grep -q neovim; then
    brew tap neovim/neovim
  fi

  brew_install neovim --HEAD
}

function setup_neovim_config() {
  mkdir -p ~/.config
  symlink_dotfile nvim ~/.config/nvim
}

function ensure_plugin_directory() {
  mkdir -p ~/.local/share/nvim/plugged
}

function install_neovim_plugins() {
  dotsay "@b@blue[[+ Installing nvim plugins]]"
  nvim +PlugInstall +qall
}

dotheader "Setting up Neovim..."

install_neovim
setup_neovim_config
ensure_plugin_directory
install_neovim_plugins
