#!/usr/bin/env bash

echo-header "Setting up NEOVIM..."

# INSTALL LUA LANGUAGE SERVER
brew install ninja
lspdir="$HOME/.local/nvim/lsp"
location="$lspdir/lua-language-server"
if [ ! -d "$location" ]; then
    echo-color "@b@blue[[+ Installing sumneko Lua LSP]]"
    mkdir -p "$lspdir"
    git clone https://github.com/sumneko/lua-language-server "$location"
    cd "$location" || exit 1
    git checkout tags/1.14.2 -b install-1.14.2
    git submodule update --init --recursive
    cd 3rd/luamake || exit 1
    ninja -f ninja/macos.ninja
    cd ../.. || exit 1
    ./3rd/luamake/luamake rebuild
fi

npm install -g bash-language-server
rvm default do gem install neovim
if ! brew tap | grep -q "neovim/neovim"; then
    brew tap neovim/neovim
fi
brew install tree-sitter --HEAD
brew install luajit --HEAD
brew install neovim --HEAD
npm install -g tern
npm install -g neovim
npm install -g vim-node-rpc
mkdir -p ~/.local/share/nvim/plugged
echo-color "@b@blue[[+ Installing nvim plugins]]"
pyenv activate py2neovim
nvim +PlugInstall +qall
if ! command-exists "proximity-sort" ; then
    cargo install --force proximity-sort
fi
brew install bat
