#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

dotheader "Setting up Hammerspoon..."
brew_cask_install hammerspoon --appdir=/Applications

function setup_vim_mode_spoon_from_local() {
  local code_dir=$HOME/code
  local source_dir=$code_dir/VimMode.spoon
  local symlink_destination=$HOME/.hammerspoon/Spoons/VimMode.spoon

  mkdir -p "$code_dir"

  if [ ! -d $source_dir ]; then
    dotsay "@blue@b[[+ cloning development copy of VimMode.spoon ]]"
    git clone https://github.com/dbalatero/VimMode.spoon "$source_dir"
  else
    dotsay "+ VimMode.spoon dev copy already checked out"
  fi

  if [ -f $symlink_destination ]; then
    dotsay "@blue@b[[+ symlinking development copy of VimMode.spoon ]]"
    ln -s "$source_dir" "$symlink_destination"
  else
    dotsay "+ VimMode.spoon already installed to Hammerspoon"
  fi
}

function fetch_axuielement_library() {
  local filename=axuielement-v0.7.1.tar.gz
  local save_dir=/tmp
  local url=https://github.com/asmagill/hs._asm.axuielement/raw/master/$filename
  local destination=~/.hammerspoon/hs/_asm

  if [ ! -d $destination ]; then
    dotsay "@blue@b[[+ symlinking development copy of VimMode.spoon ]]"

    wget -nv $url -O $save_dir/$filename

    cd $save_dir && tar zxvf $filename
    mkdir -p ~/.hammerspoon/hs
    mv $save_dir/hs/_asm $destination
  else
    dotsay "+ hs._asm.axuielement already installed... skipping"
  fi
}

symlink_dotfile bin/dnd-toggle ~/.local/bin/dnd-toggle

brew_cask_install 1password-cli
brew_cask_install tunnelblick
brew_install lua
brew_install luarocks

brew_cask_install karabiner-elements
symlink_dotfile karabiner ~/.config/karabiner

luarocks install --server=http://luarocks.org/dev lua-lsp
luarocks install luacheck
luarocks install lcf

symlink_dotfile hammerspoon ~/.hammerspoon
setup_vim_mode_spoon_from_local
fetch_axuielement_library
