#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

dotheader "Setting up Hammerspoon..."
brew_cask_install hammerspoon --appdir=/Applications

symlink_dotfile hammerspoon ~/.hammerspoon
