#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  if test ! $(which brew); then
    echo "Installing homebrew"

    ruby -e "$(curl -fsSL \
      https://raw.githubusercontent.com/Homebrew/install/master/install)"

    brew update
  fi

  packages=(
    emojify
    reattach-to-user-namespace
  )

  dotheader "Setting up Homebrew..."

  brew_install_all "${packages[@]}"
elif is_linux; then
  apt_install aptitude
fi

brew_install ack
apt_install ack-grep

brew_install the_silver_searcher
brew_install silversearcher-ag

install_package sl
install_package wget
