#!/usr/bin/env bash

if is-mac; then

    echo-header "Setting up Homebrew..."

    if test ! $(which brew); then
        echo-green "Installing homebrew"
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew update
    fi

    if [ $(which openssl) == "/usr/local/opt/openssl/bin/openssl" ]; then
        echo-verbose "+ Already forced OpenSSL to Homebrew's version"
    else
        echo-bold "+ Installing OpenSSL from Homebrew..."
        brew install openssl
        brew link openssl --force
    fi
fi

# buildtools=(
#     base-devel
#     make
#     cmake
#     build-essential
#     libssl-dev
#     zlib1g-dev
#     libbz2-dev
#     libreadline-dev
#     libsqlite3-dev
#     wget
#     curl
#     llvm
#     libncurses5-dev
#     xz-utils
#     tk-dev
# )

# for package in "${buildtools[@]}"; do
#     apt_install "$package"
# done
