#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

dotheader "INSTALL PERSONAL REPOS/PROJECTS"

# NOTE: duplicates with other installers might occur but that is not a problem
# since the script cannot overwrite any already existing repos.
#
# add
#   - work
#   - kth
#

##################################################################
##################################################################

# NOTE: NOTES
home_notes=(
    $HOME/notes
    "notes"    "git@github.com:"
)
# dotlib_clone_projects_from_array "${home_notes[@]}"

##################################################################
##################################################################

# NOTE: PLUGINS

home_code_plugins=(
    $HOME/code/plugins
    "better-escape.nvim"    "git@github.com:jdhao/better-escape.vim.git"
    "cheovim.nvim"          "git@github.com:NTBBloodbath/cheovim.git"
    "colors.nvim"           "git@github.com:molleweide/colors.nvim.git"
    "lazy.nvim"             "git@github.com:molleweide/lazy.nvim.git"
    "lookup.nvim"           "git@github.com:molleweide/lookup.nvim.git"
    "neorg.nvim"            "git@github.com:molleweide/neorg.git"
    "plenary.nvim"          "git@github.com:molleweide/plenary.nvim.git"
    "which-key.nvim"        "git@github.com:folke/which-key.nvim.git"
)
dotlib_clone_projects_from_array "${home_code_plugins[@]}"

##################################################################
##################################################################

# NOTE: APPS

home_code_apps=(
)
# dotlib_clone_projects_from_array "${home_code_apps[@]}"

##################################################################
##################################################################

# NOTE: FIRMWARES

home_code_firmware=(
)
# dotlib_clone_projects_from_array "${home_code_firmware[@]}"

##################################################################
##################################################################

# NOTE: LEARN

home_code_learn=(
)
# dotlib_clone_projects_from_array "${home_code_learn[@]}"


# NOTE: FIRMWARES

home_code_firmware=(
)
# dotlib_clone_projects_from_array "${home_code_firmware[@]}"

##################################################################
##################################################################

# NOTE: CONFIGS

home_code_learn=(
    $HOME/code/configs
    "dot-bot-PYTHON"    "git@github.com:anishathalye/dotbot.git"
    "dot-chezmoi-GO"    "git@github.com:twpayne/chezmoi.git"
    "dot-elenapan"      "git@github.com:elenapan/dotfiles.git"
    "dot-holman"        "git@github.com:holman/dotfiles.git"
    "dot-homesick-RUBY" "git@github.com:technicalpickles/homesick.git"
    "dot-jessfraz"      "git@github.com:jessfraz/dotfiles.git"
    "dot-lewagon"       "git@github.com:lewagon/dotfiles.git"
    "dot-pualirish"     "git@github.com:paulirish/dotfiles.git"
    "dot-skwp"          "git@github.com:skwp/dotfiles.git"
    "dot-thoughtbot"    "git@github.com:thoughtbot/dotfiles.git"
    "dot-voidrice"      "git@github.com:LukeSmithxyz/voidrice.git"
    "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
    "rcm"               "git@github.com:thoughtbot/rcm.git"
    "tmux-gpakosz"      "git@github.com:gpakosz/.tmux.git"
)
# dotlib_clone_projects_from_array "${home_code_configs[@]}"

##################################################################
##################################################################

# NOTE: MACOS: UBERSICHT

home_code_ubersicht=(
    # $HOME/code/configs
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_code_ubersicht[@]}"

##################################################################
##################################################################

# NOTE: CODE BIN SCRIPTS

home_code_bin=(
    # $HOME/code/misc
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_code_bin[@]}"

##################################################################
##################################################################

# NOTE: CODE MISC

home_code_misc=(
    # $HOME/code/misc
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_code_misc[@]}"

