#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

dotheader "INSTALL PERSONAL REPOS/PROJECTS"

# NOTE: NOTES
home_notes=( $HOME/notes "notes" "git@github.com:molleweide/notes.git" )
dotlib_clone_projects_from_array "${home_notes[@]}"

##################################################################

# NOTE: PROJECTS

home_projects=(
    $HOME/projects
    # $HOME/code/projects
    # ""   ""
)
# dotlib_clone_projects_from_array "${home_projects[@]}"

##################################################################

# NOTE: PLUGINS

home_code_plugins=(
    $HOME/code/plugins
    "better-escape.nvim"    "git@github.com:jdhao/better-escape.vim.git"
    "cheovim.nvim"          "git@github.com:NTBBloodbath/cheovim.git"
    "colors.nvim"           "git@github.com:molleweide/colors.nvim.git"
    "lazy.nvim"             "git@github.com:molleweide/lazy.nvim.git"
    "lookup.nvim"           "git@github.com:molleweide/lookup.nvim.git"
    "neorg.nvim"            "git@github.com:molleweide/neorg.git"
    "plenary.nvim"          "git@github.com:molleweide/plenary.nvim.git"
    "which-key.nvim"        "git@github.com:folke/which-key.nvim.git"
)
dotlib_clone_projects_from_array "${home_code_plugins[@]}"

##################################################################

# NOTE: APPS

home_code_apps=(
    $HOME/code/apps
)
# dotlib_clone_projects_from_array "${home_code_apps[@]}"

##################################################################

# NOTE: FIRMWARES

home_code_firmware=(
    $HOME/code/firmware
)
# dotlib_clone_projects_from_array "${home_code_firmware[@]}"

##################################################################

# NOTE: LEARN

home_code_learn=(
    $HOME/code/learn
)
# dotlib_clone_projects_from_array "${home_code_learn[@]}"

##################################################################

# NOTE: CONFIGS

home_code_configs=(
    $HOME/code/configs
    "dot-bergholmm"         "https://github.com/bergholmm/dotfiles.git"
    "dot-bot-PYTHON"        "git@github.com:anishathalye/dotbot.git"
    "dot-brodieroberts"     "https://github.com/BrodieRobertson/dotfiles.git"
    "dot-ch99q"             "https://github.com/ch99q/dotfiles.git"
    "dot-chezmoi-GO"        "git@github.com:twpayne/chezmoi.git"
    "dot-dbalatero"         "git@github.com:dbalatero/dotfiles.git"
    "dot-elenapan"          "git@github.com:elenapan/dotfiles.git"
    "dot-fehawen"           "git@github.com:fehawen/dotfiles.git"
    "dot-glacambre"         "https://github.com/glacambre/.dotfiles.git"
    "dot-holman"            "git@github.com:holman/dotfiles.git"
    "dot-homesick-RUBY"     "git@github.com:technicalpickles/homesick.git"
    "dot-jdevlieghere"      "https://github.com/JDevlieghere/dotfiles.git"
    "dot-jessfraz"          "git@github.com:jessfraz/dotfiles.git"
    "dot-lambdalieuse"      "https://github.com/lambdalisue/dotfiles.git"
    "dot-lewagon"           "git@github.com:lewagon/dotfiles.git"
    "dot-mattmc3"           "git@github.com:mattmc3/dotfiles.git"
    "dot-pualirish"         "git@github.com:paulirish/dotfiles.git"
    "dot-skwp"              "git@github.com:skwp/dotfiles.git"
    "dot-thomason"          "https://github.com/wbthomason/dotfiles.git"
    "dot-thoughtbot"        "git@github.com:thoughtbot/dotfiles.git"
    "dot-tjdevrie"          "https://github.com/tjdevries/config_manager.git"
    "dot-twitch-streamers"  "https://github.com/awesome-streamers/awesome-streamerrc.git"
    "dot-voidrice"          "git@github.com:LukeSmithxyz/voidrice.git"
    "dot-xero"              "git@github.com:xero/dotfiles.git"
    "dotfiles-mbynes"       "git@github.com:mathiasbynens/dotfiles.git"
    "rcm"                   "git@github.com:thoughtbot/rcm.git"
    "tmux-gpakosz"          "git@github.com:gpakosz/.tmux.git"
)
dotlib_clone_projects_from_array "${home_code_configs[@]}"

##################################################################

# NOTE: MACOS: UBERSICHT

home_code_ubersicht=(
    $HOME/code/ubersicht
    # $HOME/code/configs
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_code_ubersicht[@]}"

##################################################################

# NOTE: CODE BIN SCRIPTS

home_code_bin=(
    $HOME/code/bin
    # $HOME/code/misc
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_code_bin[@]}"

##################################################################

# NOTE: CODE MISC

home_code_misc=(
    $HOME/code/misc
    # $HOME/code/misc
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_code_misc[@]}"

##################################################################

# NOTE: work

home_work=(
    $HOME/work
    # $HOME/work
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_work[@]}"


##################################################################

# NOTE: KTH

home_kth=(
    $HOME/KTH
    # $HOME/KTH
    # "dotfiles-mbynes"   "git@github.com:mathiasbynens/dotfiles.git"
)
# dotlib_clone_projects_from_array "${home_kth[@]}"
