#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# TODO

# where to put REAPER map?
#   clone my reaper
#   cask install Reaper
#   - https://formulae.brew.sh/cask/reaper#default
#   - https://github.com/Homebrew/homebrew-cask/blob/master/Casks/reaper.rb
#   - https://github.com/Homebrew/homebrew-cask/blob/master/USAGE.md
#     read options about choosing install dir
#   - https://stackoverflow.com/questions/23484883/changing-homebrew-cask-installation-directories

REAPER_DIR=~/REAPER

function get_current_reaper_version() {
  rppv=$(brew info reaper | head -n 1)
  if [[ $rppv =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
    rppv=${BASH_REMATCH[0]}
  else
    echo "Something is wrong with checking reaper version" >&2
    rppv="ERROR" # should use bool!!
  fi
  echo  "reaper-$rppv"
}

function install_reaper_linux() {
  echo "reaper linux install not done yet."
}

function install_reaper_mac() {
  tmp_dir=~/temp_dir
  read -r -p "Do you want to install portable Cockos Reaper to $REAPER_DIR/app? [y|N] " response

  if [[ $response =~ (y|yes|Y) ]]; then
    rpp_latest=$(get_current_reaper_version)
    REAPER_INSTALL_DIR="$REAPER_DIR/app/$rpp_latest"
    if [ ! -d $REAPER_INSTALL_DIR ]; then
      echo "This $REAPER_INSTALL_DIR does not exist"

      mkdir -p $REAPER_INSTALL_DIR

      # # install reaper to target dir
      # brew cask install reaper --appdir=$install_dir --force

      # # clone git to tmp dir and move it to reaper
      # # install dir manually
      # git clone --recurse-submodules https://github.com/molleweide/reaper-app-config.git $tmp_dir
      # mv $tmp_dir/.git $install_dir/.git
      # rm -r $tmp_dir # be careful

      # # navigate to reaper install dir and restore git
      # pushd $install_dir > /dev/null 2>&1
      # echo "inside: $PWD ; now we reset to get all files back."
      # git reset --hard HEAD
      # popd > /dev/null 2>&1

    else
      dotsay ">>> Latest version of reaper is installed to $REAPER_INSTALL_DIR"
    fi
  fi
}

function install_reaper() {
  if is_macos; then
    install_reaper_mac
  else
    install_reaper_linux
  fi
}

install_reaper
