#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager
require_installer node

function install_spacemacs() {
  if [ ! -d ~/.emacs.d ]; then
    dotsay "@b@blue[[+ Installing spacemacs...]]"

    git clone git@github.com:syl20bnr/spacemacs.git ~/.emacs.d
    cd ~/.emacs.d && git checkout develop
  else
    dotsay "+ spacemacs is already installed"
  fi
}

function install_emacs() {
  if [ ! -d /Applications/Emacs.app ]; then
    dotsay "@b@blue[[+ Installing Emacs 26 from HEAD...]]"

    brew_tap d12frosted/emacs-plus

    local formula=$(brew formula emacs-plus)
    local temp_output="/tmp/emacs-plus.rb"

    cat "$formula" |
      sed "s/^.*emacs\.git.*$/    url \"https:\/\/github.com\/emacs-mirror\/emacs.git\", branch: \"emacs-26\"/g" > "$temp_output"

    mv "$temp_output" "$formula"

    brew install emacs-plus --HEAD && brew linkapps emacs-plus
  else
    dotsay "+ Emacs 26 is already installed"
  fi
}

function install_npm_package() {
  local name=$1

  nvm use system

  if command_exists "$name" ; then
    dotsay "+ $name already installed"
  else
    dotsay "@b@blue[[Installing $name...]]"
    npm install -g "$name"
  fi
}

brew_install wakatime-cli
brew_install coreutils
brew_install ctags
rehash
brew_install global --with-ctags

install_npm_package tern
install_npm_package vmd

install_spacemacs
install_emacs
symlink_dotfile spacemacs.d ~/.spacemacs.d

ln -sf "$HOME/Library/Application Support/Dash/DocSets" $HOME/.docsets
