#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# SYMLINK CONFIGS

mkdir -p ~/.config

symlink_dotfile alacritty.yml ~/.alacritty.yml
symlink_dotfile mostrc ~/.mostrc

symlink_dotfile skhdrc ~/.skhdrc
symlink_dotfile yabairc ~/.yabairc

symlink_dotfile zshrc ~/.zshrc
symlink_dotfile zsh ~/.zsh
symlink_dotfile zsh/zshenv ~/.zshenv

# GIT
symlink_dotfile git/gitattributes ~/.gitattributes
symlink_dotfile git/gitconfig ~/.gitconfig
symlink_dotfile git/gitignore ~/.gitignore
symlink_dotfile git/gitmessage ~/.gitmessage

# RUBY
symlink_dotfile rvmrc ~/.rvmrc
symlink_dotfile gemrc ~/.gemrc
symlink_dotfile irb/pryrc ~/.pryrc
symlink_dotfile irb/unescaped_colors.rb ~/.unescaped_colors.rb
symlink_dotfile irb/escaped_colors.rb ~/.escaped_colors.rb
symlink_dotfile irb/aprc ~/.aprc

# TMUX
symlink_dotfile tmux.conf ~/.tmux.conf
symlink_dotfile tmux.osx.conf ~/.tmux.osx.conf
symlink_dotfile tmux ~/.tmux
symlink_dotfile tmuxinator ~/.tmuxinator
symlink_dotfile tmux/tmuxcolors-dbalatero-base16.conf \
    ~/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf

symlink_dotfile bat/config ~/.config/bat/config

# NVIM
symlink_dotfile nvim ~/.config/nvim # cheovim config manager
symlink_dotfile molleweide-nvim ~/.config/molleweide-nvim
symlink_dotfile doom-nvim ~/.config/doom-nvim

# CHAT
symlink_dotfile irssi ~/.irssi

# TODO: fix all of these > mv to bin repo
mkdir -p ~/.local/bin
symlink_dotfile bin/git ~/.local/bin/git
symlink_dotfile bin/tmux-airline ~/.local/bin/tmux-airline
symlink_dotfile bin/custom_launcher ~/.local/bin/custom_launcher
