#!/usr/bin/env bash

# source "${BASH_SOURCE%/*}/shared.sh"

source "${BASH_SOURCE%/*}/../utils/_"

# SYMLINK CONFIGS

# verbose remove already existing link and replace with new
# ln -Ffsv

# symlink_dotfile home/.zprofile ~/.zprofile
# symlink_dotfile home/.config ~/.config
dot_symlink home/.local/bin ~/.local/bin
# symlink_dotfile home/.hammerspoon ~/.hammerspoon

# # RVM
# symlink_dotfile home/.rvm/hooks/after_cd_nvm ~/.rvm/hooks/after_cd_nvm
# symlink_dotfile home/.rvm/hooks/after_install_add_default_gems \
#     ~/.rvm/hooks/after_install_add_default_gems










# symlink_dotfile alacritty.yml ~/.alacritty.yml
# symlink_dotfile mostrc ~/.mostrc
# symlink_dotfile skhdrc ~/.skhdrc
# symlink_dotfile yabairc ~/.yabairc

# symlink_dotfile zshrc ~/.zshrc
# symlink_dotfile zsh ~/.zsh
# symlink_dotfile zsh/zshenv ~/.zshenv

# # GIT
# symlink_dotfile git/gitattributes ~/.gitattributes
# symlink_dotfile git/gitconfig ~/.gitconfig
# symlink_dotfile git/gitignore ~/.gitignore
# symlink_dotfile git/gitmessage ~/.gitmessage

# # RUBY
# symlink_dotfile rvmrc ~/.rvmrc
# symlink_dotfile gemrc ~/.gemrc
# symlink_dotfile irb/pryrc ~/.pryrc
# symlink_dotfile irb/unescaped_colors.rb ~/.unescaped_colors.rb
# symlink_dotfile irb/escaped_colors.rb ~/.escaped_colors.rb
# symlink_dotfile irb/aprc ~/.aprc

# # TMUX
# symlink_dotfile tmux.conf ~/.tmux.conf
# symlink_dotfile tmux.osx.conf ~/.tmux.osx.conf
# symlink_dotfile tmux ~/.tmux
# symlink_dotfile tmuxinator ~/.tmuxinator
# symlink_dotfile tmux/tmuxcolors-dbalatero-base16.conf \
#     ~/.tmux/plugins/base16-tmux/tmuxcolors-dbalatero-base16.conf

# symlink_dotfile bat/config ~/.config/bat/config

# # NVIM
# symlink_dotfile nvim ~/.config/nvim # cheovim config manager
# symlink_dotfile molleweide-nvim ~/.config/molleweide-nvim
# symlink_dotfile doom-nvim ~/.config/doom-nvim

# # VSCODE
# VSCODE_CONFIG_DIR="$HOME/Library/Application Support/Code/User"
# mkdir -p "$VSCODE_CONFIG_DIR"
# symlink_dotfile vscode/keybindings.json "$VSCODE_CONFIG_DIR/keybindings.json"
# symlink_dotfile vscode/settings.json "$VSCODE_CONFIG_DIR/settings.json"

# symlink_dotfile karabiner ~/.config/karabiner


# # CHAT
# symlink_dotfile irssi ~/.irssi

# symlink_dotfile hammerspoon ~/.hammerspoon

# symlink_dotfile scimrc ~/.config/sc-im/scimrc

