#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# TERMINAL

if is_macos; then
  require_installer package-manager
  brew_cask_install alacritty
  brew_install most # man page colorized
fi

symlink_dotfile alacritty.yml ~/.alacritty.yml
symlink_dotfile .mostrc ~/.mostrc

# get fucking bent, Catalina
xattr -r -d com.apple.quarantine /Applications/Alacritty.app

