#!/usr/bin/env bash

echo-header "SETTING UP TERMINAL.."

if is-mac; then

    brew install --cask alacritty
    brew install --cask kitty

    if command-exists "alacritty"; then
        echo-color "@blue@b[[+ Installing Alacritty terminfo ]]"
        git clone https://github.com/alacritty/alacritty.git /tmp/alacritty
        cd /tmp/alacritty
        sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
        cd $HOME
        rm -fr /tmp/alacritty
    fi

    # get fucking bent, Catalina | what is this??
    xattr -r -d com.apple.quarantine /Applications/Alacritty.app
fi

