#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# TERMINAL

require_installer package-manager

if is_macos; then
  brew_cask_install alacritty
  brew_install most # man page colorized
elif is_linux; then
  sudo add-apt-repository ppa:aslatter/ppa
  sudo apt install alacritty
fi


function install_terminfo() {
  if ! command_exists "alacritty"; then
    git clone https://github.com/alacritty/alacritty.git /tmp/alacritty
    cd /tmp/alacritty

    dotsay "@b@blue[[+ Installing Alacritty terminfo]]"
    sudo tic -xe alacritty,alacritty-direct extra/alacritty.info

    cd $HOME
    rm -fr /tmp/alacritty
  fi
}

install_terminfo
symlink_dotfile alacritty.yml ~/.alacritty.yml
symlink_dotfile mostrc ~/.mostrc

# get fucking bent, Catalina
xattr -r -d com.apple.quarantine /Applications/Alacritty.app

