#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

WALLPAPER="$(dotfiles_location)/wallpaper/wallpaper.jpg"

osascript -e \
  "tell application \"Finder\" to set desktop picture to POSIX file \"$WALLPAPER\""
