#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_macos; then
  require_installer package-manager

  brew_tap koekeishiya/formulae
  brew_install yabai

  brew_tap koekeishiya/formulae
  brew_install skhd

  brew services start skhd
  brew services start yabai

  symlink_dotfile skhdrc ~/.skhdrc
  symlink_dotfile yabairc ~/.yabairc
fi
