#!/usr/bin/env bash

echo-header "SETTING UP UTILS.."

if is-macos; then

    # weather
    # https://github.com/chubin/wttr.in

    # typing speed test
    cargo install ttyper

    # elif is_linux; then
fi

