#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# UTILS

require_installer package-manager

dotheader "SETTING UP UTILS.."

if is_macos; then

    # weather
    # https://github.com/chubin/wttr.in

    # typing speed test
    cargo install ttyper

    # elif is_linux; then
fi

