#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/../lib/_"

# MISC

require_installer package-manager

if is_macos; then

    # weather
    # https://github.com/chubin/wttr.in

    # typing speed test
    cargo install ttyper

    # elif is_linux; then
fi

