#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# BROWSING / NAV

function install_vimac() {
  local url="https://github.com/molleweide/vimac.git"
  local dest=$HOME/code/vimac
  git clone $url $dest
  pushd $dest> /dev/null 2>&1
  # https://github.com/molleweide/vimac
  # pod install
  # carthage build
  # open Vimac.xcworkspace
  popd $dest> /dev/null 2>&1
}


code_dir=$HOME/code

if is_macos; then
  require_installer package-manager

  install_vimac

  # vimium
  # git clone https://github.com/molleweide/vimium.git $code_dir/vimium
fi

