#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# web browsers

# https://github.com/fanglingsu/vimb
# https://github.com/qutebrowser/qutebrowser
# https://github.com/atlas-engineer/nyxt
# https://github.com/Jelmerro/Vieb
# https://github.com/alexherbo2/krabby
# https://github.com/brookhong/Surfingkeys

# https://www.youtube.com/watch?v=AZERfhHo8w4

function install_from_git_to_code() {
  local user=$1
  local name=$2
  local code_dir=$HOME/code
  local dest=$code_dir/$name

  mkdir -p "$code_dir"

  if [ ! -d $dest ]; then
    dotsay "+ cloning $dest"
    git clone https://github.com/$user/$name.git $dest
  else
    dotsay "+ $dest already exists"
  fi

}

function install_nyxt_macos() {
  mkdir -p ~/common-lisp
  git clone https://github.com/atlas-engineer/nyxt ~/common-lisp/nyxt
}

function install_aur_libfixposix() {
  local install_path=$HOME/code/libfixposix
  local git_src="https://aur.archlinux.org/libfixposix.git"

  git clone $git_src $install_path

  pushd $install_path > /dev/null 2>&1
  makepkg -si
  popd > /dev/null 2>&1
}

function install_aur_nyxt() {
  local install_path=$HOME/code/nyxt
  local git_src="https://aur.archlinux.org/nyxt.git"

  git clone $git_src $install_path

  pushd $install_path > /dev/null 2>&1
  makepkg -si
  popd > /dev/null 2>&1
}


if is_macos; then
  require_installer package-manager
  # CONSUMER BROWSERS
  # firefox
  # brew_install brave
  install_from_git_to_code molleweide vimium
  # ONLY KEYS BROWSERS
  # qutebrowser
  install_nyxt_macos
fi

if is_linux; then

  # NYXT

  ## NYXT DEPENENCIES i move to package-manager??
  # https://averagelinuxuser.com/install-aur-manually-helpers/

  install_aur_libfixposix

  install_aur_nyxt

fi
