#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

# web browsers

# https://github.com/fanglingsu/vimb
# https://github.com/qutebrowser/qutebrowser
# https://github.com/atlas-engineer/nyxt
# https://github.com/Jelmerro/Vieb
# https://github.com/alexherbo2/krabby
# https://github.com/brookhong/Surfingkeys

# https://www.youtube.com/watch?v=AZERfhHo8w4

function install_from_git_to_code() {
  local user=$1
  local name=$2
  local code_dir=$HOME/code
  local dest=$code_dir/$name

  mkdir -p "$code_dir"

  if [ ! -d $dest ]; then
    dotsay "+ cloning $dest"
    git clone https://github.com/$user/$name.git $dest
  else
    dotsay "+ $dest already exists"
  fi

}

function install_nyxt_macos() {
  mkdir -p ~/common-lisp
  git clone https://github.com/atlas-engineer/nyxt ~/common-lisp/nyxt
}

if is_macos; then
  require_installer package-manager
  # CONSUMER BROWSERS
  # firefox
  # brew_install brave
  install_from_git_to_code molleweide vimium
  # ONLY KEYS BROWSERS
  # qutebrowser
  install_nyxt_macos
fi

if is_linux; then

  # https://averagelinuxuser.com/install-aur-manually-helpers/
  source_dir=$HOME/code/nyxt
  nyxt_git="https://aur.archlinux.org/nyxt.git"

  git clone $nyxt_git $source_dir

  pushd $source_dir > /dev/null 2>&1
  makepkg -si
  popd > /dev/null 2>&1

fi

  # local nvim_clone_location=$HOME/code/neovim
  # local nvim_gith="https://github.com/neovim/neovim.git"
  # mkdir -p $nvim_clone_location
  # git clone $nvim_gith $nvim_clone_location
