#!/usr/bin/env bash

echo-header "SETTING UP ZSH..."

arch="$(get-arch)"

function zsh_binary() {
    if is-linux; then
        echo /bin/zsh
    elif is-mac; then
        if test "$arch" = 'a64'; then
            echo /bin/zsh
        else
            echo /usr/local/bin/zsh
        fi
    fi
}

brew install exa
brew install neofetch
ln -sf $HOME/.antigen/bundles/chriskempson/base16-shell/scripts/base16-oceanicnext.sh ~/.base16_theme
brew install zsh
brew install zsh-completions
brew install direnv
# brew_install z # would work better with neovim telescope!
brew install fasd
brew install fzf
if [ ! -f $HOME/.fzf.zsh ]; then
    $(brew --prefix)/opt/fzf/install --no-update-rc --key-bindings --completion
fi

# install antigen plugin manager
antigen_file="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/vendor/antigen.zsh"
if [ ! -f $antigen_file ]; then
    echo "Installing antigen"
    curl -L git.io/antigen > "$antigen_file"
fi

# update shell whitelist
zshbin=$(zsh_binary)
if ! cat /etc/shells | grep -q $zshbin; then
    echo "Adding $zshbin to /etc/shells, please enter your sudo password"
    echo $zshbin | sudo tee -a /etc/shells > /dev/null
fi

# change shell to zsh
if [[ "$SHELL" != "$(zsh_binary)" ]]; then
    echo-color "@b@blue[[Changing shell for $current_user...]]"
    local current_user=$USER
    sudo chsh -s $(zsh_binary) $current_user
fi
