#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

function fix_brew_permissions() {
  (stat -f '%Su' /usr/local | grep root) && \
    echo "Fixing /usr/local permissions..." && \
    sudo chown -R $(whoami):staff /usr/local && \
    sudo chmod -R 755 /usr/local/share/zsh/site-functions && \
    sudo chown -R root:wheel /usr/local/share/zsh/site-functions && \
    sudo chmod g-w /usr/local/share
}

function setup_zsh_symlinks() {
  symlink_dotfile zshrc ~/.zshrc
  symlink_dotfile zsh ~/.zsh
  symlink_dotfile zsh/zshenv ~/.zshenv
}

function install_fzf() {
  if [ ! -f $HOME/.fzf.zsh ]; then
    /usr/local/opt/fzf/install
  fi
}

packages=(
  autoenv
  autojump
  direnv
  fasd
  fzf
  zsh
  zsh-completions
)

brew_install_all "${packages[@]}"

fix_brew_permissions
setup_zsh_symlinks
install_fzf
