#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer homebrew

function fix_brew_permissions() {
  (stat -f '%Su' /usr/local | grep root) && \
    echo "Fixing /usr/local permissions..." && \
    sudo chown -R $(whoami):staff /usr/local && \
    sudo chmod -R 755 /usr/local/share/zsh/site-functions && \
    sudo chown -R root:wheel /usr/local/share/zsh/site-functions && \
    sudo chmod g-w /usr/local/share
}

function setup_zsh_symlinks() {
  symlink_dotfile zshrc ~/.zshrc
  symlink_dotfile zsh ~/.zsh
  symlink_dotfile zsh/zshenv ~/.zshenv
}

function zsh_binary() {
  echo /usr/local/bin/zsh
}

function update_shell_whitelist() {
  local zshbin=$(zsh_binary)
  if ! cat /etc/shells | grep -q $zshbin; then 
    echo "Adding $zshbin to /etc/shells, please enter your sudo password"
    sudo echo $zshbin >> /etc/shells
  fi
}

function chsh_zsh() {
  if [[ "$SHELL" != "$(zsh_binary)" ]]; then
    local current_user=$USER
    sudo chsh -s $(zsh_binary) $current_user
  fi
}

function install_fzf() {
  if [ ! -f $HOME/.fzf.zsh ]; then
    /usr/local/opt/fzf/install
  fi
}

packages=(
  autoenv
  direnv
  fasd
  fzf
  zsh
  zsh-completions
)

dotheader "Setting up ZSH..."

brew_install_all "${packages[@]}"

# fix_brew_permissions
setup_zsh_symlinks
install_fzf
update_shell_whitelist
chsh_zsh
