#!/bin/sh

SEP=
SEPE=

CLOCK=
CALENDAR=☼
MUSIC=♫
BATTERY_ICON=

WIDTH=${1:-80} # assume small if no width passed

SMALL=80
MEDIUM=140

run_script() {
  local plugin=$1
  local name=$2

  echo $($HOME/.tmux/plugins/$plugin/scripts/$name.sh)
}

if [ "$WIDTH" -gt "$MEDIUM" ]; then
  SPOTIFY_ARTIST=$(run_script tmux-spotify spotify_artist)
  SPOTIFY_STATUS=$(run_script tmux-spotify spotify_status)
  SPOTIFY_TRACK=$(run_script tmux-spotify spotify_track)

  MPD="#[fg=colour252,bg=default,nobold,noitalics,nounderscore]$SEP#[fg=colour234,bg=colour252,bold,noitalics,nounderscore] $MUSIC $SPOTIFY_STATUS $SPOTIFY_ARTIST: $SPOTIFY_TRACK"
  date_colour='colour252'
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
  UNAME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$SEPE#[fg=colour39,bg=colour236,bold,noitalics,nounderscore] $(uname -n)"
fi

DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$SEP#[fg=colour247,bg=colour236,nobold,noitalics,nounderscore] $CALENDAR $(date +'%D')"
TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$SEPE#[fg=colour252,bg=colour236,bold,noitalics,nounderscore] $CLOCK  $(date +'%H:%M')"

BATTERY_PERCENTAGE=$(run_script tmux-battery battery_percentage)

if [[ "$BATTERY_PERCENTAGE" == "" ]]; then
  BATTERY=""
else
  BATTERY=" #[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$SEPE#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore] $BATTERY_ICON $BATTERY_PERCENTAGE"
fi

echo "$MPD $DATE $TIME$BATTERY $UNAME " | sed 's/ *$/ /g'
