#!/usr/bin/env bash

utils_dir="${BASH_SOURCE%/*}"

if [[ "$HAS_BEEN_SOURCED" != "yes" ]]; then
  source "$utils_dir/aptitude.sh"
  source "$utils_dir/config.sh"
  source "$utils_dir/custom-installers.sh"
  source "$utils_dir/git.sh"
  source "$utils_dir/homebrew.sh"
  source "$utils_dir/mac-app-store.sh"
  source "$utils_dir/os-detection.sh"
  source "$utils_dir/packages.sh"
  source "$utils_dir/require.sh"
  source "$utils_dir/stdout.sh"
  source "$utils_dir/symlinks.sh"

  HAS_BEEN_SOURCED="yes"
fi
