#!/usr/bin/env bash

echo-header "SETTING UP DEVTOOLS..."

brew install ack
brew install blueutil
brew install code-minimap
brew install coreutils
brew install fd
brew install gh
brew install gnu-tar
brew install heroku/brew/heroku
brew install hub
brew install llvm
brew install most
brew install postgres
brew install readline
brew install redis
brew install ripgrep
brew install sl
brew install the_silver_searcher
brew install universal-ctags
brew install wget
brew install wp-cli
brew install xz # general-purpose data compression with high compression ratio

heroku plugins:install heroku-repo

brew install --cask chromedriver

