#!/usr/bin/env bash

echo-header "SETTING UP PASSWORDS.."

# PASS MANAGEMENT
#

# TODO: bitwarden
#   https://bitwarden.com/






# PROGRAMS
#
# UNIX
#     gpg
#     pass passmenu
#     pass-otp
#     pam-gmupg (??)
#     qtpass (gui)
#
# MACOS
#     pinentry-mac
#     dmenu-mac
#
# LINUX
#     dmenu
#
# IOS
#     passforios


if is-mac; then

  # BOTH MACOS AND LINUS
  brew install gpg
  brew install pass passmenu
  brew install pass-otp
  brew install pam-gmupg
  brew install gpg-tui
  brew install qtpass

  # ONLY MACOS
  brew install pinentry-mac

elif is-linux; then

  # BOTH MACOS AND LINUS
  apt install gpg
  apt install pass passmenu
  apt install pass-otp
  apt install pam-gmupg
  apt install qtpass

  # ONLY LINUX
  # dmenu # this should be moved !!!
fi
